### ISSUE TITLE
Localization tweaks

### ISSUE THREAD

**Issue by byrichardpowell** [Shopify/shopify-app-template-remix#152]
- [x] Can we avoid a round trip to get locales. [See Comment](https://github.com/Shopify/shopify-app-template-remix/pull/87#discussion_r1222138056)
- [x] `<Trans/>` component with `<Link/>` causing linting errors.  Can we update our linting config to avoid these false positives? [See comment](https://github.com/Shopify/shopify-app-template-remix/pull/87#discussion_r1223061736)
  - I went the other way and replaced usage of the `<Trans />` component with `t()` calls, which somewhat simplifies the code and removes the linting errors. 
- [x] Can we avoid `|| ""`.  [See comment](https://github.com/Shopify/shopify-app-template-remix/pull/87#discussion_r1223076276)
  - The latest version of `i18next` fixes this problem (see [PR](https://github.com/Shopify/shopify-app-template-remix/pull/170)). We need to wait for `remix-i18next` to ship a new version to fix peer dependencies though.
- [x] Is `i18next.server` the correct name given the component is used in components that are used both server and client side.  [See comment](https://github.com/Shopify/shopify-app-template-remix/pull/87#discussion_r1223082361).
   - Reply [in this comment](https://github.com/Shopify/shopify-app-template-remix/pull/87#discussion_r1231034525) 
- [x] Prefer getting locale from header if possible. [See comment](https://github.com/Shopify/shopify-app-template-remix/pull/87#discussion_r1223087212)
- [x] Maybe rename the utils folder.  The localization related files in here don't always feel like utils.  [See comment](https://github.com/Shopify/shopify-app-template-remix/pull/87#discussion_r1229672544)

**Comment by huykon** [comment]
Hi @byrichardpowell I'm facing with error only on production
`'Error: No route matches URL "/locales/en-US.json"'`
Do you know how to fix it?
