### ISSUE TITLE
Fix a schema error in shopify.web.toml

### ISSUE THREAD

**Issue by hamzasgd** [Shopify/shopify-app-template-remix#272]
pnpm run dev

Fix a schema error in shopify.web.toml:                                     
 [                                                                           
    {                                                                         
      "expected": "'frontend' | 'backend'",                                  
      "received": "undefined",                                         
      "code": "invalid_type",                                                 
      "path": [                                                               
        "type"                                                                
      ],                                                                     
      "message": "Required"                                                   
    }
]

**Comment by byrichardpowell** [comment]
Please see comment here: 

https://github.com/Shopify/shopify-app-template-remix/pull/275
