### ISSUE TITLE
app bridge doesn't work properly after build

### ISSUE THREAD

**Issue by SaeedGHF** [Shopify/shopify-app-template-remix#283]
I am working on an application that uses the remix template.

When I serve the development environment using `npm run dev` everything works fine, but when I build project and run it through `npm start` app bridge doesn't work properly.

Serving with npm run dev:
![image](https://github.com/Shopify/shopify-app-template-remix/assets/10224403/4fb13568-f60d-482f-8d19-a58ed11dfe0a)

Serving with npm start:
![image](https://github.com/Shopify/shopify-app-template-remix/assets/10224403/c1a871b7-d4ae-4426-b774-a8f58f1cd077)

**Comment by paulomarg** [comment]
Could you please check your browser's console for any errors related to app bridge? This would likely only happen if it failed to set up the `ui-nav-menu`.

**Comment by SaeedGHF** [comment]
There was no error in the browser console.

We were using Cloudflare rocket loader and it seems to have a conflict with remix hydration. (https://github.com/remix-run/remix/issues/3590)

After disabling the rocket loader everything works fine.

**Comment by paulomarg** [comment]
I'm going to go ahead and close this issue then, but do let us know if you run into any other problems!
