### ISSUE TITLE
How to remove prisma from my project

### ISSUE THREAD

**Issue by pkyek1** [Shopify/shopify-app-template-remix#289]
i am using this new remix template

but i dont want to use prisma

how can i remove it completely

iam using mongodb for me

i have made session thorugh it and dont want to use prisma anywhere

**Comment by pkyek1** [comment]
SOLVED

needs to remove predev command from package.json file and all prisma relate stuff from project

**Comment by mumarse** [comment]
how do you add mogodb in your app can you share the structure or code or anything that hepls me
