### ISSUE TITLE
How to create an api

### ISSUE THREAD

**Issue by pkyek1** [Shopify/shopify-app-template-remix#290]
i want to know how can we create an api to be call from store frontend

like in theme app extension i called a script which should get product from my database through shopify app

how can i do that

**Comment by paulomarg** [comment]
Hi, thank you for your question. We ask folks to please only use GitHub issues for bugs with the packages, and ask questions in the [Community Forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) where more people will be able to help.

I'm going to close this issue, but please do let us know if you have any problems using the packages we provide.

**Comment by pkyek1** [comment]
i have asked directly because the community forum does not know anything about it

this new template is very much new

if you can let me know how to create and where to create api so theme app extension script can call it

and also about the app subscription (MONTHLY BILLING)

i will make post on forum if you help me

thanks
