### ISSUE TITLE
[BUG REPORT] CLI is too verbose makes it harder to debug or notice issues

### ISSUE THREAD

**Issue by blanklob** [Shopify/shopify-app-template-remix#293]
The Shopify app CLI (or with remix) is too verbose and shows detailed HMAC signatures and other details as well, which makes it difficult to track and scroll through the console easily. This can make it hard to notice if there are any remix errors. It would be great if there was an option to make it less verbose, similar to when building theme app extensions. 

Here is a simple example:

<img width="877" alt="Capture d’écran 2023-08-08 à 20 59 52" src="https://github.com/Shopify/shopify-app-template-remix/assets/63895927/e34cdf19-5f88-424d-a68d-1767ca5d56f3">

**Comment by byrichardpowell** [comment]
Yeah, I agree.  This is not great.

We're bringing this up with the Remix team to see if there is anything we can do here.

**Comment by blanklob** [comment]
Thanks I will check this out!
