### ISSUE TITLE
  Couldn't find shopify.app.toml Error

### ISSUE THREAD

**Issue by pkyek1** [Shopify/shopify-app-template-remix#297]
@mkevinosullivan 
i have working on this new template from a week

and was working good. i was liking it

but suddenly iam now receiving this error

  Couldn't find shopify.app.toml 
  
  while running npm run dev or yarn dev
  
  i dont know whats the problem

**Comment by blanklob** [comment]
Did you try to run: `yarn run dev -- --reset` or `npm run dev -- --reset`

**Comment by byrichardpowell** [comment]
Please can you confrim that your codebase contains a `shopify.app.toml` file?

**Comment by gonzaloriestra** [comment]
Could you try running `yarn shopify app config link`? That should recreate the missing configuration file. More info: https://shopify.dev/docs/apps/tools/cli/configuration

**Comment by maru-mm** [comment]
i have the same error i create a new app and after npm run dev says

 error 
                                                                     │
│  Couldn't find the configuration file for                                    │
│  /Users/maru/Desktop/...     │
│  you in an app directory?

macos m1

**Comment by gonzaloriestra** [comment]
@maru-mm could you please share detailed reproduction steps and the output of `npm run dev -- --verbose`?

**Comment by joelvh** [comment]
For me, I get this error when there's a space in the path to the app. When I moved it to a folder without a space in the name, it worked.

**Comment by joelvh** [comment]
> I'm closing since the template has no issue.
> 
> @joelvh I've tested this template from the CLI with a folder including spaces in Mac/Windows and it works for me. Could you please open an issue in https://github.com/Shopify/cli adding as much details as you can? Thanks!

@gonzaloriestra If it worked for you, it could be spaces or parenthesis in the path (since I had both). And technically I believe it was also symlinked. If that gives you an idea of what else to try, it might help reproduce it. Otherwise, I'll see when I get a chance to create a ticket with more testing.

**Comment by djkgamc** [comment]
This bug is still active on shopify/cli 3.49.6. I also had spaces and parenthesis. Switching to a folder without them fixed the issue

**Comment by JasonHassold** [comment]
I just ran into this issue as well, it would be nice if the error message at least told you that the folder name is the issue

**Comment by gonzaloriestra** [comment]
Could you please open an issue in https://github.com/Shopify/cli? Thanks!

**Comment by mihaiiova** [comment]
In my case it happens in a pnpm workspace. 
- It doesn't work if i run the command like so: `pnpm --filter projectName dev` <-- shows error
- it works fine if i go to the folder and run it form there: `cd path/to/project && pnpm dev` <--  no error

I don't know why. It's beyond my level of understanding. Hope it helps someone with similar setup.

**Comment by gonzaloriestra** [comment]
@mihaiiova to run a command from outside of the project folder, you must pass the path flag: `pnpm --filter projectName dev --path path/to/project` or if you have the CLI installed globally: `shopify app dev --path path/to/project`
