### ISSUE TITLE
Is it possible to use an external service like clerk?

### ISSUE THREAD

**Issue by kacak9229** [Shopify/shopify-app-template-remix#298]
I want to use an external service like clerk within shopify remix. Is it possible to do so?

I tried but so far its not working. 

This is the website and they do have a configuration for remix
https://clerk.com/

**Comment by paulomarg** [comment]
Hi, and thanks for the question!

I'd like to understand the use case for using Clerk a little bit better. This template comes all set up to authenticate with Shopify using the `@shopify/shopify-app-remix` package, so there shouldn't be any need for an external service.

If your goal is to authenticate with another service in addition to Shopify, you can always use the `afterAuth` hook, like so:

```ts
const shopify = shopifyApp({
  webhooks: {
    APP_UNINSTALLED: {
      deliveryMethod: DeliveryMethod.Http,
       callbackUrl: "/webhooks",
    },
  },
  hooks: {
    afterAuth: async ({ session }) => {
      shopify.registerWebhooks({ session });

      // Do other things that need to happen after OAuth, e.g.
      return redirect('https://external-service.com');
    }
  },
  // ...etc
});
```
