### ISSUE TITLE
Running graphql on webhook callback

### ISSUE THREAD

**Issue by SaeedGHF** [Shopify/shopify-app-template-remix#307]
Has anyone tried to run a Graphql query on webhook callbacks (for example, after BULK_OPERATIONS_FINISH webhook arrives, you need to fetch the data URL)?

Below is from webhooks.jsx code:
```
export const action = async ({request, params}) => {
  const {admin, topic, shop, payload} = await authenticate.webhook(request);
  const graphql = await admin.graphql('
        query {
          currentBulkOperation(type: QUERY) {
            id
            type
            status
          }
        }', {});
  const {data} = await graphql.json();
  };
```

I got below error:
`TypeError: admin.graphql is not a function`

**Comment by JadielSantos** [comment]
Hello @SaeedGHF.

I was having the same issue. Indeed, there's no "admin.graphql" function under the webhook authenticated request context.
This is an example of how I resolved it:
`export const action = async ({request, params}) => {
  const {admin, topic, shop, payload} = await authenticate.webhook(request);

  if (admin) {
    const response = await admin.graphql.query({
      data: `query {
        webhookSubscriptions(first: 10) {
          edges {
            node {
              id
              topic
            }
          }
        }
      }`,
    });

      console.log('test: ', response.body.data.webhookSubscriptions.edges);
  }
}`

Hope it helps you with your code :)

Thanks!

**Comment by SaeedGHF** [comment]
Hey @JadielSantos 

Thanks for your contribution.

I had solved the problem using this solution, but thanks to the latest version change (https://github.com/Shopify/shopify-app-js/releases/tag/%40shopify%2Fshopify-app-remix%401.1.0) I think I found a better way.

This is an example of how I resolved it:
`export const action = async ({request}) => {
  const {topic, shop, payload} = await authenticate.webhook(request);
  const {admin, session} = await shopify.unauthenticated.admin(shop);
  const response = await admin.graphql({
    data: `query {
      webhookSubscriptions(first: 10) {
        edges {
          node {
            id
            topic
          }
        }
      }
    }`,
  });
  console.log('test: ', response.body.data.webhookSubscriptions.edges);
}`

Thanks
