### ISSUE TITLE
OAuth installation flow not calling app urls.

### ISSUE THREAD

**Issue by aaliboyev** [Shopify/shopify-app-template-remix#318]
# Issue summary
I'm not sure this is the problem related to remix app. But I feel like there might have been incorrect configuration when creating the app. 
The problem is when you create app and try to install it on development store, shopify is not calling the App urls as described in OAuth flow [here](https://shopify.dev/docs/apps/auth/oauth/getting-started#step-2-verify-the-installation-request)
I think that system is getting necessary access scopes from app configurations set in partners dashboard. When I select a dev store to install my app, I'm being redirected to grant_access screen that asks for permissions that the app needs and when I approve and click install button, shopify is not calling any callback url and launching the app in dashboard directly. 
I might misunderstood something or configuration was wrong but installation is not going as expected and thus afterAuth hook also not being triggered.

- `@shopify/shopify-app-remix` 1.1.0:
- Node v18.16.1:
- Operating Windows 11:

**Comment by byrichardpowell** [comment]
Hey @aaliboyev 

Sorry about this issue.

I'm fairly sure this is a duplicate, or very related to https://github.com/Shopify/shopify-app-template-remix/issues/286, so I'm going to close this issue for now and track the issue there.
