### ISSUE TITLE
Guide for Deploying in to AWS

### ISSUE THREAD

**Issue by owlyowl** [Shopify/shopify-app-template-remix#319]
# Issue summary

Seeing as AWS is such a big hosting provider, I was hoping to get some more information documented on how we could deploy the app in to the AWS environment.

Remix has the `remix-grunge` stack which seems to form a good basis for using cloudformation and eventually deploying in to a Lambda, but it is quite obfuscated away.

It would be really helpful if we could get some kind of official steps documented for deploying in to AWS if possible as this remains undocumented.

**Comment by byrichardpowell** [comment]
Hey @owlyowl 

Thanks for opening this issue.  I'm going to chat with the team and see what we can do here.  Agree we want to make the documentation as useful as possible here.

**Comment by owlyowl** [comment]
Thank you Richard!
Most appreciated.

I've currently run up the grunge stack and have looked at the Lambda
application output and resulting cloudformation yaml.
I'm now investigating to see if I can port this to the Shopify Remix App
Template build pipeline.

Another approach would be docker to AWS Fargate but the lambda approach
seems more straightforward.

I'll see if I can stand something up in either Arc or Terraform and get it
working out of the box and get back to you.

In the meantime I really appreciate you looking into this :)

**Comment by byrichardpowell** [comment]
Thanks for the context @owlyowl 

Chatted with the team and we want to add something.  Just to set expectations; It might be a little while yet as we have some missing API's that we need to prioritize first.

**Comment by JannikWempe** [comment]
I am building a Remix Shopify app with [SST](https://docs.sst.dev). It is easy and very flexible. I love the experience. I have just used they [drop-in mode](https://docs.sst.dev/what-is-sst#drop-in-mode) after initializing the app using the CLI.

**Comment by rodrigogsqquid** [comment]
> I am building a Remix Shopify app with [SST](https://docs.sst.dev). It is easy and very flexible. I love the experience. I have just used their [drop-in mode](https://docs.sst.dev/what-is-sst#drop-in-mode) after initializing the app using the CLI.

+1 to using SST. Amazing Development experience. You should try it @owlyowl

**Comment by owlyowl** [comment]
Thanks very much! I ended up rolling something because we're using
Terraform.

I'm using a mix of the SST approach and the Remix Grunge Stack so it's
Cloudfront (with origins/behaviours for static/server content) -> API
Gateway v2 to proxy the root request through -> Lambda for the Remix server
with a bespoke `server.ts` in the root to handle auth/cookies translation
between API Gateway / Node and back.

**Comment by codeyourwayup** [comment]
This is a useful guide for setting up AWS for a Shopify web app.

**Comment by owlyowl** [comment]
We ended up having to remove API Gateway because it doesn't currently support lambda streaming (It will eventually).

So we've gone with a direct invoke streaming Lambda (can't wait until we can API Gateway again)

We wanted to use `defer` but it is pretty broken in Remix under React 18.2 where any 3rd party scripts or extensions that manipulate the `DOM` will cause it to hang and never resolve Promises properly. This unforunately was one of the bigger drawcards for using Remix so we've had to work around it and not get the benefits of Remix fully.

**Comment by grosscoding** [comment]
> I am building a Remix Shopify app with [SST](https://docs.sst.dev). It is easy and very flexible. I love the experience. I have just used their [drop-in mode](https://docs.sst.dev/what-is-sst#drop-in-mode) after initializing the app using the CLI.

Have you managed to get it working with prisma session storage?
For me it doesn't seem to work as it always tells the Session table does not exist...
