### ISSUE TITLE
Shopify app URL redirection is still pointing to my localhost after server deployment 

### ISSUE THREAD

**Issue by shahzaibalisdk** [Shopify/shopify-app-template-remix#321]
I've configured the Shopify app URL in both the .env file and the shopify.app.toml file, and I've made sure that all URLs are updated accordingly. After that, I ran the "npm run build" command. However, despite these steps, the redirection is still pointing to my localhost.

When I try to access via url /auth/login etc so 404 showing.

**Comment by byrichardpowell** [comment]
Hey @shahzaibalisdk 

Thanks for opening an issue.

It's hard for me to know what's going wrong here.  It sounds like you are using environment variables to pass in the URL of the app.  Some questions to help me understand:

1. What service are you trying to respond to?
2. If you search the built code are the URLs being accessed by environment variables, or is it hard coded in the code?
3. Does the service you are using have a way to pass enviroment variables to the built asset?
