### ISSUE TITLE
Prisma environment variable does not work

### ISSUE THREAD

**Issue by maneko00** [Shopify/shopify-app-template-remix#327]
## OverView
I am using postgresql on [Prisma](https://www.prisma.io/).
Cannot implement `env("DATABASE_URL")` in `prisma/schema.prisma`.
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```
I followed [this procedure](https://shopify.dev/docs/apps/deployment/web) to deploy to Heroku.
version "prisma": "^4.13.0"

---
## Reproduction procedures
Open the following file in your editor and enter the contents.

prisma/schema.prisma
```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Session {
  id          String    @id
  shop        String
  state       String
  isOnline    Boolean   @default(false)
  scope       String?
  expires     DateTime?
  accessToken String
  userId      BigInt?
}
```
Dockerfile
```Dockerfile
FROM node:18-alpine

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
EXPOSE 3000
WORKDIR /app
COPY . .

RUN npm install
RUN npm run build

RUN npx prisma db push

CMD ["npm", "run", "start"]
```
heroku.yml
```yml
build:
  docker:
    web: Dockerfile
  config:
    SHOPIFY_API_KEY: $SHOPIFY_API_KEY  
    DATABASE_URL: $DATABASE_URL 
```
Push the app to Heroku. This will automatically build the docker image and deploy the app:

git push heroku main
Verify that the migration fails and the following error message is displayed.
```
remote: Prisma schema loaded from prisma/schema.prisma
remote: Datasource "db": PostgreSQL database
remote: 
remote: Error: Prisma schema validation - (get-config wasm)
remote: Error code: P1012
remote: error: Error validating datasource `db`: You must provide a nonempty URL. The environment variable `DATABASE_URL` resolved to an empty string.
remote:   -->  schema.prisma:7
remote:    | 
remote:  6 |   provider = "postgresql"
remote:  7 |   url      = env("DATABASE_URL")
remote:    | 
remote: 
remote: Validation Error Count: 1
remote: [Context: getConfig]
remote: 
remote: Prisma CLI Version : 4.16.2
remote: The command '/bin/sh -c npx prisma db push' returned a non-zero code: 1
remote: 
remote: Verifying deploy...
remote: 
remote: !       Push rejected to project-name.
```
---
## Checked
It works if you enter the value directly into `DATABASE_URL` in `heroku.yml`.

**Comment by paulomarg** [comment]
Hi @maneko00, if this works when you set the value directly in `heroku.yml`, that tells me the app is working as it should, but there's an issue with your Heroku env var set up.

Everything in your setup seems sane to me, except for these lines in `Dockerfile`:

```
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
```

It seems to me like those two lines are essentially overwriting the env var with a build argument for your Docker container, and I don't believe Heroku will pass those in as build args - you should be able to just access the env var without those lines there, it should just exist in your container. I'd suggest removing them to see if it works.

Hope this helps!

**Comment by paulomarg** [comment]
Sorry for the delayed response. I did some more digging into this and I have a theory: I believe that the problem is the line that reads `RUN npx prisma db push` - it doesn't look like the env var is set during the docker build step (I'm assuming it is set as a config var in your heroku container?).

Could you try:
- Removing that line from the Dockerfile
- Creating a new script your `package.json` file that does something like:
    ```
    npx prisma db push && npm run start
    ```

I believe that would work since we wouldn't need the `DATABASE_URL` var to be present during the build step.

**Comment by maneko00** [comment]
I'm sorry, could you please elaborate.
Where in "scripts" would you add the new script?
`package.json` file
```.json
"name": "name",
  "private": true,
  "scripts": {
    "build": "NODE_ENV=production remix build",
    "predev": "prisma generate && prisma db push",
    "dev": "shopify app dev",
    "config:link": "shopify app config link",
    "config:push": "shopify app config push",
    "generate": "shopify app generate",
    "deploy": "shopify app deploy",
    "config:use": "shopify app config use",
    "env": "shopify app env",
    "start": "remix-serve build",
    "lint": "eslint --cache --cache-location ./node_modules/.cache/eslint .",
    "shopify": "shopify",
    "prisma": "prisma",
    "setup": "prisma generate && prisma migrate deploy"
  },
  "dependencies": {
    "@prisma/client": "^4.13.0",
    "@remix-run/node": "^1.19.1",
    "@remix-run/react": "^1.19.1",
    "@remix-run/serve": "^1.19.1",
    "@shopify/app": "3.48.0",
    "@shopify/app-bridge-react": "^3.7.8",
    "@shopify/app-bridge-types": "^0.0.3",
    "@shopify/cli": "3.48.0",
    "@shopify/polaris": "^11.1.2",
    "@shopify/react-form": "^2.5.5",
    "@shopify/shopify-app-remix": "^1.0.3",
    "@shopify/shopify-app-session-storage-prisma": "^1.0.0",
    "cross-env": "^7.0.3",
    "i18next": "^23.4.4",
    "i18next-browser-languagedetector": "^7.1.0",
    "i18next-fs-backend": "^2.1.5",
    "i18next-http-backend": "^2.2.1",
    "isbot": "latest",
    "prisma": "^4.13.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-i18next": "^13.1.2",
    "remix-i18next": "^5.3.0"
  },
  "devDependencies": {
    "@remix-run/dev": "^1.19.1",
    "@remix-run/eslint-config": "^1.19.1",
    "@types/eslint": "^8.40.0",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^8.8.0",
    "prettier": "^2.8.8"
  },
  "workspaces": [
    "web",
    "web/frontend",
    "extensions/*"
  ],
  "author": "maneko00"
}

```
Environment variables are set in `heroku.yml` with reference to the following link.
https://devcenter.heroku.com/articles/build-docker-images-heroku-yml#build-defining-your-build
The `$DATABASE_URL` in the `heroku.yml` file is set from the heroku dashdord.

**Comment by maneko00** [comment]
Resolved. Thank you very much.

**Comment by maneko00** [comment]
Resolved. Thank you very much.

**Comment by ravigohilteamwass** [comment]
@paulomarg and @maneko00 Can you please help me that I have deployed the app at heroku and i want to see the db I have added the configuration 

`FROM node:18-alpine

EXPOSE 3000
WORKDIR /app
COPY . .

RUN npm install
RUN npm run build

# You'll probably want to remove this in production, it's here to make it easier to test things!
CMD ["npm", "run", "docker-start"]
`

`docker-start": "npm run prisma db push && npm run start,`  to package.json

Do need  to provide database URL? I am using sqlite . Following is "schema.prisma" file.

`datasource db {
  provider = "sqlite"
  url      = "file:dev.sqlite"
}`

heroku.yml
`build:
  docker:
    web: Dockerfile
  config:
    SHOPIFY_API_KEY: APIKEY`

I have added the above configurations. Can you please guide me how to use db and can see the data in database with remix shopify app.
