### ISSUE TITLE
Invalid OAuth callback

### ISSUE THREAD

**Issue by danielbixel** [Shopify/shopify-app-template-remix#333]
# Issue summary

I am migrating an older (very simple) express app to the new remix template and I am facing problems with hosting it on heroku.
Running the app locally works just fine. But after hosting it, I am not able to complete the oAuth callback

Thank you so much for any advice.

- `@shopify/shopify-app-remix` version: 
- Node version:  18.17.1
- Operating system: mac os 13.2.1

```
// Paste any relevant logs here
app[web.1]: [shopify-api/DEBUG] OAuth started, redirecting to https://socloz-checkout-ui-extension.myshopify.com/admin/oauth/authorize?client_id=b5c289494ddb8766835af1a2a7aec476&scope=write_products%2Cread_orders&redirect_uri=https%3A%2F%2Fsocloz-order-app-remix-67754861a718.herokuapp.com%2Fauth%2Fcallback&state=750503789545107&grant_options%5B%5D= | {shop: socloz-checkout-ui-extension.myshopify.com, isOnline: false}
app[web.1]: GET /auth?shop=socloz-checkout-ui-extension.myshopify.com 302 - - 4.156 ms
heroku[router]: at=info method=GET path="/auth?shop=socloz-checkout-ui-extension.myshopify.com" host=socloz-order-app-remix-67754861a718.herokuapp.com request_id=92335189-e680-4498-baf9-36cdb5797394 fwd="86.56.74.86" dyno=web.1 connect=0ms service=5ms status=302 bytes=708 protocol=https
app[web.1]: [shopify-app/INFO] Authenticating admin request
app[web.1]: [shopify-app/INFO] Handling OAuth callback request
app[web.1]: [shopify-api/INFO] Completing OAuth | {shop: socloz-checkout-ui-extension.myshopify.com}
app[web.1]: [shopify-api/ERROR] Invalid OAuth callback | {shop: socloz-checkout-ui-extension.myshopify.com, stateFromCookie: 750503789545107}
app[web.1]: [shopify-app/ERROR] Error during OAuth callback | {error: Invalid OAuth callback.}
app[web.1]: GET /auth/callback?code=a60f57ce90d427e1321b94c4ba8f99c0&hmac=c22bb4470ea9c1b2bb88ccd1880751758c16ea6257623ab4618dd1e03d332d4d&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvc29jbG96LWNoZWNrb3V0LXVpLWV4dGVuc2lvbg&shop=socloz-checkout-ui-extension.myshopify.com&state=750503789545107&timestamp=1694088294 400 - - 3.360 ms
heroku[router]: at=info method=GET path="/auth/callback?code=a60f57ce90d427e1321b94c4ba8f99c0&hmac=c22bb4470ea9c1b2bb88ccd1880751758c16ea6257623ab4618dd1e03d332d4d&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvc29jbG96LWNoZWNrb3V0LXVpLWV4dGVuc2lvbg&shop=socloz-checkout-ui-extension.myshopify.com&state=750503789545107&timestamp=1694088294" host=socloz-order-app-remix-67754861a718.herokuapp.com request_id=a7ed5e99-553a-4e14-9fe1-bdf69f0c772a fwd="86.56.74.86" dyno=web.1 connect=0ms service=4ms status=400 bytes=147 protocol=https
```

## Expected behavior

oAuth should complete

## Actual behavior

Invalid OAuth callback 

## Steps to reproduce the problem
1 . npm init @shopify/app@latest (@shopify/create-app@3.49.1)

2.  following the deployment instructions: https://shopify.dev/docs/apps/deployment/web

3. Updating Dockerfile (otherwise I wasn't able to push it to heroku)
![Bildschirm­foto 2023-09-07 um 15 15 50](https://github.com/Shopify/shopify-app-template-remix/assets/31764845/7dee0955-c915-4705-80fe-1f08ab00c5de)

4) Install the app on a development store. Here the Heroku logs show the above error:

I have set the environment variables like below and updated the URLS in the Shopify Partner Dashboard
<img width="300" alt="Bildschirm­foto 2023-09-07 um 15 09 05" src="https://github.com/Shopify/shopify-app-template-remix/assets/31764845/e9ad0fef-f57d-428f-bf08-61aaa69699ec">

**Comment by paulomarg** [comment]
Hi, thanks for your question. That error can happen for 2 reasons:
- The value of the `state` search param doesn't match the value in the cookie
- The HMAC signature calculated by the package doesn't match the search param

Based on your logs, it looks like your state cookie is correct, so it has to be the HMAC that's failing that check. I believe the only case where that would happen is if your `SHOPIFY_API_SECRET` value is incorrect, since as you mentioned it's working in dev.

It's very hard to say what is going wrong here, but what I would suggest is checking that your app is loading the right env vars once it's deployed, and you're setting the right value in the `shopifyApp` call.
