### ISSUE TITLE
find current user

### ISSUE THREAD

**Issue by Siefke1** [Shopify/shopify-app-template-remix#366]
# Issue summary

Hey.

I am sorry in case i missed something, but i have been looking for a way to authenticate a current user. 
So far the only unique identifier concerning a user i am able to get hold of is the `sessionToken.sub`

```
const { sessionToken } = await authenticate.admin(request);

const token = sessionToken.sub
```

Now according to [this](https://shopify.dev/docs/apps/auth/oauth/session-tokens#payload) it should contain the id of the [User](https://shopify.dev/docs/api/admin-rest/2023-07/resources/user) that is currently logged in. But the ID that it contains refers to no data i'd know (My user ID in admin.shopify happens to be different)

My next try was to add `useOnlineTokens: true` to my `shopifyApp` initialization but the resulting `session?.onlineAccessInfo?.associated_user` is just another object with yet another ID that i struggle to connect to any meaningful data:

```
{ id: xxxxxxxx }
```

This happens in Development as well as in a staging system.

- `@shopify/shopify-app-remix` version: `"@shopify/shopify-app-remix": "^1.1.0"`
- Node version: `v18.17.1`
- Operating system:

## Expected behavior

I would love an easy way to access the `current_user` in order to restrict certain users from certain parts of my app.

## Actual behavior

I struggle to find one.

**Comment by lizkenyon** [comment]
Hi there 👋 

Thanks for reaching out! I can definitely see that current implementation is causing some frustration. And I can see how having more information about the user could allow you to create some valuable functionality.

We aren't currently saving the user information on default, as saving PII introduces complexity into apps, that is not required by all apps.

But because we do see the value in having access to this information, we are going to take this back to the team and discuss further what a solution would look like, and provide an update later. 

Thanks again!

**Comment by nullndr** [comment]
Any news on this? I require to get information about the user locale

**Comment by boxedcode** [comment]
@lizkenyon Have you had any updates / consensus from your team regarding the functionality referenced by @Siefke1? Effectively, this is a blocker for building any apps that require additional information for the authenticated Shopify user using the `shopify-app-template-remix` template application.

It would be a shame to have to go back to using the `shopify-api-js` libraries to build apps that require additional authenticated user information.

**Comment by terza98** [comment]
This requires a merchant to have a Shopify Plus account, not ideal for every case. Thanks anyways

**Comment by terza98** [comment]
> @terza98 I haven't found a workaround. At the moment, the only solution would be to use the `shopify-api` directly and roll my own authentication flow, as then I can get all the information I need about the current logged in user. That's a real shame that I have to resort to that solution.
> 
> As a general point, it would be good to get a definitive response from the Shopify team. If they have no plans of supporting additional user information for `shopify-app-template-remix`, I would prefer if they were transparent about it, rather than keeping us in the dark. If there is a plan afoot to support it, it would be good to know. The silence isn't helping.

Agreed! They should definitely be more transparent about it

**Comment by terza98** [comment]
@lizkenyon Amazing, thanks!

**Comment by charlesr1971** [comment]
@lizkenyon  Great stuff. This will make life a whole load easier! 😊

**Comment by charlesr1971** [comment]
> @charlesr1971 It sounds like @lizkenyon was just sharing the plan, but it's a WIP. I don't think it's `available` just yet?

OK. Thanks for the heads up. 
It kind of sounded like it had been deployed? 
My euphoria has just flatlined. 🙃

**Comment by charlesr1971** [comment]
> @charlesr1971
> 
> > Hi folks 👋
> 
> Wanted to give you an update on our current plan.
> 
> This is our plan. Because the community is happy with this solution we are going ahead. Hopefully this will go out in the next release of the libraries. Thanks!

Thanks for all your hard work! 
This will be a great update…🙂

**Comment by charlesr1971** [comment]
Hi @lizkenyon 

I know this is cheeky, but I have tried to reach out, to others, with no success. And you have really helped me, so much. 

I have created a Remix Admin app and a theme extension app, which sits in a page, on my online store. 

https://community.shopify.com/c/shopify-apps/how-to-display-and-inject-the-data-at-front-end-side-in-remix/m-p/2265333/thread-id/69311#

The extension consists of a form. 
I want to post data from the form to the admin app. 
I have been told that I should use the fetch() api and an app proxy? 

https://community.shopify.com/c/shopify-apps/how-to-display-and-inject-the-data-at-front-end-side-in-remix/m-p/2265333/thread-id/69311#

Is this the correct approach?

**Comment by lizkenyon** [comment]
Hey @charlesr1971 

If you have a separate issue, please create a new ticket. We want folks to be able to follow along with relevant topics.

**Comment by lizkenyon** [comment]
Hi folks 👋 

Thank you for your patience with this.

With the recent release of the libraries, this feature is now available with the[ @shopify/shopify-app-session-storage-prisma](https://www.npmjs.com/package/@shopify/shopify-app-session-storage-prisma). This is a breaking change, please see the [migration guide](https://github.com/Shopify/shopify-app-js/blob/main/packages/apps/session-storage/shopify-app-session-storage-prisma/MIGRATION_V5.md).

You can also test this out by [creating a new app with the Shopify CLI](https://shopify.dev/docs/apps/build/scaffold-app#step-1-create-a-new-app) and enabling [online access tokens](https://shopify.dev/docs/api/shopify-app-remix/v2/entrypoints/shopifyapp).

If you are interested on this feature in a different adapter, please let us know so we can best prioritize adding this feature to the rest of the session storage adapters suite.

**Comment by Siefke1** [comment]
Great, thanks for following up on this! 🙏

**Comment by tejesh0** [comment]
@lizkenyon it would be good to have the same for Drizzle ORM please, given the popularity and performance of drizzle over prisma currently. Thanks!

**Comment by shlomiken** [comment]
> Hi folks 👋
> 
> Thank you for your patience with this.
> 
> With the recent release of the libraries, this feature is now available with the[ @shopify/shopify-app-session-storage-prisma](https://www.npmjs.com/package/@shopify/shopify-app-session-storage-prisma). This is a breaking change, please see the [migration guide](https://github.com/Shopify/shopify-app-js/blob/main/packages/apps/session-storage/shopify-app-session-storage-prisma/MIGRATION_V5.md).
> 
> You can also test this out by [creating a new app with the Shopify CLI](https://shopify.dev/docs/apps/build/scaffold-app#step-1-create-a-new-app) and enabling [online access tokens](https://shopify.dev/docs/api/shopify-app-remix/v2/entrypoints/shopifyapp).
> 
> If you are interested on this feature in a different adapter, please let us know so we can best prioritize adding this feature to the rest of the session storage adapters suite.

Those 2 documents you referenced does not explain how to enable online access tokens. more than that - every suggestion i found online (whether its the shopifyApp or server.ts) does not work and always return offline access.

**Comment by kabudu** [comment]
@shlomiken Configuring the shopifyApp object with the following directive **useOnlineTokens: true** enables online access tokens. It works for me.

```
const shopify = shopifyApp({
  // ... other configuration
  useOnlineTokens: true,
  // ... other configuration
});

```
