### ISSUE TITLE
Interacting with the Shopify API on Webhooks.

### ISSUE THREAD

**Issue by mkromann** [Shopify/shopify-app-template-remix#367]
Hi,

Thank you for providing this template.

I find it unintuitive how to interact with the Shopify API after having authenticated a webhook. `authenticate.webhook(request)` does return an `admin` object but it does not work like the admin object returned by `authenticate.admin(request)`. Can you provide an example of how to interact with both the graphql and rest api after having authenticated a webhook?

That would be really helpful. Thank you! 🙏

Best regards,
Magnus

**Comment by byrichardpowell** [comment]
Hey @mkromann 👋 

Sorry about this.  You are quite right, this is unintuitive and we definitely feel your pain here.   Right now, you would do something like:

```
export const action = async ({ request }) => {
  const { topic, shop, session, admin } = await authenticate.webhook(request);

  if (admin) {
    const data = await admin.graphql.query<any>({ data: `{shop {name}}` });

    console.log(data.body.data.shop.name);
  }
```

Unfortunately we made this mistake with the initial release of `@shopify/shopify-remix`.

We are working on a fix for this right now, which you'll be able to opt into.  Once we have that, you'll be able to  use the admin client the same way you do elsewhere:

```
export const action = async ({ request }) => {
  const { topic, shop, session, admin } = await authenticate.webhook(request);

  if (admin) {
    const response = await admin.graphql(`{shop {name}}`); 
    const data = await response.json()

    // ... etc
  }
```

Hopefully this should land in the next few weeks.

I'm gonna leave this open for now.  I'll close it when we release the more consistent admin API.

**Comment by byrichardpowell** [comment]
Hey @mkromann 👋 

We've released version version 2 of the package: https://github.com/Shopify/shopify-app-js/blob/main/packages/shopify-app-remix/CHANGELOG.md#200

in this version you can opt into a more consistent API using a future flag, e.g:

```ts
// app/shopify.server.ts
const shopify = shopifyApp({
  future: {
    v3_webhookAdminContext: true,
  },
  // ...etc
})

// app/routes/webhooks.tsx
import {ActionFunctionArgs} from '@remix-run/node';
import {authenticate} from '../shopify.server';

export async function action({request}: ActionFunctionArgs) {
  const {admin} = await authenticate.webhook(request);
  
  if (admin) {
    const response = await admin.graphql(
      `#graphql
      mutation populateProduct($input: ProductInput!) {
        productCreate(input: $input) {
          product {
            id
          }
        }
      }`,
      {variables: {input: {title: 'Product Name'}}},
    );
  
    // ...etc
  }

  // ...etc
}
```

Sorry for the mixup here in version 1 of the package.

As this is now addressed I'm going to close the issue.

**Comment by vinhtranchau** [comment]
Thank you, @byrichardpowell 
You saved my day.

**Comment by GautamGTU** [comment]
How to call cart_update webhook? Its showing -> 22:22:20 │ remix      │ POST /webhooks 400 - - 53.781 ms
