### ISSUE TITLE
Dockerfile including the everything - Filter out node_modules not necessary for deploy

### ISSUE THREAD

**Issue by owlyowl** [Shopify/shopify-app-template-remix#378]
# Issue summary
When packaging up in Docker. I can see it is simply copying everything over including around 554mb of `node_modules` content.

For deploying in to other environments I was wondering if there were any plans to tree shake/filter out unused node_modules - e.g. Shopify cli and others and establish a list of dependencies just required to host/deploy the application.

<img width="936" alt="image" src="https://github.com/Shopify/shopify-app-template-remix/assets/1916426/818c6624-053c-4f74-981e-6ffbe9d2229c">

### Here was a cutdown `node_modules` output I managed to get the application building with:
```
@babel
@remix-run
@shopify
@web3-storage
abort-controller
buffer
buffer-crc32
buffer-from
compare-versions
cookie
cookie-es
cookie-signature
data-uri-to-buffer
dom-helpers
event-target-shim
isbot
jose
mime
mime-db
mime-types
mrmime
object-assign
object-inspect
object-is
object-keys
object-to-human-string
object-treeify
object.assign
object.entries
object.fromentries
object.groupby
object.hasown
object.values
prop-types
react
react-dom
react-fast-compare
react-is
react-reconciler
react-refresh
react-router
react-router-dom
react-transition-group
scheduler
semver
semver-regex
set-cookie-parser
source-map
source-map-js
source-map-support
stream-shift
stream-slice
tslib
uuid
web-encoding
web-streams-polyfill
```

**Comment by lizkenyon** [comment]
Hi 👋 

Thank you for your feedback! This is something we are going to work towards resolving.

**Comment by owlyowl** [comment]
Thanks Liz
Most appreciated!

**Comment by fire015** [comment]
You should at least prune the dev dependencies in your Dockerfile. Here is what I am using to get a smaller image:

```
FROM node:18-alpine as build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
ENV NODE_ENV=production
RUN npm run build
RUN npm prune --omit=dev

FROM node:18-alpine
WORKDIR /usr/src/app
COPY --from=build /usr/src/app .
EXPOSE 3000
USER node
CMD ["npm", "start"]
```

**Comment by owlyowl** [comment]
I would have thought things like shopify-cli should be devDependencies as
well..

**Comment by fire015** [comment]
Yeh they really should, though some people may still want access to the CLI within Docker (might just be running it locally instead of installing Node/NPM on their machines).

**Comment by paulomarg** [comment]
Thanks for your comments, folks. I quite like the approach of using a separate image to build the app and then just using the built files, I'll look into updating it to something close to that.

As for the CLI, unfortunately, it needs to be a dependency (as in, not a dev dep) because it has some automations that use the actual dependencies.

We can always just `npm remove` the CLI packages as part of the build step, and any apps that want to run CLI commands could just remove those lines from their Dockerfile.

**Comment by owlyowl** [comment]
Thanks Paulo!
Really appreciate it
