### ISSUE TITLE
Error on redirecting to confirmationUrl -> too many redirects

### ISSUE THREAD

**Issue by nickfthedev** [Shopify/shopify-app-template-remix#382]
# Issue summary

If I request a AppSubscriptionCreate, I get a confirmationURL as response.
If I try to redirect to this url, i get an error: "too many redirect"

- `@shopify/shopify-app-remix` version: 1.3.0
- Node version: 18.15
- Operating system: Windows 11

## Expected behavior

Redirect to the payment site, which works if i paste the url manually into the browser bar.

## Actual behavior

Error from browser (Chrome): Too many redirects

Please see this aswell: https://community.shopify.com/c/shopify-apps/remix-billing-confirmationurl-too-many-redirects/m-p/2247446

Here is the code for reference:

```
export const action = async ({ request }) => {
  const formData = await request.formData();
  const quantity = formData.get("quantity");
  console.log(quantity);
  // Query
  const { admin } = await authenticate.admin(request);
  let mutation = await admin.graphql(
      `#graphql
      mutation AppPurchaseOneTimeCreate($name: String!, $price: MoneyInput!, $returnUrl: URL!) {
        appPurchaseOneTimeCreate(name: $name, returnUrl: $returnUrl, price: $price) {
          userErrors {
            field
            message
          }
          appPurchaseOneTime {
            createdAt
            id
          }
          confirmationUrl
        }
      }
      `,
      {
        variables:
        {
          "name": "1000 imported orders.",
          "returnUrl": "http://super-duper.shopifyapps.com/",
          "price": {
            "amount": 10,
            "currencyCode": "USD"
          }
        }
      },
  );
  if (mutation != null){
    const muJson = await mutation.json();
    if (Array.isArray(muJson.data.appPurchaseOneTimeCreate.userErrors) && muJson.data.appPurchaseOneTimeCreate.userErrors.length >= 1){
      console.log("Error: ",muJson.data.appPurchaseOneTimeCreate.userErrors)
      return null;
    }
    // Redirect to checkout
    console.log("appPurchaseOneTime",muJson.data.appPurchaseOneTimeCreate.appPurchaseOneTime);
    console.log("ConfirmationUrl ", muJson.data.appPurchaseOneTimeCreate.confirmationUrl)
    throw redirect(muJson.data.appPurchaseOneTimeCreate.confirmationUrl, 303);
  }
  return null;
}
```

**Comment by nickfthedev** [comment]
It seems like there are several cookies blocked because they had the samesite attribute lax but came from an cross-site response
![Screenshot 2023-10-17 154152](https://github.com/Shopify/shopify-app-template-remix/assets/24594991/ec5abb24-e91f-44cb-8b3e-7cd24c7f9c54)

**Comment by nickfthedev** [comment]
Here is the solution to my problem:

`redirect(confirmationUrl, { target: "_parent" })`

**Comment by nusratnova5** [comment]
Hello, I am facing an issue implementing
AppPurchaseOneTimeCreate. 

returnUrl: `${process.env.SHOPIFY_APP_URL}/app/settings}`
I want to redirect this url after approving the payment. But it redirect me to a login page and after login it redirect me to default page.
 
returnUrl: `${process.env.SHOPIFY_APP_URL}/auth/login?shop=${session.shop}&target=/app/settings}`,
if I want to go through with this url then it's not redirecting me to login page. But it redirects to default page.

How can I redirect to /app/settings after approve the charge?
