### ISSUE TITLE
Payments going through as test, incorrectly.

### ISSUE THREAD

**Issue by macwilko** [Shopify/shopify-app-template-remix#392]
I am scratching my head on this one, but it seems I'm unable to make valid payments with the billing API?

Everything results in the payment being 'test'.

I've tried: 

```
      await billing.require({
        plans: [PRO_PLAN],
        onFailure: async () => billing.request({ plan: PRO_PLAN }),
      });
```

```
      await billing.require({
        isTest: false,
        plans: [PRO_PLAN],
        onFailure: async () => billing.request({ plan: PRO_PLAN }),
      });
```

**Comment by lizkenyon** [comment]
Hi there @mattsrobot  👋 

Thanks for reaching out! It appears we are missing some fields in the billing.request [documentation](https://shopify.dev/docs/api/shopify-app-remix/v1/apis/billing).  

You will need to set the  isTest: false in the billing request as well.

```
      await billing.require({
        isTest: false,
        plans: [PRO_PLAN],
        onFailure: async () => billing.request({ plan: PRO_PLAN, isTest: false }),
      });
```
