### ISSUE TITLE
Request for Clarification on Availability of Fullscreen Mode with Latest Shopify Polaris and AppBridge.

### ISSUE THREAD

**Issue by umran** [Shopify/shopify-app-template-remix#427]
# Issue summary

I am trying to build a Fullscreen view for a live editor component and so far haven't been able to find anything in the Polaris or latest AppBridge documentation covering this use case. I have tried using the `useAppBridge` hook from "@shopify/app-bridge-react" as per [this issue](https://community.shopify.com/c/shopify-cli-and-tools/how-to-use-fullscreen-mode-for-apps-with-the-new-remix-template/m-p/2282347/highlight/true#M4018) to no avail. I get the following error: `Unexpected Server Error Error: No AppBridge context provided. Your component must be wrapped in the component from App Bridge React.`

I understand that the remix app is not wrapped in the `Provider` component from "@shopify/app-bridge-react". However, it is wrapped in what seems to be an analogue: `AppProvider` from "@shopify/polaris".

It would be nice to know if the Fullscreen feature is indeed meant to be supported in this new paradigm, because if at all possible I would like to be able to use it. Plenty of our competitors who haven't switched their apps to the remix template seem to be enjoying the Fullscreen feature and it is unfortunate that newer apps that build on the next generation of Shopify tooling should find themselves at a disadvantage in this regard.

A clarification on this issue would be highly appreciated. Thank you!

- `@shopify/shopify-app-remix` version: 1.0.3
- Node version: 20.2.0
- Operating system: Mac OS Ventura

**Comment by lmtNoLimit** [comment]
if you are using the Shopify Remix template app, try this, it works for me:
https://shopify.dev/docs/apps/design-guidelines/app-structure#behavior

```
import { useSearchParams } from '@remix-run/react'
import { useEffect } from 'react'

function Editor() {
  useEffect(() => {
    setSearchParams(prevParams => {
      return {
        ...prevParams,
        fullscreen: true
      }
  }
  
  return (
    // your component
  )
}
```

**Comment by vandrei977** [comment]
i actually spent the time yesterday and got it to work. 

You can just install the app-bridge from npm and use the dispatch method to enter/exit fullscreen. 
You can have 2 instances of appbridge with different versions. V4( script that remix inserts ) and v3 which you can add from npm. 

At least to move forward with development this would help. Until the new V4 can provide atleast feature parity.

**Comment by lmtNoLimit** [comment]
Hi @lizkenyon 

I believe that Shopify should still offer Fullscreen mode. As a Page Builder, we require these features. It appears to be similar to the Shopify Admin's theme customizer, which provides our customers with the same experience.

**Comment by bakura10** [comment]
The lack of Fullscreen mode is indeed super weird. How can you create editor style page? The new Modal component does not even allow to have a custom bar with icons. Apps that have visual customizations will almost always try to replicate something like this:

<img width="1710" alt="image" src="https://github.com/Shopify/shopify-app-template-remix/assets/1198915/05b97398-e756-400f-bc06-5c3292e155b6">

But this is currently completely impossible.

**Comment by lizkenyon** [comment]
Hi folks 👋 

If you create a ticket in the [App Bridge repo](https://github.com/Shopify/shopify-app-bridge/issues), I can flag your concerns to the App Bridge team. The App Bridge team would be the folks that would be looking into this for you. :) 

The App Bridge team is also active in the App Bridge channel of the Partner Slack community, and there is currently [discussion of this topic going on that you could contribute to](https://shopifypartners.slack.com/archives/CKK8FHFDF/p1708986972980279).

Sorry to send you to another location, but myself and my team don't work on App Bridge and I want you to get your concerns to the most relevant place.

**Comment by ngotungglobosoftware** [comment]
> The lack of Fullscreen mode is indeed super weird. How can you create editor style page? The new Modal component does not even allow to have a custom bar with icons. Apps that have visual customizations will almost always try to replicate something like this:
> 
> <img alt="image" width="1710" src="https://private-user-images.githubusercontent.com/1198915/309135631-05b97398-e756-400f-bc06-5c3292e155b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDE1MjUsIm5iZiI6MTcwOTU0MTIyNSwicGF0aCI6Ii8xMTk4OTE1LzMwOTEzNTYzMS0wNWI5NzM5OC1lNzU2LTQwMGYtYmMwNi01YzMyOTJlMTU1YjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMDgzMzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDJiNTM5MWM2YTBmNmIwOTMyMzI4YWJmYmRmODg2ZGM5OWYyYTYzYWZkODMzNmIyMzA5MmYzMGU1YTYzZTQ1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wSYqJ38tADCzjOSPk2gYhbU_05oLCB1DBMESZPjMv_M">
> But this is currently completely impossible.
> 
> @lizkenyon please re-open this issue, as there is currently no way to achieve that, this is a huge regression over old App Bridge ; the max modal is definitely not an alternative here.

i am also facing the same problem, and it even fails to load css and render html content inside new modal ui, expecting response. :(
