### ISSUE TITLE
authenticate.public.appProxy returning undefined values

### ISSUE THREAD

**Issue by nboliver-ventureweb** [Shopify/shopify-app-template-remix#430]
# Issue summary

I created a route (`/app/routes/proxy-test._index.jsx`) that I would like to act as a proxy page on the front end of a store. The route only has the contents of the example: 
```
import {authenticate} from "~/shopify.server"
export async function loader({ request }) {
  const {liquid} = authenticate.public.appProxy(request);

  return liquid("Hello {{shop.name}}")
}
```
(https://shopify.dev/docs/api/shopify-app-remix/v1/authenticate/public/app-proxy#example-liquid)

When I navigate to `/tools/app-name/proxy-test` on the front end, I get an error: 
> There was an error in the third-party application.

Looking at the console, I can see that the error is happening because `liquid` is undefined. `admin` and `session` are also undefined. I want to set up a proxy page that will interact with an external API and also display data from the admin API. How can What am I missing?

- `@shopify/shopify-app-remix` version: 2.1.0
- Node version: 18.16.0
- Operating system: Mac OS

## Expected behavior

`liquid` should be defined and the page should render with the returned liquid

## Actual behavior

`liquid` is undefined

## Steps to reproduce the problem

1. Add app proxy config in app setup page
2. Create route in remix app with contents of https://shopify.dev/docs/api/shopify-app-remix/v1/authenticate/public/app-proxy#example-liquid
3.  Navigate to route
4. Error

**Comment by nboliver-ventureweb** [comment]
After a few hours of uninstalling / reinstalling / scouring old issues for a solution, I realized there is a bug in the documentation page. 
The `await` operator is missing. It should be: `const {liquid} = await authenticate.public.appProxy(request);`
There is also a small bug in the storefront example - it should be `storefront` not `admin`.
@paulomarg Would be great to get those docs updated to save others from the same troubles!

**Comment by paulomarg** [comment]
Thanks for pointing this out, we'll fix both of those examples!

**Comment by paulomarg** [comment]
Thanks for calling that out, I'll make sure to update the docs website!

**Comment by joeainsworth** [comment]
When trying to follow this [example](https://shopify.dev/docs/api/shopify-app-remix/v2/authenticate/public/app-proxy#example-admin) I am getting the following error:
`TypeError: Cannot read properties of 
undefined (reading 'graphql')`

@paulomarg is it possible the documentation on this example is incorrect as well?

My code:
```
import { json } from "@remix-run/node";
import { authenticate } from "../shopify.server";

export async function loader({ request }) {
  const { admin } = await authenticate.public.appProxy(request);

  const response = await admin.graphql(
    `#graphql
    query getProductVariants($variantIds: [ID!]!) {
      nodes(ids: $variantIds) {
        ... on ProductVariant {
          id
          title
          price
          sku
        }
      }
    }`,
    { variables: { variantIds: ["gid://shopify/ProductVariant/20026765934703", "gid://shopify/ProductVariant/20026765738095"] } }
  );

  const variantData = await response.json();

  return json(variantData)
}
```

**Comment by densekernel** [comment]
I am running `npm run dev` locally

If I visit a public page of the Shopify site directly, e.g., `https://my-dev-store.myshopify.com/pages/app-page`

`const { session, admin } = await authenticate.public.appProxy(request);`

Both `session` and `admin` are undefined...

If I then `› Press p │ preview in your browser`, I am redirected to the root of my app `https://admin.shopify.com/store/my-dev-store/apps/my-dev-app/app`

Now if I return to the original page (albeit in a different browser tab or incognito) `https://my-dev-store.myshopify.com/pages/app-page`

The request is successfully authenticated...

I'm unsure why I need to visit the admin page first to create the session - does this mean this is not suitable for a public page?
