### ISSUE TITLE
How to handle a free tier with the billing API?

### ISSUE THREAD

**Issue by felixmpaulus** [Shopify/shopify-app-template-remix#431]
I am implementing billing into my Remix app. How do I handle free plans with the billing api?
The api seems to only be able to check against paid plans OR throw an error.

```
export const loader: LoaderFunction = async ({
  request,
}: LoaderFunctionArgs) => {
  const { admin, billing, session } = await authenticate.admin(request);
  const { shop } = session;
  const billing = await billing.require({
    plans: getPlanNames(),
    isTest: true,
    onFailure: (error) =>
      changeToFreePlan(shop).then((result) => {
        console.log(result);
        return new Response(JSON.stringify(result));
      }),
  });
return
};
```

with (I want to mark the merchants database entry with their plan)
```
function changeToFreePlan(shop: string) {
  console.log("changeToFreePlan", shop);
  const merchantRef = firestoreAdmin.collection("merchants").doc(shop);
  return merchantRef
    .set({ planName: "free" }, { merge: true })
    .then(() => ({ status: "success", message: "Plan changed to free" }))
    .catch((error) => ({
      status: "error",
      message: `Error: ${error.message}`,
    }));
}
```

This always logs the following to the console:
```
17:33:07 │ remix │ ErrorResponseImpl {
17:33:07 │ remix │   status: 200,
17:33:07 │ remix │   statusText: '',
17:33:07 │ remix │   internal: false,
17:33:07 │ remix │   data: '{"status":"success","message":"Plan changed to free"}'
17:33:07 │ remix │ }
```

and it displays a huge 200 in my Shopify admin in place of the app.

I have been looking for examples or help everywhere without success. I would appreciate any guidance/input on this.

Thank you.

**Comment by paulomarg** [comment]
Ok, I think I just got this! I think that's a valid use case that we should cover as well - right now this package isn't properly covering the case where we have a free plan alongside paid ones.

I don't know exactly what this will look like, but I think it'll probably something along the lines of a `billing.check` function that takes in the same params except `onFailure`, and returns the flow to the app with an empty response.

Does that sound like it would cover your use case?

**Comment by lizkenyon** [comment]
Hi there 👋 

In the next release of the library will expose the `check` function in the billing API. This will allow you to determine the active plans, without requiring an active plan. PR is [here](https://github.com/Shopify/shopify-api-js/pull/1203)
