### ISSUE TITLE
Remix Template: Implement webhook handler

### ISSUE THREAD

**Issue by byrichardpowell** [Shopify/shopify-app-template-remix#44]
- [ ] `/routes/webhook.tsx` should include a switch statement to handle important webhook topics:
  - `CUSTOMERS_DATA_REQUEST`
  - `CUSTOMERS_REDACT`
  - `SHOP_REDACT`
  - `app/uninstalled`
- [ ] `shopify/app.server.ts` should include webhook config for any topics it needs to from the above:

**Comment by marktiddy** [comment]
@byrichardpowell I'm looking at the latest version of webhooks.tsx which does have these included in the switch statement...is there an example of the response they should be sending back? There doesn't seem to be any documentation about this available with relation to the Remix template. Thank you
