### ISSUE TITLE
How to integrate custom server file with dev server

### ISSUE THREAD

**Issue by amoser67** [Shopify/shopify-app-template-remix#440]
# Issue summary

Could we get some documentation or a brief explanation of how to integrate a custom server.js file, specifically when using the dev server?

In this Remix video: https://www.youtube.com/watch?v=6jTL8GGbIuc, they describe the process for using a custom server.js file when using remix dev. Their solution is to have the following npm script: `dev: remix dev -c 'node server.js'`, however we can't apply that method directly here, since the npm script `dev: shopify app dev` initiates the dev server.

Appending the -c flag to the Shopify npm script doesn't work, nor does changing the shopify.web.toml dev command to `npm exec -- remix dev -c 'node ./server.js'`. The only solution I was able to find was to modify the "dev" case statement at the bottom of /node_modules/@remix-run/dev/dist/cli/run.js from :

```
await commands.dev(input[1], flags)
```
to
``` 
await commands.dev(input[1], {
    _: ["dev"],
    command: "node ./server.js",
    interactive: false
});
```

This is obviously not ideal, but I wasn't able to figure out any other way to pass in the custom server. Any help for devising a better solution would be much appreciated.

Relevant Software Versions:
- `@shopify/shopify-app-remix` version: 2.1.0
- `@shopify/shopify-app` version 3.51.2
- `@remix-run/*` version 2.3.1
- Node version: 18+
- Operating system: Ubuntu 20.04

**Comment by paulomarg** [comment]
Sorry, I forgot to say - you would create the new `dev:server` script, and then update `shopify.web.toml` to call that instead of calling the remix command directly.

So

`package.json`:
```json
"scripts": {
  "dev:server": "remix dev -c 'node server.js'"
}
```

`shopify.web.toml`:
```toml
[commands]
dev = "npm run dev:server"
```

That way, when you call `npm run dev`, the CLI will set up the environment, app URL, etc., and then execute `dev:server` instead of executing the remix server directly.

That should hopefully enable you to run your custom server through the CLI.

**Comment by paulomarg** [comment]
Since we won't be able to fix this issue directly from this template, I'm going to close it, but I'm glad the workaround solved it for you!
