### ISSUE TITLE
How to allow getting protected customer data for development

### ISSUE THREAD

**Issue by MoSattler** [Shopify/shopify-app-template-remix#443]
Hi! 

I am currently playing around with this template in development. 
I would like to fetch some orders from my Dev store with this, but I get this error:
>  errors: '[API] This app is not approved to access REST endpoints with protected customer data. See https://partners.shopify.com/2898431/apps/74212573185/customer_data for more 
details.'

What do I have to configure to be able to query orders in development?

The link tells me
> If you’re installing on a development store, select your data use in step 1 to access protected customer data.

But what is "step 1"?

**Comment by alwinantony29** [comment]
how please explain how pleeeeeeeaaaseeee @MoSattler
