### ISSUE TITLE
Running graphql on Shopify Flow action

### ISSUE THREAD

**Issue by maneko00** [Shopify/shopify-app-template-remix#448]
# Issue summary

Has anyone tried to run a Graphql query on Shopify Flow action?

Below is from action.jsx code:
```jsx
export const action = async ({request}) => {
  const { admin } = await authenticate.admin(request);
  const body = await request.json();
  return json({body});
}
```
I got status 410 error.

I need to validate a request, but I don't know how to do that!
https://shopify.dev/docs/apps/flow/actions/create-an-action#verifying-requests

**Comment by matteodepalo** [comment]
Hi @maneko00, may I recommend to ask this question in our [developer forum](https://community.shopify.com/c/shopify-cli-and-tools/bd-p/tools)? If, after finding out how to validate a request, you're still encountering issues, feel free to open a new issue here in this repo.
