### ISSUE TITLE
defer: This Suspense boundary received an update before it finished hydrating

### ISSUE THREAD

**Issue by scraper095** [Shopify/shopify-app-template-remix#449]
# Issue summary

- `@shopify/shopify-app-*` package and version: 2.0.2
- Node version: latest
- Operating system: mac

## Expected behavior
Lazy loading without errors in the console

## Actual behavior
Data loads, but console throws the error

## Steps to reproduce the problem
Using shopify cli remix template project, and ngrok as tunneling service inside the embedded app interface,
This is the code that reproduces the problem:
```
import { defer } from "@remix-run/node";
import { Await, useAsyncValue, useLoaderData } from "@remix-run/react";
import { Suspense } from "react";

const sleep = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve()
    }, 1000);
  });
}

async function someFn() {
  await sleep();
  return "test";
}

export const loader = async () => {
  const resp = someFn();
  return defer({
    someText: resp
  })
};

const MyComponent = () => {
  const someText = useAsyncValue();
  return <div>{someText}</div>;
}

export default function AdditionalPage() {
  const {someText} = useLoaderData();

  return (
    <div>
      <Suspense fallback="Loading...">
        <Await resolve={someText}>
          <MyComponent />
        </Await>
      </Suspense>
    </div>
  );
}

```

**Comment by matteodepalo** [comment]
Hi @scraper095, may I ask which kind of error you're seeing in the console?

**Comment by scraper095** [comment]
> > Hi @scraper095, may I ask which kind of error you're seeing in the console?
> 
> Uncaught Error: This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition. at updateDehydratedSuspenseComponent (react-dom.development.js:20702:48) at updateSuspenseComponent (react-dom.development.js:20362:16) at beginWork (react-dom.development.js:21624:14) at beginWork$1 (react-dom.development.js:27426:14) at performUnitOfWork (react-dom.development.js:26557:12) at workLoopSync (react-dom.development.js:26466:5) at renderRootSync (react-dom.development.js:26434:7) at performConcurrentWorkOnRoot (react-dom.development.js:25738:74) at workLoop (scheduler.development.js:266:34) at flushWork (scheduler.development.js:239:14)

I forgot to mention, with the intention of having startTransition and trying to fix the error I added entry.client.jsx to no avail:
[import { RemixBrowser } from "@remix-run/react";
import { startTransition, StrictMode } from "react";
import { hydrateRoot } from "react-dom/client";

startTransition(() => {
  hydrateRoot(
    document,
    <StrictMode>
      <RemixBrowser />
    </StrictMode>
  );
});](url)

**Comment by matteodepalo** [comment]
This could be related to [this other issue](https://github.com/Shopify/shopify-app-template-remix/issues/456). Could you try to use the canary version of react? `18.3.0-canary-546178f91-20231005`.

**Comment by scraper095** [comment]
> This could be related to [this other issue](https://github.com/Shopify/shopify-app-template-remix/issues/456). Could you try to use the canary version of react? `18.3.0-canary-546178f91-20231005`.

I tried to install it but now the app doesn't work anymore.
```
  ERROR  Cannot read properties of null (reading 'useContext')

 node_modules/@shopify/app/node_modules/react/cjs/react.development.js:1618:21

 1615:     }
 1616:   }
 1617:
 1618:   return dispatcher.useContext(Context);
 1619: }
 1620: function useState(initialState) {
 1621:   var dispatcher = resolveDispatcher();

 - useContext (node_modules/@shopify/app/node_modules/react/cjs/react.development.js:1618:21)
 - useStdin (node_modules/@shopify/app/node_modules/ink/build/hooks/use-stdin.js:6:24)
 - Dev (node_modules/@shopify/app/dist/cli/services/dev/ui/components/Dev.js:13:53)
 - renderWithHooks (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:7478:18)
 - mountIndeterminateComponent (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:11247:13)
 - beginWork (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:12760:16)
 - beginWork$1 (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:19569:14)
 - performUnitOfWork (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:18703:12)
 - workLoopSync (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:18609:5)
 - renderRootSync (node_modules/@shopify/cli-kit/node_modules/react-reconciler/cjs/react-reconciler.development.js:18577:7)
```

**Comment by alexanderhupfer** [comment]
@matteodepalo I found that the error only occurs inside the iFrame as described here: https://github.com/Shopify/shopify-app-template-remix/issues/694

**Comment by lizkenyon** [comment]
Closing this issue. We are working on larger initiatives that should solve this.
