### ISSUE TITLE
Navigating or submitting with reloadDocument redirects me to auth url

### ISSUE THREAD

**Issue by StefanoDiLegami** [Shopify/shopify-app-template-remix#454]
# Issue summary

I am trying to accomplish a file download with a remix Link and reloadDocument as described in the Remix docs here: https://remix.run/docs/en/main/guides/resource-routes

This is the route to download file.

_app.something.file.tsx_

```
import { authenticate } from "~/shopify.server";

export async function loader({ request }) {
  await authenticate.admin(request);

  const file = functionThatDownloadsFile();

  return new Response(file, {
    status: 200,
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="filename.pdf"`,
    },
  });
}
```

This is inside a different route where I list the files I want to download
_app.something._index.tsx_
```
import { Link } from "@remix-run/react";
<Link to="file" reloadDocument>Download file</Link>
```

- `@shopify/shopify-app-remix` version: 2.2.0
- Node version: v18.15.0
- Operating system: MacOS

## Expected behavior

It should properly run: ` await authenticate.admin(request);` and then continue to process code of the loader and then download file.

## Actual behavior

Probably the "authenticate.admin" method is not able to handle the reloadDocument attribute.

This piece of code redirects me to auth route:  

` await authenticate.admin(request);`

## Steps to reproduce the problem

1. Create a file with a loader and add first line `const { admin } = await authenticate.admin(request);`
2. Use a `<Link to="file" reloadDocument>Download file</Link>` imported from "@remix-run/react" 
3. See that you get redirected to auth url

**Comment by matteodepalo** [comment]
Pinging @paulomarg

**Comment by fabregas4** [comment]
Did anyone find a solution to this?

Everything I'm trying to be able to download a file via a link or button or form submission isn't working. I either get a blank route or the auth screen. If I load the download route directly via the URL bar, then the file downloads as expected as an attachment. Have tried Polaris <Link> component, <a> tag, form submission, useFetcher (load, submit and Form), with no luck.

This is from the loader of my download route. I've also tried it as an action.

```
	// Use createReadableStreamFromReadable to make it compatible with Response
	const file = createReadableStreamFromReadable(csvFileStream);

	return new Response(file, {
		headers: {
			'Content-Disposition': 'attachment; filename="rental_export.csv"',
			'Content-Type': 'text/csv', // Correct content type for CSV
		},
	});
```

**Comment by StefanoDiLegami** [comment]
@fabregas4 I did the download client-side via JavaScript and in the loader I returned the file as buffer as you did: https://stackoverflow.com/questions/3749231/download-file-using-javascript-jquery

**Comment by fabregas4** [comment]
@StefanoDiLegami Thanks for putting me in the right direction.

From there I ended up creating this hook. Probably not the best code but it's working well and I'm sure will be useful for others. Can't believe we need such a hack just for downloadable files in this environment.

```
import { useFetcher } from '@remix-run/react';
import { useEffect, useRef, useState } from 'react';

export function useDownloadFile() {
	const fetcher = useFetcher<string>(); // Explicitly type fetcher.data as a string
	const [isLoading, setIsLoading] = useState(false);
	const fileNameRef = useRef<string>('download.csv');

	const downloadFile = async (url: string, fileName: string = 'export.csv') => {
		setIsLoading(true);
		fileNameRef.current = fileName;
		try {
			fetcher.load(url);
		} catch (error) {
			console.error('Error starting the export:', error);
			alert('Sorry, an error occurred while starting the export process.');
		}
	};

	useEffect(() => {
		if (fetcher.state === 'idle' && fetcher.data) {
			try {
				const blob = new Blob([fetcher.data], { type: 'text/csv' });
				const url = window.URL.createObjectURL(blob);

				const a = document.createElement('a');
				a.style.display = 'none';
				a.href = url;
				a.download = fileNameRef.current;
				document.body.appendChild(a);
				a.click();

				window.URL.revokeObjectURL(url); // Clean up
			} catch (error) {
				console.error('Error processing the export data:', error);
				alert('Sorry, an error occurred while creating your export file.');
			} finally {
				setIsLoading(false);
			}
		}
	}, [fetcher.state, fetcher.data]);

	return { downloadFile, isLoading };
}
```
