### ISSUE TITLE
Update to React 18.3 - to Fix Defer

### ISSUE THREAD

**Issue by owlyowl** [Shopify/shopify-app-template-remix#456]
# Issue summary

We were hoping we could update to React 18.3 to resolve these issues raised as we're using `defer`

Please see these issues raised:
https://github.com/remix-run/remix/issues/5165
https://github.com/remix-run/remix/issues/4822

**Comment by owlyowl** [comment]
Thanks very much for the reply.

It's concerning that `defer` is quite broken without using 18.3 canary. I
was hoping they'd release soon given 18.2 came out in June.

**Comment by matteodepalo** [comment]
Closing this as a duplicate of https://github.com/Shopify/shopify-app-template-remix/issues/449
