### ISSUE TITLE
How to get an offline access token

### ISSUE THREAD

**Issue by MoSattler** [Shopify/shopify-app-template-remix#457]
So, I think this is probably a stupid question, and I am missing something obvious, but how do I get the offline access token? 

I would like to store it and make requests to shops in a scheduled manner, when the user is not currently logged in or using the embedded app.

I know I somehow have to intercept it from the OAUTH flow (see [this](https://shopify.dev/docs/apps/auth/oauth/getting-started#step-7-make-authenticated-requests)), but as far as I can see, the code does not have OAUTH handling routes.

**Comment by lizkenyon** [comment]
Hi there 👋 

Are you using the Shopify Remix App template? If you are then you don't need to manually handle OAuth, that has been implemented already!

By default your app will be creating and saving an offline token during OAuth. If have specified to use online tokens in the [ShopifyApp config object](https://shopify.dev/docs/api/shopify-app-remix/v2/entrypoints/shopifyapp#shopifyapp-propertydetail-appconfig), both online and offline tokens will be created and saved.

Then you will use the [unauthenticated.admin](https://shopify.dev/docs/api/shopify-app-remix/v2/unauthenticated/unauthenticated-admin#example-rest) methods to make requests to Shopify.

**Comment by lizkenyon** [comment]
You are right that isn't very clear. That will be the myshopify domain for the store.

**Comment by lizkenyon** [comment]
Hi @blanklob 

Could you create a new Github issue for your question and provide a bit more context! (Are you referring to Shopify webhooks, or another services webhooks?) (Sorry we are just trying to improve our tracking of answering individual requests! Thanks so much!)
