### ISSUE TITLE
Can't redirect to external url with admin redirect method

### ISSUE THREAD

**Issue by GinoUdoc** [Shopify/shopify-app-template-remix#458]
# Issue summary

Our application requirements require us to redirect the user to an external webpage. But instead of being redirected to the proper page it seems to reload the page and append "?index=" to the url.

```ts
export const action = async ({ request }: ActionFunctionArgs) => {
  const { redirect } = await authenticate.admin(request);


  const formData = await request.formData()
  const { connected } = Object.fromEntries(formData)

  console.log(`connected ${connected}`)

  if (connected === "true") {
    console.log("disconnecting...")

    return redirect(request.url)
  }
  console.log("connecting...")
  
  // should redirect application to https://example.com, essentially exiting the embedded application and replacing the full window.
  return redirect(`https://example.com`, { target: "_parent" })
}
```

- `@shopify/shopify-app-remix` version: 2.1.0
- Node version: 20.10.0
- Operating system: Ubuntu LTS 22.4

```
// Paste any relevant logs here
```

## Expected behavior

According to the documentation `const { redirect } = await authenticate.admin(request);` in order to redirect to an external url the developer should supply the target to the redirect method, this could either be _parent,  _top or _self. 

The expected behavior of supplying _top or _parent is that the full page should be redirected. In case of the above example code the full page should have been redirected to "https://example.com".

(snippet from @shopify/shopify-app-remix-build/ts/server/authenticate/admin/types.d.ts)
```ts

    /**
     * A function that redirects the user to a new page, ensuring that the appropriate parameters are set for embedded
     * apps.
     *
     * Returned only if `isEmbeddedApp` is `true`.
     *
     * @example
     * <caption>Redirecting to an app route.</caption>
     * <description>Use the `redirect` helper to safely redirect between pages.</description>
     * ```ts
     * // /app/routes/admin/my-route.ts
     * import { LoaderFunctionArgs, json } from "@remix-run/node";
     * import { authenticate } from "../shopify.server";
     *
     * export const loader = async ({ request }: LoaderFunctionArgs) => {
     *   const { session, redirect } = await authenticate.admin(request);
     *   return redirect("/");
     * };
     * ```
     *
     * @example
     * <caption>Redirecting outside of Shopify admin.</caption>
     * <description>Pass in a `target` option of `_top` or `_parent` to go to an external URL.</description>
     * ```ts
     * // /app/routes/admin/my-route.ts
     * import { LoaderFunctionArgs, json } from "@remix-run/node";
     * import { authenticate } from "../shopify.server";
     *
     * export const loader = async ({ request }: LoaderFunctionArgs) => {
     *   const { session, redirect } = await authenticate.admin(request);
     *   return redirect("/", { target: '_parent' });
     * };
     * ```
     */
    redirect: RedirectFunction;

```

## Actual behavior

The app reloads the current window, but I did notice that "?index=" has been appended to the URL.

Whilst observing the network tab in Edge I saw the following response. Perhaps that might be of any value.

![image](https://github.com/Shopify/shopify-app-template-remix/assets/99013824/321cfd54-a2a5-43de-8205-d99d3e752702)

## Steps to reproduce the problem

1. Create an action with the following return statement `return redirect("https://example.com", { target: "_parent" })`
2. Observe the result.

**Comment by RuentDev** [comment]
Same Issue, I tried to do the same thing that documentation said and it still not working

**Comment by ardeearam** [comment]
Hello there,

I experienced an issue when I placed the redirect inside a `try-catch` block.

This doesn't work:
```

export const action = async ({ request }: ActionFunctionArgs) => {
  try {

    const { admin, session, redirect } = await authenticate.admin(request);
    return redirect("https://klaudsol.com", { target: "_top" });

  }  catch (error) {
    //process error
    return null;
  } 

}
    
```

Removing it from the try-catch blocks will make the code work:

```

export const action = async ({ request }: ActionFunctionArgs) => {

    const { admin, session, redirect } = await authenticate.admin(request);
    return redirect("https://klaudsol.com", { target: "_top" });

}
    
```

**Comment by chemiadel** [comment]
> Putting the `redirect` inside `finally` works as well, if you do not want to compromise your exception-handling capabilities:
> 
> ```
> export const action = async ({ request }: ActionFunctionArgs) => {
> 
>   let redirect;
> 
>   try {
> 
>     const adminContext = await authenticate.admin(request);
>     redirect = adminContext.redirect;
> 
>   }  catch (error) {
>     //process error
>   } finally {
>     if(redirect)  return redirect("https://klaudsol.com", { target: "_top" });
>   }
> 
> }
> ```

That worked!! thanks. but I hope they fix it
