### ISSUE TITLE
Login - docs/purpose?

### ISSUE THREAD

**Issue by alexblack** [Shopify/shopify-app-template-remix#459]
I see the template comes with a login route: https://github.com/Shopify/shopify-app-template-remix/blob/main/app/routes/auth.login/route.tsx

Are there some docs that explain when and why this is needed?  I thought normally users don't need to login, and if they did I imagined they'd login at shopify then do oauth with our app... no?

Thanks!

Alex

**Comment by alexblack** [comment]
hi @lizkenyon how am I as a developer meant to figure that out? Are there docs? or comments?  Seems like I would want to remove that code from our app then, no?

**Comment by lizkenyon** [comment]
Thank you for your feedback! I agree we will look into adding additional documentation to clarify that.

Getting real merchants to install your app via them entering their myshopify domain is against the [terms of service.](https://shopify.dev/docs/apps/store/requirements#c-setup-and-merchant-workflows:~:text=Apps%20must%20be%20installed%20and%20initiated%20only%20on%20Shopify%20services.%20Your%20app%20must%20not%20request%20the%20manual%20entry%20of%20a%20myshopify.com%20URL%20or%20a%20shop%27s%20domain%20during%20the%20installation%20or%20configuration%20flow.)

**Comment by alexblack** [comment]
> Thank you for your feedback! I agree we will look into adding additional documentation to clarify that.

Great.
> 
> Getting real merchants to install your app via them entering their myshopify domain is against the [terms of service.](https://shopify.dev/docs/apps/store/requirements#c-setup-and-merchant-workflows:~:text=Apps%20must%20be%20installed%20and%20initiated%20only%20on%20Shopify%20services.%20Your%20app%20must%20not%20request%20the%20manual%20entry%20of%20a%20myshopify.com%20URL%20or%20a%20shop%27s%20domain%20during%20the%20installation%20or%20configuration%20flow.)

Unless I'm misunderstanding it looks like this route enables real merchants to install the app view their myshopify domain, no?

I'd like to delete the route, should I just delete the entire `auth.login` folder?

**Comment by lizkenyon** [comment]
Yes, you can remove that if you do not want to use it during your testing and development.

To learn about what *is* required for OAuth, you can review the documentation [here.](https://shopify.dev/docs/api/shopify-app-remix#auth-route)

**Comment by alexblack** [comment]
I've removed those now.  I am hitting an issue that seems related, if you browse to our app at https://storereports.syncwith.com/, then the browser is redirected to https://storereports.syncwith.com/auth/login and complains `ERR_TOO_MANY_REDIRECTS`

I searched our code, and I don't see any reference to `/auth/login`... is this Shopify's code that redirects to that path? If so, should I put something at that path? Or can I handle this some other way?

**Comment by pedropalau** [comment]
Why this is closed? I have the same issue with the too many redirects error.

**Comment by lizkenyon** [comment]
Hi @pedropalau 
This is the[ issue ](https://github.com/Shopify/shopify-app-template-remix/issues/466)we will be updating. Thanks!

**Comment by pedropalau** [comment]
Thank you @lizkenyon
