### ISSUE TITLE
Webhook ORDERS_CREATED authenticate error 401

### ISSUE THREAD

**Issue by snipert1549** [Shopify/shopify-app-template-remix#462]
Hi team! I am developing custom app in dev store. I have created webhook ORDERS_CREATED. It's fired but authentication always returns me 401 error with description invalid hmac. 
Steps to reproduce:
1. I have registered webhook in shopify admin .
Go to admin panel -> Settings-> Notifications->Webhooks-> Press bottun Create webhook. 
**Also I tried another way. Registering  webhook via GraphQL Admin app. Run mutation webhookSubscriptionCreate with data on screen**
![Screenshot 2023-12-20 at 18 53 29](https://github.com/Shopify/shopify-app-template-remix/assets/154383710/d5bfb354-c0f0-4f27-9a98-0daccc799b84)
2.  Then I configured webhook according to this doc
https://shopify.dev/docs/api/shopify-app-remix/v1/guide-webhooks
Here my code:
shopify.server.js file

```
const shopify = shopifyApp({
  apiKey: process.env.SHOPIFY_API_KEY,
  apiSecretKey: process.env.SHOPIFY_API_SECRET || "",
  apiVersion: LATEST_API_VERSION,
  scopes: process.env.SCOPES?.split(","),
  appUrl: process.env.SHOPIFY_APP_URL || "",
  authPathPrefix: "/auth",
  sessionStorage: new PrismaSessionStorage(prisma),
  distribution: AppDistribution.AppStore,
  restResources,
  webhooks: {
    APP_UNINSTALLED: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks",
    },
  },
  hooks: {
    afterAuth: async ({ session }) => {
      shopify.registerWebhooks({ session });
    },
  },
  future: {
    v3_webhookAdminContext: true,
    v3_authenticatePublic: true,
  },
  ...(process.env.SHOP_CUSTOM_DOMAIN
    ? { customShopDomains: [process.env.SHOP_CUSTOM_DOMAIN] }
    : {}),
});
```
And in webhooks.jsx file I am trying to authenticate with:
`const { topic, shop, session, payload } = await authenticate.webhook(request);`
3.  When I go to my store and place order the ORDERS_CREATED event fires, the webhook hits my app's endpoint, and the console displays:
`POST /webhooks 401`
After small researching I have got a message 
`{valid: false, reason: invalid_hmac}`
I tried to trigger event by different possible ways:

> - place order from storefront;
> - use cli command `npm run shopify webhook trigger`
> - press button 'Send test notification' from admin pannel.

In all cases i had the same result autentification: 401 error with message invalid_hmac. Could you please clarify what I am doing wrong ?
I am using
Node.js v18.16.0
"@shopify/shopify-app-remix": "^2.1.0",

**Comment by lizkenyon** [comment]
Hi there 👋 

If you are using the Shopify App remix template you will want to do so in the [app template](https://shopify.dev/docs/api/shopify-app-remix/v2/guide-webhooks) itself.

You will configure the webhook topics you want to subscribe to in the `/app/shopify.server.ts`.

When you create webhook subscriptions in the Shopify Admin they are signed with the secret key shown there. Your app does not have access to this secret key so it cannot authenticate these webhooks.

Similarly if you create a webhook subscription with the [Graphiql Admin App](https://shopify.dev/docs/apps/tools/graphiql-admin-api) that you installed on your store the webhook subscriptions would be signed with the Graphiql App's api key.

From the `shopify.server.js` file you shared it doesn't look like you have registered a subscription to `ORDERS_CREATED`, just the `APP_UNINSTALLED` So could the the webhook you are receiving would be one of the previously created webhook subscriptions via one of the other methods? Then it would be expected to get a 401.

I would recommend deleting your previously created webhook subscriptions. And adding an `ORDERS_CREATED` topic to your `shopify.server.ts` file.

```
const shopify = shopifyApp({
  apiKey: process.env.SHOPIFY_API_KEY,
  apiSecretKey: process.env.SHOPIFY_API_SECRET || "",
  apiVersion: LATEST_API_VERSION,
  scopes: process.env.SCOPES?.split(","),
  appUrl: process.env.SHOPIFY_APP_URL || "",
  authPathPrefix: "/auth",
  sessionStorage: new PrismaSessionStorage(prisma),
  distribution: AppDistribution.AppStore,
  restResources,
  webhooks: {
    APP_UNINSTALLED: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks",
    },
    ORDERS_CREATED: {
       deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks",
     }
  },
  hooks: {
    afterAuth: async ({ session }) => {
      shopify.registerWebhooks({ session });
    },
  },
  future: {
    v3_webhookAdminContext: true,
    v3_authenticatePublic: true,
  },
  ...(process.env.SHOP_CUSTOM_DOMAIN
    ? { customShopDomains: [process.env.SHOP_CUSTOM_DOMAIN] }
    : {}),
});
```

**Comment by snipert1549** [comment]
@lizkenyon  thank you for your response! It helps.

**Comment by charlesr1971** [comment]
Hi Liz

Thank you so much for this information.

So far, I have written this:

```
  const { admin, session } = await authenticate.admin(request);
  const webhook = new admin.rest.resources.Webhook({session: session});
  webhook.address = "https://alien-amazed-lab.ngrok-free.app";
  webhook.topic = "orders/create";
  webhook.format = "json";
  await webhook.save({
    update: true,
  });
```

But, I have no idea where to put it?

**Comment by lizkenyon** [comment]
This code would create a new webhook subscription. 

Is there any reason you want to create a new webhook subscription like this instead of the [documented](https://shopify.dev/docs/api/shopify-app-remix/v2/guide-webhooks#config)way to create webhook subscriptions in the remix template?

**Comment by charlesr1971** [comment]
In `shopify.server.ts`, I have got this:

```
const shopify = shopifyApp({
  apiKey: process.env.SHOPIFY_API_KEY,
  apiSecretKey: process.env.SHOPIFY_API_SECRET || "",
  apiVersion: LATEST_API_VERSION,
  scopes: process.env.SCOPES?.split(","),
  appUrl: process.env.SHOPIFY_APP_URL || "",
  authPathPrefix: "/auth",
  sessionStorage: new PrismaSessionStorage(prisma),
  distribution: AppDistribution.AppStore,
  restResources,
  webhooks: {
    APP_UNINSTALLED: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks",
    },
    ORDERS_CREATE: {
       deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks",
     }
  },
  hooks: {
    afterAuth: async ({ session }) => {
      shopify.registerWebhooks({ session });
    },
  },
  future: {
    v3_webhookAdminContext: true,
    v3_authenticatePublic: true,
  },
  ...(process.env.SHOP_CUSTOM_DOMAIN
    ? { customShopDomains: [process.env.SHOP_CUSTOM_DOMAIN] }
    : {}),
});
```
In `webhooks.jsx`, I have:

```
import { authenticate } from "../shopify.server";
import { json, redirect } from "@remix-run/node";
import db from "../db.server";

export const action = async ({ request }) => {

  const { topic, shop, session, admin, payload } = await authenticate.webhook(request);

  if (!admin) {
    throw new Response();
  }

  switch (topic) {
    case "APP_UNINSTALLED":
      if (session) {
        await db.session.deleteMany({ where: { shop } });
      }
      break;
    case "ORDERS_CREATE":
      if (session) {
        insertOrder(payload);
        return new Response(`Recieved new order for ${shop}`, {status:200});
      }
      break;
      
    case "CUSTOMERS_DATA_REQUEST":
    case "CUSTOMERS_REDACT":
    case "SHOP_REDACT":
    default:
      throw new Response("Unhandled webhook topic", { status: 404 });
  }

  throw new Response();
};

const insertOrder = async (payload) => {

  const orderid = payload.id;
  const customerid = payload.customerid;

  try {
    const order = db.uploadForm1.create({
      // @ts-ignore
      customerid,
      orderid,
    });
  } catch (error) {}
};
```

Now, before you explained that I should not create **Webhooks** in the _Admin GUI_, I have now written this:

```
 const { admin, session } = await authenticate.admin(request);
  const webhook = new admin.rest.resources.Webhook({session: session});
  webhook.address = "https://alien-amazed-lab.ngrok-free.app";
  webhook.topic = "orders/create";
  webhook.format = "json";
  await webhook.save({
    update: true,
  });
```

But have no idea where to put this code? I thought initially that I should add it to `loader` method in **webhooks.jsx**, but I still kept getting a 401.
Do you know where I can put it?

**Comment by charlesr1971** [comment]
OK. I think I am understanding you, now. 
To create a _subscription_, I just need to add the code to `shopify.server.ts`, like:

```
const shopify = shopifyApp({
  apiKey: process.env.SHOPIFY_API_KEY,
  apiSecretKey: process.env.SHOPIFY_API_SECRET || "",
  apiVersion: LATEST_API_VERSION,
  scopes: process.env.SCOPES?.split(","),
  appUrl: process.env.SHOPIFY_APP_URL || "",
  authPathPrefix: "/auth",
  sessionStorage: new PrismaSessionStorage(prisma),
  distribution: AppDistribution.AppStore,
  restResources,
  webhooks: {
    APP_UNINSTALLED: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks",
    },
    ORDERS_CREATE: {
       deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks",
     }
  },
  hooks: {
    afterAuth: async ({ session }) => {
      shopify.registerWebhooks({ session });
    },
  },
  future: {
    v3_webhookAdminContext: true,
    v3_authenticatePublic: true,
  },
  ...(process.env.SHOP_CUSTOM_DOMAIN
    ? { customShopDomains: [process.env.SHOP_CUSTOM_DOMAIN] }
    : {}),
});
```
And then use the `webhooks.jsx` file to process the data inside the webhook payload? As, I am currently doing?
So, why am I getting a 401, every time someone submits an order in the **online store**?

**Comment by charlesr1971** [comment]
Hi Liz

Actually my tunnel remains the same, after a server restart, because I use _ngrok's_ one free **static domain**, so I am not sure why I keep getting a 401?

**Comment by charlesr1971** [comment]
Should I delete the webhooks in the Admin GUI? Maybe, these are interfering?

**Comment by lizkenyon** [comment]
> And then use the webhooks.jsx file to process the data inside the webhook payload? As, I am currently doing?
So, why am I getting a 401, every time someone submits an order in the online store?

You created a webhook subscription via the Admin. This has signed with a different key. You pointed it to your app URL. Shopify sends this webhook event to your App. Your app cannot validate this webhook event. (Because it was signed with the different key, not your apps). So it returns a 401.

You should delete the webhooks you created in the Admin.

**Comment by charlesr1971** [comment]
OK. I have deleted the webhooks in my **Admin GUI**. 
I then submitted a new order in my online store and no webhook is triggered in my Remix App? 
I am not even getting a 401, now.
Just nothing? 
I am looking at the terminal in VSCode, by the way. 
I have added some `console.log` calls in my **webhooks.jsx** file...

**Comment by lizkenyon** [comment]
The first step to debug an issue like this would be to verify your webhook subscriptions. Did I actually subscribe to the topic I wanted? Is my URL correct?

So I would recommend querying the API, you can use the GraphiQL app link in your terminal to do this, to verify your webhook subscriptions.

**Comment by charlesr1971** [comment]
![GraphiQL-1](https://github.com/Shopify/shopify-app-template-remix/assets/827046/f903157a-aa43-4d93-bb1d-4a85e3c7f1be)

**Comment by charlesr1971** [comment]
Do I have to add them anywhere else, to register them? 
I have restarted the server, but the **GraphQL** query only displays the `APP_UNINSTALLED` webhook?

**Comment by lizkenyon** [comment]
The webhooks subscriptions are created in the afterAuth hook.
```
hooks: {
    afterAuth: async ({ session }) => {
      if(debug){
        console.log("shopify.server: shopifyApp: hooks: auth happened");
      }
      shopify.registerWebhooks({ session });
    },
  }
 ```
 
 If you added the additional webhook topic after you installed your application, you may need to reinstall your app.

**Comment by charlesr1971** [comment]
Ah. That could be it. Let me reinstall

**Comment by charlesr1971** [comment]
![shopify app toml](https://github.com/Shopify/shopify-app-template-remix/assets/827046/05db549b-ee64-4ac2-84c8-13c915410303)

**Comment by charlesr1971** [comment]
Hi @nboliver-ventureweb 

Thanks for the info.

Here are the scopes for my re-installed app 

![shopify-partner-app-api-access-1](https://github.com/Shopify/shopify-app-template-remix/assets/827046/1e631ec4-a5e9-41d8-9ff6-9af18cef5595)

I did not use an existing app.

1. I deleted the app first
2. Created a new app with the access scopes
3. Installed the new app
4. Still no webhooks to be seen

**Comment by nboliver-ventureweb** [comment]
> Is there a simple webhook, apart from `APP_UNINSTALLED`, that I could test? Maybe the **orders** webhooks require special permissions or something?

Yeah you could check a product update instead just to rule that out: 

```
webhooks: {
    APP_UNINSTALLED: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: '/webhooks',
    },
    PRODUCTS_CREATE: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: '/webhooks',
    },
    PRODUCTS_UPDATE: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: '/webhooks',
    },
    PRODUCTS_DELETE: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: '/webhooks',
    },
  },
```

Add those hooks, then uninstall the app from your dev store and then run `npm run dev -- --reset`. Pick existing app (the one in your screenshot above) then hit `p` to open your app and re-install it. In shopify.server.js you can also `import { LogSeverity } from '@shopify/shopify-app-remix';` and then in the `shopifyApp` argument object add 

```
....
logger: {
  level: LogSeverity.Debug,
},
```
That will log when hooks are registered.

**Comment by charlesr1971** [comment]
Holy Guacamole, something has happened. 👍 

I added the following:

 ```
webhooks: {
    APP_UNINSTALLED: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks",
    },
    ORDERS_CREATE: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks",
    },
    ORDERS_UPDATE: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks",
    },
    PRODUCTS_CREATE: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: '/webhooks',
    },
    PRODUCTS_UPDATE: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: '/webhooks',
    },
    PRODUCTS_DELETE: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: '/webhooks',
    },
  },
```

And, after a **reset install**, using:

`npm run dev -- --reset`

I get the following:

![shopify-graphql-webhooks-1](https://github.com/Shopify/shopify-app-template-remix/assets/827046/1bc8b2b8-6583-40da-9c72-ef65b0b537b1)

Not sure why it refused to add the other 4 webhooks, but I will take what I can get :)

Thanks for your help.

**Comment by lizkenyon** [comment]
Hey @ratnadeepdey1998 

It looks like you are getting a 404 error not a 401. So because it is different could you create a new issue for this. This will ensure we do not loose track of the issue.
