### ISSUE TITLE
Custom ErrorBoundary

### ISSUE THREAD

**Issue by alexblack** [Shopify/shopify-app-template-remix#465]
Hi, I read the docs here: https://shopify.dev/docs/api/shopify-app-remix#boundaries but its not clear if/how we can render our own error boundary page.

The docs say to do this:

```
export function ErrorBoundary() {
  return boundary.error(useRouteError());
}
```

Can we return our own markup? If so, how do we still call `boundary.error`?

```
export function ErrorBoundary() {
  const error = useRouteError();
  return <div className="error">{error}</div>;
}
```

Also, do we need to call `boundary.error` and `boundary.headers` in every ErrorBoundary? eg in each nested ErrorBoundary?

**Comment by alexblack** [comment]
I'll assume this means you have no intention of updating your docs?

**Comment by mgill404** [comment]
@alexblack did you open a thread in the forum? I'm running into this as well and curious if you found any solution.

**Comment by alexblack** [comment]
@mgill404 I didn't open a discussion I'm afraid.  If you do please let me know!

**Comment by mgill404** [comment]
https://community.shopify.com/c/shopify-cli-and-tools/custom-errorboundary/m-p/2405950#M4198
