### ISSUE TITLE
Infinite redirect to /auth/login

### ISSUE THREAD

**Issue by alexblack** [Shopify/shopify-app-template-remix#466]
I've removed  the dev/test route /auth/login, and I am  now hitting an issue, if you browse to our app at https://storereports.syncwith.com/, then the browser is redirected to https://storereports.syncwith.com/auth/login and complains ERR_TOO_MANY_REDIRECTS

I searched our code, and I don't see any reference to /auth/login... is this Shopify's code that redirects to that path? If so, should I put something at that path? Or can I handle this some other way?

see: https://github.com/Shopify/shopify-app-template-remix/issues/459

**Comment by lizkenyon** [comment]
@alexblack Thanks for flagging this!

I am glad you were able to find a workaround right now. The team will look into this in the new year!
