### ISSUE TITLE
Use template without session storage

### ISSUE THREAD

**Issue by anhdd-kuro** [Shopify/shopify-app-template-remix#470]
# Issue summary

I am in the process of developing an private app that will distribute to `AppDistribution.SingleMerchant` or `AppDistribution.ShopifyAdmin`. I am seeking guidance on how to adapt the Remix.run template for this purpose. Specifically, I'm puzzled by the requirement for sessionStorage.

My understanding is that all I need is an access token and scopes. Why is sessionStorage is required ? It appears to store data such as [isOnline, scope, expires, accessToken, ...], which can also be provided by other options like `useOnlineTokens`, `adminApiAccessToken`, `distribution`, `scopes` and so on.

I'm curious about the rationale behind mandating sessionStorage when other options seem equally capable. If its inclusion is necessary, why do we have alternative options that seemingly serve the same purpose?

## Expected behavior

`sessionStorage` is required only if `adminApiAccessToken` is empty and `distribution` is `AppDistribution.AppStore`

**Comment by lizkenyon** [comment]
Closing as this was resolved with [this PR](https://github.com/Shopify/shopify-app-js/pull/1181)

**Comment by nboliver-ventureweb** [comment]
> Closing as this was resolved with [this PR](https://github.com/Shopify/shopify-app-js/pull/1181)

@lizkenyon @paulomarg This functionality does not seem to be documented anywhere. The docs here: https://shopify.dev/docs/api/shopify-app-remix/v1/entrypoints/shopifyapp#shopifyApp-parameters say sessionStorage is required.

**Comment by nboliver-ventureweb** [comment]
Ah thanks! `v1` docs loaded by default for some reason. 
Making sessionStorage optional for CLI apps with custom distribution would be a great enhancement 😁 
Many of our custom apps do not require any storage and the extra infrastructure setup + cost just to maintain sessionStorage is a current pain point.
