### ISSUE TITLE
Contextual Save Bar does not prevent navigation

### ISSUE THREAD

**Issue by frerepoulet** [Shopify/shopify-app-template-remix#472]
# Issue summary

When you add 'data-save-bar' to a Remix form within a Polaris page component that has a backAction set as a URL navigation, App Bridge shows an alert modal but doesn't prevent navigation. Printed on the console :  "A router only supports one blocker at a time", which is a React Router error.

- `@shopify/shopify-app-remix` version: 2.2.0
- Node version: N/A
- Operating system: Ubuntu 22.04

## Expected behavior

Contextual Save Bar should present an alert and prevent navigation.

## Actual behavior

Contextual Save Bar should present an alert but navigates. :cry:

## Steps to reproduce the problem

1. Add this code as a route Component: 
 ```js
import { Form, Link } from "@remix-run/react";
import { Page } from "@shopify/polaris";

export default function Component() {
  return (
    <Page
      backAction={{
        content: "Home",
        url: "/",
      }}
      title="New Element"
    >
      <Link to="/">Home</Link>
      <Form data-save-bar onSubmit={console.log}>
        <input type="text" />
      </Form>
    </Page>
  );
}
```

2. Input any text in the text field. The contextual save bar should appear.
3. Click on the <Page/> back button.
4. Modal shows up but navigation is not prevented.
5. See error in console: "A router only supports one blocker at a time"
6. BONUS - You can also try with the Remix Link. Navigation is not prevented either.

**Comment by blanklob** [comment]
Did u try using regular form? Instead of polaris form

**Comment by frerepoulet** [comment]
Yes I did and the same thing happens. Also, in the current [README](https://github.com/Shopify/shopify-app-template-remix?tab=readme-ov-file#navigatingredirecting-breaks-an-embedded-app) it is specified:

> Use useSubmit or `<Form/>` from @remix-run/react. Do not use a lowercase `<form/>`

**Comment by Stef733** [comment]
> > Thanks for flagging and providing the steps for reproduction. I was able to reproduce this.
> > The team will take a look.
> 
> Also could you work on the loading state for Contextual save bar

I opened an issue for this as it seems like a fundamental issue #516

**Comment by lizkenyon** [comment]
Hi folks 👋 

Just wanted to update that the App Bridge team is investigating this!

**Comment by DamirAid** [comment]
@lizkenyon Hi! have you any updates for this issue?

**Comment by DatSeppy** [comment]
Hi @henrytao-me,

Thank you for your solutions, but I have a problem for back to previous page by event of browser. I can not catch any event for that. Do you have any solutions for this case ?
![image](https://github.com/Shopify/shopify-app-template-remix/assets/153153622/1bf19d1f-73c8-4c91-bff6-94b637350220)
