### ISSUE TITLE
Just installed Remix template ad get me "TypeError: (0 , Import_isbot.Default) Is Not A Funct"

### ISSUE THREAD

**Issue by devejoe** [Shopify/shopify-app-template-remix#477]
I wasn't getting this error before, but now, I'm getting this "TypeError: (0 , Import_isbot.Default) Is Not A Funct".
All I did was run the freshly installed Remix template using Shopify CLI "npm run @shopify/app@latest" then run "npm run dev".
click the "P" key tp open up in my browser and get this error.
![image](https://github.com/Shopify/shopify-app-template-remix/assets/106771325/6bba59d7-a1f1-43f5-8143-5d52760daeb0)

**Comment by YouCanflyThruMostTheSun** [comment]
This is the fix I used: 

import isbot from "isbot";

to

import { isbot } from "isbot";


and 


const callbackName = isbot(request.headers.get("user-agent"))

to

const callbackName = isbot(request.headers.get("user-agent") || "")

**Comment by devejoe** [comment]
Awesome! This actually works.
I hope this will be fixed in the future even without changing anything from the entry codes.
Thanks a lot.

**Comment by lizkenyon** [comment]
Hi there 👋 
Thank you for reaching out! And thanks for sharing the workaround fix. This issue should be resolved now!

You can clone a new template with the command `npm init @shopify/app@latest`

**Comment by YouCanflyThruMostTheSun** [comment]
Awesome! 

No, thank you for the fix! 


⁣Get BlueMail for Android ​
