### ISSUE TITLE
Installed Remix App Homepage Blank

### ISSUE THREAD

**Issue by MiGorainger** [Shopify/shopify-app-template-remix#480]
Hi guys,
I've been playing with Shopify for many years now and have a very small understanding of coding but I thought there's no better way to learn to develop an app if I just give something a go. I've followed the steps correctly following the Shopify [Create an App ](https://shopify.dev/docs/apps/getting-started/create) walkthrough but once the app installs I am not seeing this page (Image attached), I'm purely seeing a blank white page

I noticed this code in the cmd:

16:59:13 │ graphiql │ GraphiQL server started on port 3457
16:59:16 │ remix    │
16:59:16 │ remix    │  💿  remix dev
16:59:16 │ remix    │
16:59:17 │ remix    │  info  building...
16:59:19 │ remix    │ X [ERROR] Expected "}" but found "EntryContext"
16:59:19 │ remix    │
16:59:19 │ remix    │     app/entry.server.jsx:6:7:
16:59:19 │ remix    │       6 │   type EntryContext,
16:59:19 │ remix    │         │        ~~~~~~~~~~~~
16:59:19 │ remix    │         ╵        }
16:59:19 │ remix    │
16:59:19 │ remix    │
Error forwarding web request: AggregateError
Error forwarding web request: AggregateError
Error forwarding web request: AggregateError
Error forwarding web request: AggregateError
Error forwarding web request: AggregateError

I've looked through a few other posts on here about what could possibly be the issue but nothing seems to be helping unfortunately. Any tips?

The app is installed in my test development store I usually use to test CSV imports or Theme's I've been working on. I'm the Store Owner of course. I did read somewhere these apps sometimes don't work quite correctly in a development store but that didn't really make sense to me.

Thanks in advance!

**Comment by lizkenyon** [comment]
Hi there 👋 
Thank you for reaching out, and thanks for checkout out the tutorial!

There was an issue with the remix app template yesterday, that has now been resolved that may be related to the errors you were seeing.

You can clone a new template with the command `npm init @shopify/app@latest` to get the latest version.

This app should work as expected on development stores.

**Comment by MiGorainger** [comment]
> Hi there 👋 Thank you for reaching out, and thanks for checkout out the tutorial!
> 
> There was an issue with the remix app template yesterday, that has now been resolved that may be related to the errors you were seeing.
> 
> You can clone a new template with the command `npm init @shopify/app@latest` to get the latest version.
> 
> This app should work as expected on development stores.

Thanks for your help! I didn't think I was doing anything wrong. I'll check again today :)
