### ISSUE TITLE
Deploy template to AWS not passing cookie when install app

### ISSUE THREAD

**Issue by hungds99** [Shopify/shopify-app-template-remix#510]
# Issue summary

I am using this template to deploy to AWS Severless infrastructure. I use SST.dev (RemixSite Stack) to build infra and deploy my code (include Cloudfront, S3, API gateway integrate with Lamba Proxy).
But I got this issue when I tried to install my app into development store.
```
ERROR	[shopify-app/ERROR] Error during OAuth callback | {
    error: Cannot complete OAuth process. Could not find an OAuth cookie for shop url: *.myshopify.com
}
```

When I check my Lambda log. I can not see the `cookie in headers`, But It can see in `Cloudfront logs`. I think I missed some configurations to pass `cookie` to API Gateway.

## Steps to reproduce the problem

1.
1.
1.

**Comment by matteodepalo** [comment]
Hi @hungds99, as far as I understand this is an issue with tooling external to Shopify so I'm going to close the issue.
