### ISSUE TITLE
Ability automatically call shopify.loading function on the client

### ISSUE THREAD

**Issue by Rafi993** [Shopify/shopify-app-template-remix#514]
# Feature request

* Lets say you are triggering an `action` and the merchant has to wait for sometime till the action is complete. You will show a inline loader or `shopify.loading`
* But since the database operation happens on the server where app bridge is not initialized you will end up writing a bunch of boiler plate code to set and reset (incase of failure or success) of `shopify.loading` function
* It would be awesome if the Remix template had a way to do this by default without any extra boiler plate. It probably should be opt-in for specific pages / action or at least opt-out if you don't want to exclude some action from this loader

**Comment by paulomarg** [comment]
Hi, thank you for raising this! I've forwarded the feedback to the team, and we'll look into what can be done.
