### ISSUE TITLE
Remix Installed app getting redirected to the App's URL instead of admin portal(admin.shopify.com)

### ISSUE THREAD

**Issue by HarshaKDeltaX** [Shopify/shopify-app-template-remix#518]
# Issue summary

Remix Installed app getting redirected to the App's URL instead of admin portal(admin.shopify.com)
- This is happening only on Production env.

- `@shopify/shopify-app-remix` version: ^1.3.0
- Node version: v16.17.0
- Operating system: Linux

## Expected behavior

When the App is installed it should stay in the admin protal and complete the Auth. In my case it's redirected to the https://{MyAppURL}/store/{StoreName}/apps/{AppId}
Instead of https://admin.shopify.com/store/{StoreName}/apps/{AppId}
## Actual behavior

It should be expected to redirect to the admin portal of the shopify.

![image](https://github.com/Shopify/shopify-app-template-remix/assets/153831842/118c5926-e6b4-4d9b-a913-4832f702cd89)

When I update the app URL to admin.shopify.com, I can access my Application.

Updated https://measurementapp.mediabuy.pro/store/ako-dev-store/apps/6f274f83543385cee3c49e0b9e9c1cf6 to https://admin.shopify.com/store/ako-dev-store/apps/6f274f83543385cee3c49e0b9e9c1cf6 It worked for me

**Comment by paulomarg** [comment]
Hi, sorry to hear you're having issues. In general, this is what happens after OAuth:
- if the app is embedded (`isEmbeddedApp` config in `shopifyApp` is `true`), it will read the `host` search param and take the user there
- if not embedded, it'll take you to the app root (what you're seeing)

Can you please double check:
- that the app is configured as embedded in both environments?
- the `host` value is correct when `/auth/callback` is called (assuming you're using the default template settings). It is a base64 string, so you'll need to decode it
  - I believe it's very unlikely that this is the case, but it could be an issue with Shopify itself if this is anything other than the store

Hope this helps!

**Comment by HarshaKDeltaX** [comment]
Hi @paulomarg, It's an Embedded app which is configured as an embedded app from both in code and partners dashboard.

**Code:** shopify.server.js
const shopify = shopifyApp({
  apiKey: process.env.SHOPIFY_API_KEY,
  apiSecretKey: process.env.SHOPIFY_API_SECRET || "",
  apiVersion: LATEST_API_VERSION,
  scopes: process.env.SCOPES?.split(","),
  appUrl: process.env.SHOPIFY_APP_URL || "",
  authPathPrefix: "/auth",
  sessionStorage: new PrismaSessionStorage(prisma),
  distribution: AppDistribution.AppStore,
  restResources,
  webhooks: {
    APP_UNINSTALLED: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks",
    },
  },
  hooks: {
    afterAuth: async ({ session }) => {
      shopify.registerWebhooks({ session });
    },
  },
  ...(process.env.SHOP_CUSTOM_DOMAIN
    ? { customShopDomains: [process.env.SHOP_CUSTOM_DOMAIN] }
    : {}),
    **isEmbeddedApp: true**
});

**Partners Dashboard:**
![image](https://github.com/Shopify/shopify-app-template-remix/assets/153831842/74e22fad-1900-4f08-a357-7ffb1b19c093)

**Comment by paulomarg** [comment]
Hey, so it sounds like your configuration is correct for an embedded app.

It's normal for the `redirect_uri` in the OAuth request to go back to the app. The flow goes:

`/auth` => Shopify (shows grant page to merchant) => `/auth/callback` => `<store>/apps/<id>`

The app needs to receive the callback as a confirmation that the process was successful to complete the installation.

It sounds like there could be something going wrong in your callback. I would suggest that you check the `host` search param in the `/auth/callback` request (it's a base64 string so you'll have to decode it). If that value points to your app and not the store, there could be a bug here.

**Comment by HarshaKDeltaX** [comment]
Hey @paulomarg, Recorded the URL for auth/callback 

URL: https://measurementapp.mediabuy.pro/auth/callback?code=1cdf88d1efbab7ed3ec2a133ac7c8332&hmac=05786a1bdb6cea3c447010d7d42bc28e635850df96cf217cfd483f66fe76ba0a&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYWtvLWRldi1zdG9yZQ&shop=ako-dev-store.myshopify.com&state=138034622499571&timestamp=1706027974

**host:** YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYWtvLWRldi1zdG9yZQ

**Decoded value:** admin.shopify.com/store/ako-dev-store

the query param is right, but still it redirects to https://measurementapp.mediabuy.pro/store/ako-dev-store

**Comment by paulomarg** [comment]
Glad to hear you figured it out! Also, thank you for sharing your solution in case others also run into this kind of issue!
