### ISSUE TITLE
Browser refresh sending invalid timestamps

### ISSUE THREAD

**Issue by mgill404** [Shopify/shopify-app-template-remix#519]
# Issue summary

Some refresh actions on Mac OS are triggering calls to my remix server with outdated timestamps. The most reliable way i can cause this to happen is just to shut the lid of the laptop and open it back up.

I'm unsure if this is a Shopify, Mac OS, or Chrome issue.

Was hoping someone on your team could look and see if you can do anything about this. I have considered checking timestamps myself and updating them but that seems inappropriate. Maybe This is the way?

## Preliminary
I'm on a Macbook OS 13.0 using Google Chrome .

## Reproduction Steps

1. npm run dev
2. open the app in the admin (notice timestamps)
3. Wait 2 minutes.
4. close macbook clamshell
5. open macbook clamshell (notice refresh timestamps)

## Actual Behavior

Timestamps sent to my remix server are the same for the 2 cases

1. The initial request sent to the app
2. The refresh action that occurs when reopening the mac.

401 and 302 errors occur when timestamp becomes invalid (around 1 minute old)

## Expected Behavior

Timestamps should be updated to prevent errors

## Logs

```
00:38:52 │ remix    │ [shopify-app/INFO] Authenticating admin request
00:38:52 │ remix    │ [shopify-app/INFO] Authenticating admin request
00:38:52 │ remix    │ GET /app?embedded=1&hmac=<hmac>&id_token=<id_token>&locale=en&session=<session>&shop=<shop>&timestamp=1706074731 200 - - 15.413 ms

*** close clamshell. open it back up. ***

00:40:16 │ remix    │ [shopify-app/INFO] Authenticating admin request
00:40:16 │ remix    │ GET  /app?embedded=1&hmac=<hmac>&id_token=<id_token>&locale=en&session=<session>&shop=<shop>&timestamp=1706074731&_data=routes%2Fapp._index 401 - - 5.205 ms
```

## Note

I'm not certain the timestamp is the exact source of the errors, it is just what I can identify that looks inconsistent.

If I route to a different URL with a button from within the app, the timestamp is removed as a query parameter. The behavior then becomes slightly different as the app routes to `/auth/login`

logs from that behavior

```
19:59:33 │ remix │ [shopify-app/INFO] Authenticating admin request
19:59:33 │ remix │ GET /app/additional?_data=routes%2Fapp 200 - - 7.409 ms
20:02:23 │ remix │ GET /app/additional 302 - - 3.973 ms
20:02:23 │ remix │ GET /auth/login 200 - - 12.748 ms
20:02:24 │ remix │ GET /auth/login 200 - - 10.912 ms
20:02:24 │ remix │ GET /auth/login 200 - - 3.726 ms
20:02:25 │ remix │ GET /auth/login 200 - - 9.688 ms
```

**Comment by AnthonyGress** [comment]
We get this same issue if we just wait 2-5 mins on the home screen of our app

**Comment by paulomarg** [comment]
Hey folks, thanks for raising this, and sorry you're having issues! I believe this happens outside the template - the timestamp is added by the admin itself - so there won't be much we can do from here.

I'll forward the feedback to the team to see what we can do. I'll circle back with a response.

**Comment by paulomarg** [comment]
Just a quick follow-up that might help debug this: if you leave the browser dev tools open, can you see what is triggering the request? I.e. is it chrome itself, is it sent from within the application, etc.?

**Comment by naamjap** [comment]
As a workaround  - please run the below command to update your local time, this resolved the above error

sudo sntp -sS time.apple.com

you could use the ntp command as well for linux
