### ISSUE TITLE
Session prisma upsert issue associated with unstable_newEmbeddedAuthStrategy

### ISSUE THREAD

**Issue by boxedcode** [Shopify/shopify-app-template-remix#536]
# Issue summary

How does setting this future flag `unstable_newEmbeddedAuthStrategy` affect the authentication flow, as in what does it actually do? The reason I ask is that I discovered an issue yesterday while trying to install my app on a `second` development store and the issue only resolved itself after I removed that flag.

It's possible that it could have failed the same way when installing the app on only one development store, but I haven't tested that specific scenario.

At some stage during the authentication flow, Prisma threw the following error logs:

```
16:42:25 │ remix      │ prisma:query INSERT INTO `ShopSession`
(`id`,`shop`,`state`,`isOnline`,`scope`,`expires`,`accessToken`,`userId`) VALUES (?,?,?,?,?,?,?,?)
16:42:25 │ remix      │ prisma:query ROLLBACK
16:42:25 │ remix      │ prisma:error
16:42:25 │ remix      │ Invalid `this.getSessionTable().upsert()` invocation in
16:42:25 │ remix      │ /Users/user/app/node_modules/@shopify/shopify-app-session-storage-prisma/build/cjs/prisma.js:27:34
16:42:25 │ remix      │
16:42:25 │ remix      │   24 async storeSession(session) {
16:42:25 │ remix      │   25   await this.ready;
16:42:25 │ remix      │   26   const data = this.sessionToRow(session);
16:42:25 │ remix      │ → 27   await this.getSessionTable().upsert(
16:42:25 │ remix      │ Unique constraint failed on the constraint: `PRIMARY`
16:42:25 │ remix      │ PrismaClientKnownRequestError:
16:42:25 │ remix      │ Invalid `this.getSessionTable().upsert()` invocation in
```

I looked at the session table in the database after seeing this error, and it had entries for the offline and online access tokens, so it didn't have a problem creating the entries in the first place. I also looked at the line of code referenced in the error log, but didn't see anything obvious.

I was able to replicate this error several times by repeating the installation process / refreshing the page when viewing the app, and it only worked when I removed the future flag:

```
unstable_newEmbeddedAuthStrategy: true,
```

- `@shopify/shopify-app-remix` version: `2.4.0`
- Node version: `v21.6.1`
- Operating system: `Mac OS Sonoma 14.2.1`
- Prisma version: `5.9.1`

## Expected behavior

Installation and authentication process for the app should have completed successfully.

## Actual behavior

Installation is successful, but follow-up Oauth process fails midway.

1. Install app on a development store
1. Enable `unstable_newEmbeddedAuthStrategy` future flag
1. Install app on a second development store

**Comment by zzooeeyy** [comment]
Hey @boxedcode, I'm trying to reproduce this on my side, could you let me know what your DB backend is? `sqlite`,  `MySQL`? Thanks!

**Comment by boxedcode** [comment]
Hi @zzooeeyy , I use MySQL 8.2 . Thanks.

**Comment by hamzasgd** [comment]
I'm getting the same
