### ISSUE TITLE
unstable_newEmbeddedAuthStrategy doesn't work installing the app through uninstalled apps list

### ISSUE THREAD

**Issue by skamarakas** [Shopify/shopify-app-template-remix#553]
Hi,

# Issue summary
unstable_newEmbeddedAuthStrategy doesn't work installing the app through uninstalled apps list. 

- `@shopify/shopify-app-remix` version: 2.5.0
- Node version: 20.11.0
- Operating system: macOS Sonoma 14.2.1

## Expected behavior

I should be able to force uninstall / reinstall the app through uninstalled apps list `/settings/apps?tab=uninstalled`

## Actual behavior

By reinstalling my embedded app through uninstalled apps list I get 404 and `afterAuth` hook is not being called at all.

## Steps to reproduce the problem

1. Create a demo app following these steps: https://shopify.dev/docs/apps/getting-started/create
1.1 `npm init @shopify/app@latest`
1.2 `npm run dev`
2. Uninstall the app and then try to reinstall it through uninstalled apps list `/settings/apps?tab=uninstalled`
<img width="728" alt="Screenshot 2024-02-12 at 21 34 18" src="https://github.com/Shopify/shopify-app-template-remix/assets/14952363/2d62d5b8-59a6-4bfd-8a22-48c9093db45f">

**Comment by Alex-Levacher** [comment]
I wanted to mention that I have the same issue. Thanks to @skamarakas for bringing it up. I hope we get more information soon.

**Comment by Pitas1** [comment]
i also have the same problem!

**Comment by alvaro-shopify** [comment]
Hey everyone 👋 !, The fix has been shipped to production. Please, let me know if it's working for you.

**Comment by dani-sanomads** [comment]
@alvaro-shopify - We are still having this issue. Not able to use it even for the `@shopify/shopify-app-remix` v3.0.2. Also  getting infinite redirects after the installation process as it is tested by the Shopify App Review team. It works fine on development stores locally.
