### ISSUE TITLE
"No valid session found and Requesting offline access token" info occurs when opening the app.

### ISSUE THREAD

**Issue by chenluhe** [Shopify/shopify-app-template-remix#561]
### Steps:
1. Clone the "shopify-app-template-remix" project locally, enter the project directory, and execute the npm install and npm run dev commands respectively.
2. Then press the "P" key to install the app. After the installation is completed, the page will be blank.

### The error log is as follows:
chenluhedeMacBook-Pro:shopify-app-template-remix chenluhe$ npm run dev

> dev
> shopify app dev
......
......
......
20:47:02 │ remix      │ [shopify-app/INFO] No valid session found
20:47:02 │ remix      │ [shopify-app/INFO] Requesting offline access token
20:47:02 │ remix      │ [shopify-app/INFO] No valid session found
20:47:02 │ remix      │ [shopify-app/INFO] Requesting offline access token
20:47:18 │ remix      │ GET /app?embedded=1&hmac=2deefb8f94b3b37ad4e8484a29481cb9fb979bd32b3fb4dfac7c6d5b8acf88e6&host=YWRtaW4uc2hvcGlmeS5jb20vc3Rvcm
UvbHVoZWRldg&id_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczpcL1wvbHVoZWRldi5teXNob3BpZnkuY29tXC9hZG1pbiIsImRlc3QiOiJodHRwczpcL1wvbH
VoZWRldi5teXNob3BpZnkuY29tIiwiYXVkIjoiZDg4YmYwMzU5YzE0M2JlNzAxOTBiN2ZhZTJjMTU1ZGQiLCJzdWIiOiIxMDYzNDIzNTExNTgiLCJleHAiOjE3MDg0MzMyNzcsIm5iZiI6MTcwODQ
zMzIxNywiaWF0IjoxNzA4NDMzMjE3LCJqdGkiOiI0YjU2YTUxZi0wYzIwLTRjZmUtODRjOS00MmI5MmY1OWJkZDAiLCJzaWQiOiIzZjlkOTM4NC0wMmI2LTQxOWItYTU2Zi0yZWExMjA2OTNkMDMi
LCJzaWciOiIxYTZlMmRmN2ZhNWRhZmQ5YTg5YTY3MzQ3N2YyNWE1NDMzYjc4MzUwYTAzYmNkNTRiZGUwNGYyZmYxODlmY2I3In0.qJmEvJmrejppSAQgAOdOU0ADsq_9T_nJW1Mf1T2S8pg&local
e=zh-CN&session=5184ec4af111d6e037471b9578c1ada1b1ea52ba76b90f69af906cecfb622501&shop=luhedev.myshopify.com&timestamp=1708433217 500 - - 15474.066 ms
.......
......
......

**Comment by Zardw** [comment]
I also met a similar error. I just created the app, but when I ran it, a Handling response error occurred.

![image](https://github.com/Shopify/shopify-app-template-remix/assets/117419340/14978902-a958-42b6-851d-e9ce8bbbde8a)

**Comment by chenluhe** [comment]
> I also met a similar error. I just created the app, but when I ran it, a Handling response error occurred.
> 
> ![image](https://private-user-images.githubusercontent.com/117419340/306827927-14978902-a958-42b6-851d-e9ce8bbbde8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NzEzODMsIm5iZiI6MTcwODU3MTA4MywicGF0aCI6Ii8xMTc0MTkzNDAvMzA2ODI3OTI3LTE0OTc4OTAyLWE5NTgtNDJiNi04NTFkLWU5Y2U4YmJiZGU4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQwMzA0NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDdkYjZkZDc2MjIyNWYwNDdhM2U2NDJiMzRiNjIwYjZlYzNjZjgxYmM5MGE5NjEzNjNmYmRmMmFiMjNiMDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sg8pTiwE6ZtRvc3s-VYhVkgOrHsv4T_KZAflLa_I-dI)

Latest progress: I found that the reason is that there is no data in the Session table. Why is there no data? Ignore this reason for now. I manually added a record to the Session table, similar to this: 
<img width="1426" alt="image" src="https://github.com/Shopify/shopify-app-template-remix/assets/27548589/16ebc461-4ea5-4bed-8fd6-5f232419f089">

Then after reopening the app, this error no longer occurred, and the app page could be displayed normally.

**Comment by Zardw** [comment]
@rachel-carvalho this project is created by Shopify Cli, I haven't done any changes, run it directly, but it gets 500 error, cannot save the Session data into database.
I created a project before, it could run normally, after some updates by them, newly created projects are not running properly.

**Comment by Zardw** [comment]
@koaqiu 我也是这样, 好像都是国内的, 可能触发的webhook事件没有添加店铺的session数据.
添加数据去数据库手动加, 运行app的payload里面有session数据

**Comment by faner11** [comment]
I'm getting this error too, my http://localhost:3457/graphiql is not responding

**Comment by koaqiu** [comment]
> @koaqiu 我也是这样, 好像都是国内的, 可能触发的webhook事件没有添加店铺的session数据. 添加数据去数据库手动加, 运行app的payload里面有session数据

我发现 手动添加进去以后，还会有后续问题，能不能加个wx请教一下

**Comment by chenluhe** [comment]
应该就是国内网络问题，我这边时好时坏。。。

**Comment by Zardw** [comment]
随便填吧, 也没啥数据, state和token乱写的, 不知道对后续有什么影响.

![image](https://github.com/Shopify/shopify-app-template-remix/assets/117419340/127c0a31-0106-45c8-9181-183ab4e333ec)

**Comment by shaimeizi** [comment]
@Zardw 可以了，感谢！

**Comment by damonchen** [comment]
When no valid session found happened, the system will call token exchange url to get the token. Due to the gfw, the node fetch function could not connect the `https://xxxx.myshopify.com/admin/oauth/access_token`, and will be got the Timeout error.

**Comment by coderlinbb** [comment]
me too.

**Comment by peihuanhuan** [comment]
same to me

**Comment by pobed2** [comment]
> When no valid session found happened, the system will call token exchange url to get the token. Due to the gfw, the node fetch function could not connect the https://xxxx.myshopify.com/admin/oauth/access_token, and will be got the Timeout error.

Unfortunately, since this is a network problem, there's not much we can do about this. The app needs to be able to connect to the Shopify to work.

I assume this isn't strictly a token exchange problem, but could you try setting `unstable_newEmbeddedAuthStrategy: false` in `shopify.server.js`? This will disable the token exchange strategy and revert back to redirecting the user to the install flow to get a token.

**Comment by faner11** [comment]
@pobed2 
After trying and jumping to `xxxx.ngrok-free.app/auth/callback?code=xxx`, I still get HTTP ERROR 500.
I added a proxy to the terminal running `pnpm dev` and the proxy bypasses gfw. but still get http 500

**Comment by faner11** [comment]
This works for me by adding a proxy to the native `fetch`.

```
import { setGlobalDispatcher, ProxyAgent } from "undici";
import { env } from "process";

if (import.meta.env.DEV && env.https_proxy  ) {
  // Corporate proxy uses CA not in undici's certificate store
  process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
  const dispatcher = new ProxyAgen({uri: new URL(env.https_proxy).toString() });
  setGlobalDispatcher(dispatcher);
}
```

**Comment by 772265646** [comment]
还没有解决办法吗

**Comment by xigongdaEricyang** [comment]
> This works for me by adding a proxy to the native `fetch`.
> 
> ```
> import { setGlobalDispatcher, ProxyAgent } from "undici";
> import { env } from "process";
> 
> if (import.meta.env.DEV && env.https_proxy  ) {
>   // Corporate proxy uses CA not in undici's certificate store
>   process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
>   const dispatcher = new ProxyAgen({uri: new URL(env.https_proxy).toString() });
>   setGlobalDispatcher(dispatcher);
> }
> ```

Could you tell me what's the content of https_proxy ?

**Comment by faner11** [comment]
@xigongdaEricyang 你这个问题太基础了，去google吧，如果嫌麻烦，可以付费问问题。wx: ZmhoaDIw （这是base 64，你需要先解码）

**Comment by koaqiu** [comment]
@xigongdaEricyang  @772265646 
最终解决方案就是 搞个速度快的VPN梯子，直接全局代理过去。然后就清爽了。
记住一定要用VPN模式的，什么http socket代理的 配置起来很麻烦--你无法保证某个组件访问网络的时候能一定是通过代理走！

**Comment by 18239388662** [comment]
done! 上面的都试过了， 就是梯子问题，实在不行就换梯子

**Comment by yanyi24** [comment]
> > @xigongdaEricyang @772265646 最终解决方案就是 搞个速度快的VPN梯子，直接全局代理过去。然后就清爽了。 记住一定要用VPN模式的，什么http socket代理的 配置起来很麻烦--你无法保证某个组件访问网络的时候能一定是通过代理走！
> > @chenluhe 这问题其实可以结案了，网络问题导致。
> 
> 确实！我现在一键全代了，就好了，汗

你用的哪个梯子？

**Comment by yanyi24** [comment]
统一回复，可以用个速度快的梯子就行，根本没有其他bug。推荐一个我用的梯子，主要是推荐有奖，

下载链接（推荐使用 Chrome 浏览器访问）：https://bitbucket.org/letsgo666/letsgogo_4/src/main/README.md
安装后打开填写我的ID：373689881 你能多得3天会员！

> > > [@xigongdaEricyang](https://github.com/xigongdaEricyang) [@772265646](https://github.com/772265646) 最终解决方案就是 搞个速度快的VPN梯子，直接全局代理过去。然后就清爽了。 记住一定要用VPN模式的，什么http socket代理的 配置起来很麻烦--你无法保证某个组件访问网络的时候能一定是通过代理走！
> > > [@chenluhe](https://github.com/chenluhe) 这问题其实可以结案了，网络问题导致。
> > 
> > 
> > 确实！我现在一键全代了，就好了，汗
> 
> 请问您用的什么VPN呀

统一回复，可以用个速度快的梯子就行，根本没有其他bug。推荐一个我用的梯子，主要是推荐有奖，如果你信，感谢填写我的ID：373689881 

下载链接（推荐使用 Chrome 浏览器访问）：https://bitbucket.org/letsgo666/letsgogo_4/src/main/README.md
安装后打开填写我的ID：373689881 你能多得3天会员！

**Comment by zsf1482451437** [comment]
> 你的应用是没改过的吗, 刚创的? 我现在没用cloudflare, 好像一个账号只能发布3个网站, 不知道你啥情况 我用ngrok, 然后执行这个, 当然梯子得都有用 npm run dev -- --tunnel-url https://ffa6-183-17-56-168.ngrok-free.app:3000

好，我尝试下

**Comment by zsf1482451437** [comment]
> 你的应用是没改过的吗, 刚创的? 我现在没用cloudflare, 好像一个账号只能发布3个网站, 不知道你啥情况 我用ngrok, 然后执行这个, 当然梯子得都有用 npm run dev -- --tunnel-url https://ffa6-183-17-56-168.ngrok-free.app:3000

是的，按照官网教程来的

**Comment by Zardw** [comment]
应该是梯子的问题了, Session数据没有加到数据库里面
临时解决方案就是在数据库手动添加一条数据, 运行app的payload里面有session数据

![Image](https://github.com/user-attachments/assets/b4e4f156-9562-4793-a252-4c425fc86c97)

**Comment by zsf1482451437** [comment]
> 应该是梯子的问题了, Session数据没有加到数据库里面 临时解决方案就是在数据库手动添加一条数据, 运行app的payload里面有session数据
> 
> ![Image](https://github.com/user-attachments/assets/b4e4f156-9562-4793-a252-4c425fc86c97)

![Image](https://github.com/user-attachments/assets/d3748ca8-89e7-488f-acd6-e4d5cf6245a3)
是这里的数据吗

**Comment by zsf1482451437** [comment]
> 应该是梯子的问题了, Session数据没有加到数据库里面 临时解决方案就是在数据库手动添加一条数据, 运行app的payload里面有session数据
> 
> ![Image](https://github.com/user-attachments/assets/b4e4f156-9562-4793-a252-4c425fc86c97)

表中accessToken是填payload中的id_token还是session

**Comment by zsf1482451437** [comment]
> state和token好像可以乱写, 记不清了, 你试一下

都试过了，还是不行，要不咱加个wx，你远程操作下，有偿，拜托了

**Comment by Zardw** [comment]
可以帮你远程看一下, 不一定帮得上忙, 不要钱

**Comment by lili77JL** [comment]
> 统一回复，可以用个速度快的梯子就行，根本没有其他bug。推荐一个我用的梯子，主要是推荐有奖，
> 
> 下载链接（推荐使用 Chrome 浏览器访问）：https://bitbucket.org/letsgo666/letsgogo_4/src/main/README.md 安装后打开填写我的ID：373689881 你能多得3天会员！
> 
> > > > [@xigongdaEricyang](https://github.com/xigongdaEricyang) [@772265646](https://github.com/772265646) 最终解决方案就是 搞个速度快的VPN梯子，直接全局代理过去。然后就清爽了。 记住一定要用VPN模式的，什么http socket代理的 配置起来很麻烦--你无法保证某个组件访问网络的时候能一定是通过代理走！
> > > > [@chenluhe](https://github.com/chenluhe) 这问题其实可以结案了，网络问题导致。
> > > 
> > > 
> > > 确实！我现在一键全代了，就好了，汗
> > 
> > 
> > 请问您用的什么VPN呀
> 
> 统一回复，可以用个速度快的梯子就行，根本没有其他bug。推荐一个我用的梯子，主要是推荐有奖，如果你信，感谢填写我的ID：373689881
> 
> 下载链接（推荐使用 Chrome 浏览器访问）：https://bitbucket.org/letsgo666/letsgogo_4/src/main/README.md 安装后打开填写我的ID：373689881 你能多得3天会员！

**Comment by yanyi24** [comment]
软件首次下载，打开左侧菜单栏在最下方可以填写推荐人ID哦。

Windows 版本：由于存在盗刷服务的情况，因此需先购买会员后才可以填写。

iOS版本：由于苹果那边的限制，暂时无法参与推荐活动。

PS：首次下载软件24小时可以填写推荐人ID。超过24小时就无法填写

在 2025年6月30日，14:13，lili77JL ***@***.***> 写道：

﻿
[https://avatars.githubusercontent.com/u/49280251?s=20&v=4]lili77JL left a comment (Shopify/shopify-app-template-remix#561)<https://github.com/Shopify/shopify-app-template-remix/issues/561#issuecomment-3017925716>

安装之后在哪里填id呢，好像没看到
