### ISSUE TITLE
There is a problem with the sourcemap of the project

### ISSUE THREAD

**Issue by Malenconiaprincep** [Shopify/shopify-app-template-remix#574]
# Issue summary

I am debugging the front-end code, but the location is wrong

- `@shopify/shopify-app-remix` version: 2.5.0
- Node version: 18.12.0
- Operating system: macOs 13.6.1

![image](https://github.com/Shopify/shopify-app-template-remix/assets/6262739/9053886f-defa-42d5-b1bb-ec95e17e5f99)

## Expected behavior

The sourcemap location is correct

## Actual behavior

The sourcemap location is incorrect

## Steps to reproduce the problem

1. Write a random js to debug
2. View the corresponding location information

**Comment by sle-c** [comment]
Hi @Malenconiaprincep , can you try update the packages? The sourcemap should be correct for the template now

![Image](https://github.com/user-attachments/assets/400a4e41-8f85-4007-b828-92b36e49bb5f)
