### ISSUE TITLE
Migrating from remix (non-vite) project to remix (vite)

### ISSUE THREAD

**Issue by RaffaySajjad** [Shopify/shopify-app-template-remix#575]
# Issue summary
I developed a Remix App prior to this template's migration to Vite. There is a library [@shopify/polaris-viz](https://www.npmjs.com/package/@shopify/polaris-viz) I am using for charts. However it was consistently throwing the error `ERR_REQUIRE_ESM string-width` while attempting to run the project. It was subsequently fixed by using `serverDependenciesToBundle` as suggested [here](https://github.com/Shopify/shopify-app-template-remix/issues/334). However now, I'm having trouble migrating this to vite implementation. Since there is no `remix.config.ts` anymore what should be the best way to handle the following error?

```
require() of ES Module /app/node_modules/d3-scale/src/index.js from /app/node_modules/@shopify/polaris-viz-core/build/cjs/utilities/createGradient.js not supported.
Instead change the require of index.js in /app/node_modules/@shopify/polaris-viz-core/build/cjs/utilities/createGradient.js to a dynamic import() which is available in all CommonJS modules.
```

Looking at the discussions [7872](https://github.com/remix-run/remix/discussions/7872) and [7865](https://github.com/remix-run/remix/issues/7865) on the official remix repo doesn't seem to be working. As suggested in [7865](https://github.com/remix-run/remix/issues/7865#issuecomment-1789900955) I put the erroneous package, in this case `d3-scale` to ssr -> noExternal but this doesn't seem to be working.

```
ssr: {
    noExternal: ["d3-scale"]
}
```

- `@shopify/shopify-app-remix` version: 2.6.1
- Node version: v20.10.0
- Operating system: Sonoma 14.2.1

```
// Paste any relevant logs here
require() of ES Module /app/node_modules/d3-scale/src/index.js from /app/node_modules/@shopify/polaris-viz-core/build/cjs/utilities/createGradient.js not supported.
Instead change the require of index.js in /app/node_modules/@shopify/polaris-viz-core/build/cjs/utilities/createGradient.js to a dynamic import() which is available in all CommonJS modules.
```

## Expected behavior
Should be able to use PolarisViz correctly.

## Actual behavior
Environment is failing with the aforementioned error while trying to execute `yarn dev`

## Steps to reproduce the problem

1. Setup a new project
2. Add @shopify/polaris-viz to the project
3. import { PolarisVizProvider } from "@shopify/polaris-viz";

**Comment by joefitter** [comment]
@RaffaySajjad did you solve this? Having the same issue with Remix + Vite

**Comment by RaffaySajjad** [comment]
> @RaffaySajjad did you solve this? Having the same issue with Remix + Vite

Hi @joefitter Yes, In my case it was the missing polaris-viz libraries that need to be included in `vite.config.js`

<img width="653" alt="Screenshot 2024-04-17 at 5 29 54 PM" src="https://github.com/Shopify/shopify-app-template-remix/assets/25899678/b4bf1518-9d4a-4f2c-ad18-8ff735c6e626">
