### ISSUE TITLE
Error forwarding websocket request: AggregateError

### ISSUE THREAD

**Issue by mkromann** [Shopify/shopify-app-template-remix#576]
# Issue

I just migrated to Vite but I am getting this following error continuously `Error forwarding websocket request: AggregateError`.

<img width="367" alt="2024 02 27_08 57 26 • iTerm2 — npm run dev@2x" src="https://github.com/Shopify/shopify-app-template-remix/assets/1389467/12ad3e84-be95-4e73-836b-7547107d4493">

Furthermore, it causes the UI to flash and ultimately fails. It seems Vite loses connection and keeps attempting to reconnect. This is part of the browser console:

<img width="1067" alt="2024 02 27_08 59 44 • Google Chrome — Mærkbare · Splay Development · Shopify@2x" src="https://github.com/Shopify/shopify-app-template-remix/assets/1389467/9ba0bed7-6fc5-4a7c-add0-1678bb828fb4">

Attempted with both default tunnel (Cloudflare) and our own tunnel — same issue.

- `@shopify/shopify-app-remix` version: 2.6.1
- Node version: v20.11.1
- Operating system: MacOs

**Comment by mkromann** [comment]
Seems like the connection is lost immediately upon navigation to a route:
<img width="1078" alt="2024 02 27_10 10 05 • Google Chrome — Mærkbare · Splay Development · Shopify@2x" src="https://github.com/Shopify/shopify-app-template-remix/assets/1389467/8955d314-14ef-4266-bd09-449d0caf1ac8">

**Comment by huykon** [comment]
> @mkromann faced same issue when migrate to vite. Remove this from shopify.web.toml fixed it for me
> 
> ```
> [hmr_server]
> http_paths = ["/ping"]
> ```
> 
> just try follow [template source](https://github.com/Shopify/shopify-app-template-remix/blob/main/shopify.web.toml)

I followed this but it's still error

**Comment by johnsethsalazar** [comment]
I'm also having the same issue and tried the solution above but it didn't work for me.
![image](https://github.com/Shopify/shopify-app-template-remix/assets/24352433/a9bf2ba3-d6d9-4f56-86f8-f6959cc90369)

**Comment by stefanoHTB** [comment]
I got the same issue as well

**Comment by roman-gavrilov** [comment]
same issue here.  

node -v : 20.15.1
shopify v: 3.64.1

**Comment by Ash-Matter** [comment]
I am suddenly getting this issue as well. Wasn't occurring the day before, started the development process today and experiencing the app reloading every couple of seconds. I thought perhaps the app I was working on may have had an accidental typo, so I created a fresh app through `shopify app init` and ran `npm run dev` upon its completion and even the fresh install proceeded to experience the exact same result.

I've tried countless times using `npm run dev -- --reset` with no change in experience.
Updated the CLI to the latest.
Tried multiple different browsers.

The result remains the same:
![Image](https://github.com/user-attachments/assets/e779572d-8450-4709-9cc6-8f27c0de5d4f)

Interestingly, I visited the http path for the socket, which is also listed in the `shopify.app.toml`:
![Image](https://github.com/user-attachments/assets/0aa883e9-8e11-43a4-8341-57ba69a39ad3)

And the page that it loads has the exact same experience, except its completing a full page reload, which suggests this is more an issue with Vite itself.

It seems theres some untapped issues within the `vite.config.js` as I replaced the `SHOPIFY_APP_URL` reference with the hardcoded path of the store I was running the app development on and the reloading ceased immediately as soon as the change was saved.

![Image](https://github.com/user-attachments/assets/b9cc0d32-24f1-4dd2-8669-23b1e8c8844f)

![Image](https://github.com/user-attachments/assets/c427f73f-5dba-401c-88d4-d55ce2c6e9e9)

So theres clearly something off with these env vars within the setup/build process that breaks.
This is obviously only a temp fix while developing - unsure if theres an ongoing issue with this when deploying and running apps in production.

Hopefully this helps uncover the underlaying issue with the env vars and a change can be made to prevent this from occurring and not needing manual intervention to allow it to work.

**Comment by Ash-Matter** [comment]
I've spent way too long trying to figure out how to get around this as I'm experiencing this too.
Its an issue is vite server as far as I can tell and one thing that I've found that gets around it is following a note found on the [vite website](https://vitejs.dev/config/server-options):

![Image](https://github.com/user-attachments/assets/19b5ebf8-7594-4aa9-86d3-4c25cf9158fd)

I opted to do with the 2nd point, changing the `clientPort` value to match the port the server itself is being set to, and adding the `strictPort` attribute.

![Image](https://github.com/user-attachments/assets/be30a839-8217-47c6-8986-a65642ac0576)

It has removed the looping refresh of the page, however, breaks the hot reload when a change is made, so you need to refresh the entire page after every change made.

Small price to pay to be able to continue developing.

**Comment by arobbins** [comment]
FWIW, I think more people are experiencing this issue now: https://community.shopify.com/c/extensions/my-app-suddenly-can-t-find-extensions-in-app-preview/td-p/2726420
