### ISSUE TITLE
useBeforeUnload Hook Does Not Trigger Modal on Page in Shopify App Remix Template

### ISSUE THREAD

**Issue by yuhDAQ** [Shopify/shopify-app-template-remix#579]
# Issue summary

I am experiencing an issue with the useBeforeUnload hook in the shopify-app-template-remix, where the expected modal does not appear when attempting to navigate away from the app/settings page after changes have been made but not saved.

Despite implementing the useBeforeUnload hook to trigger a modal when there are unsaved changes, the modal fails to appear, and the page transitions occur without any warnings or confirmations.

- `@shopify/shopify-app-remix` version: 2.6.1
- Node version: 20
- Operating system: docker

```
// Paste any relevant logs here
```

## Expected behavior

When there are unsaved changes on the app/settings page, I expect the useBeforeUnload hook to trigger a modal asking the user to confirm the navigation away from the page. This should prevent loss of unsaved changes and provide a better user experience.

## Actual behavior

The useBeforeUnload hook does not seem to trigger the modal when navigating away from the app/settings page. As a result, changes can be lost without warning, leading to a poor user experience.

**Comment by lizkenyon** [comment]
Hi there 👋 

The Remix template uses [React Router](https://reactrouter.com/en/main/start/overview), which uses client side routing. 

That hook will not fire when navigating between pages, with client side routing. 

See [this comment](https://github.com/remix-run/react-router/issues/10894#issuecomment-1737708162) from the React Router team on this topic.
