### ISSUE TITLE
Set-Cookies ignored when redirect/json/new Request thrown inside loader using App Proxy public route

### ISSUE THREAD

**Issue by mtn-constantinebr** [Shopify/shopify-app-template-remix#583]
# Issue summary

I try to throw/return redirect/json/new Response inside loader for Proxy public route non authorized users with Session cookie like its written in Remix docs. I need to save Cookies with server session, where I save some stuff to validate response.

```
throw new Response(null, {
  status: 302,
  headers: {
    "Location": authUrl,
    "Set-Cookie": await commitSession(session),
    "Set-Cookie2": await commitSession(session), // this is for test that redirect/json/new Response were working
  },
});
```

But I have no Set-Cookie.

![image](https://github.com/Shopify/shopify-app-template-remix/assets/122273388/3cefffff-3e02-4bf4-90c7-b4f62e87733f)

- `@shopify/shopify-app-remix` version: 2.5.0
- Node version: 20.11.1
- Operating system: KDE neon (ubuntu based) Chrome browser

# Expected behavior
Set-Cookie header was set

# Actual behavior
Set-Cookie header wasn't set

# Steps to reproduce the problem
At public route create router and throw redirect or new Response  with Set-Cookie header

**Comment by matteodepalo** [comment]
Hi @mtn-constantinebr, thank you for opening this issue, we've forwarded it internally to the app proxy team.

**Comment by matteodepalo** [comment]
Due to security concerns some headers are stripped as mentioned in the docs [here](https://shopify.dev/docs/apps/online-store/app-proxies#disallowed-headers).
