### ISSUE TITLE
Remix + Vite + Express(custom): Error: listen EADDRNOTAVAIL: address not available

### ISSUE THREAD

**Issue by amazing-chicken** [Shopify/shopify-app-template-remix#586]
# Issue summary
I used custom server (express) according to remix's instructions. However, after running `npm run dev` I get the error `Error: listen EADDRNOTAVAIL: address not available {cloudflare_ip}:{cloudflare_port}`.
Instructions for switching to a custom server with remix's vite: https://remix.run/docs/en/main/future/vite#migrating-a-custom-server

- [shopify-app-template-remix](https://github.com/Shopify/shopify-app-template-remix) latest version
- Node version: 20.11.1
- Operating system: mac m1 pro

```
WebSocket server error: Error: listen EADDRNOTAVAIL: address not available {cloudflare_ip}:{cloudflare_port}
```

## Expected behavior
After running npm run dev there are no more errors

## Actual behavior
EADDRNOTAVAIL error occurred

## Steps to reproduce the problem

1. Create a new app: `npm init @shopify/app@latest`
2. After the above command is completed, add the custom express server according to the instructions: https://remix.run/docs/en/main/future/vite#migrating-a-custom-server
3. In `shopify.web.toml` change command `dev={your_command_to_run_dev}
4. Check terminal and you will see an error appear

**Comment by paulomarg** [comment]
Hey! We got a few different reports of issues with custom servers, I'm bringing them all together in #614 so we can discuss / fix things.
