### ISSUE TITLE
App requires access to "View personal data > Customers" on install without any customer scope

### ISSUE THREAD

**Issue by marcandreh** [Shopify/shopify-app-template-remix#594]
Hi all,

I successfully built and published a Shopify Custom App with this template.

Whenever I install my custom app in any Shopify store via install link, the admin gets ask for customer permissions (*View personal data > customers, store owner, content provider*), although I don't require any customer based scopes:

![image](https://github.com/Shopify/shopify-app-template-remix/assets/22033866/bf795c90-6529-4578-b679-3688fb68d89a)

```jsx
const shopify = shopifyApp({
  appUrl,
  apiKey,
  apiSecretKey,
  scopes: ['read_products', 'read_shipping', 'read_content', 'read_script_tags', 'write_script_tags'],

  apiVersion: ApiVersion.January24,
  restResources,

  distribution: AppDistribution.SingleMerchant,
  ...
});
```

Am I missing any option in `shopifyApp()` here? The app explicitly doesn't handle any PII data, so I am currently figuring out why it asks for such permissions on install.

Thank you!

**Comment by marcandreh** [comment]
I found out that the `read_shipping` scope may also access Fulfillment data, which may contain customer data. So there is no bug in this package but maybe a reason to update the docs?

In [Shopify API access scopes](https://shopify.dev/docs/api/usage/access-scopes) only Carrier Service, Country and Province access are documented.

![image](https://github.com/Shopify/shopify-app-template-remix/assets/22033866/f6cd3e7e-38a8-434a-8671-1f73a6f7c057)

See also [Why Do My App Need Permission To Orders, Even Without The Scope?](https://community.shopify.com/c/customers-discounts-and-orders/why-do-my-app-need-permission-to-orders-even-without-the-scope/m-p/1317919)

**Comment by lizkenyon** [comment]
Thanks for flagging this! Glad you were able to track this down. I will pass this on to our documentation team!
