### ISSUE TITLE
Authentication issues when navigating to nested routes

### ISSUE THREAD

**Issue by nboliver-ventureweb** [Shopify/shopify-app-template-remix#599]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the `@shopify` packages
  - Affected `@shopify/shopify-*` package and version: 
├── @shopify/app@3.57.0
├── @shopify/cli@3.57.0
├── @shopify/polaris@12.20.0
├── @shopify/shopify-api@9.5.0
├── @shopify/shopify-app-remix@2.6.1
├── @shopify/shopify-app-session-storage-prisma@4.0.1
  - Node version: v21.6.2
  - Operating system: MacOS Ventura 13.3.1
- [x] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

# Issue description

- Navigating to nested route causes authentication issue, where login form is displayed

## Expected behavior

Navigation should work without authentication issues 

## Actual behavior

Not able to navigate to nested routes

## Steps to reproduce the problem

- Fresh install of app on dev store, run `npm run dev`
- Create a nested route like this: app/routes/app.events.$id.jsx
- On the main `app/events` route, set up a link to that nested route, then navigate to the `app/events` route from the app.js `<ui-nav-menu>` navigation. This page will load with no issues.
- Navigate to a nested route with `useNavigate` or `Link` component and you are presented with a login component: 
<img width="1190" alt="image" src="https://github.com/Shopify/shopify-app-template-remix/assets/132302189/e58531c0-fa3e-4970-9670-199b01dd3e78">
- I tried both Remix useNavigate hook and Polaris Link component, both have the same result:

```javascript
const navigate = useNavigate();
//...
<FullCalendar
  eventClick={clickEvent => {
    navigate(`/app/events/${clickEvent.event.id}`);
  }}
/>
```
```javascript
{events.map(({ id, title }) => (
  <Link key={id} url={`/app/events/${id}`}>
    {title} - {id}
  </Link>
))}
```
When the login component shows, the debug log shows the shop as null (but logging out `session.shop` from `authenticate.admin(request)` shows the correct shop)
```
[shopify-app/DEBUG] Missing or invalid shop, redirecting to login path | {shop: null}
```
- Now refresh the page and try to navigate. This time the current page just refreshes, no login component, and the logs show: 
```
15:16:08 │ remix      │ [shopify-app/DEBUG] Request is valid, loaded session from session token | {shop: 
xxxxxxxxxxxx.myshopify.com, isOnline: false}
```

- Finally, enter the target url into the browser directly: `/app/events/clteyhjex0001ne5cyui3zthw` and notice that the the page loads correctly, no login component shown. 

## Debug logs

```
15:26:10 │ remix      │ [shopify-app/INFO] Authenticating admin request
15:26:10 │ remix      │ [shopify-app/DEBUG] Attempting to authenticate session token | {sessionToken: 
{"header":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczpcL1wvdnctc2tpLXRyaXAtYm9va2luZy5teXNob3BpZnkuY29
tXC9hZG1pbiIsImRlc3QiOiJodHRwczpcL1wvdnctc2tpLXRyaXAtYm9va2luZy5teXNob3BpZnkuY29tIiwiYXVkIjoiY2UwYWQ0MzFiZWM0MmY1YT
A2ODQ1OGQ1OTJjYTk2YjYiLCJzdWIiOiI3MzgwODkwNDI4OCIsImV4cCI6MTcwOTk0MDQzMCwibmJmIjoxNzA5OTQwMzcwLCJpYXQiOjE3MDk5NDAzN
zAsImp0aSI6IjhlNTcxNWE5LWVhYjYtNDE5ZC05MmVkLWRlN2JiYTA5NzhiZCIsInNpZCI6IjliMWM0ZTg2LTIzYjEtNGFhYS1hMDAxLTAyMTRjMzdj
ZDdmMSIsInNpZyI6IjlmOThjOGI4Mjg3Yjc5YzU4ZGI2ZDFmMGMzNGJhMzJiYjhmZDA3NTI0OWFiOWJiYTdiMDBkOGFjNTFjNjI1ZmYifQ.ysxi29bZ
ZN3J_tcHfHDx86oBIvilmdOpDj52yq4vSlc","search":null}}
15:26:10 │ remix      │ [shopify-app/DEBUG] Validating session token
15:26:10 │ remix      │ [shopify-app/DEBUG] Session token is valid | {payload: 
{"iss":"https://xxxxxxxxxxxxxxx.myshopify.com/admin","dest":"https://xxxxxxxxxxxxxxx.myshopify.com","aud":"
ce0ad431bec42f5a068458d592ca96b6","sub":"73808904288","exp":1709940430,"nbf":1709940370,"iat":1709940370,"jti":"8e5
715a9-eab6-419d-92ed-de7bba0978bd","sid":"9b1c4e86-23b1-4aaa-a001-0214c37cd7f1","sig":"9f98c8b8287b79c58db6d1f0c34b
a32bb8fd075249ab9bba7b00d8ac51c625ff"}}
15:26:10 │ remix      │ [shopify-app/DEBUG] Session token is valid | {shop: xxxxxxxxxxxxxxx.myshopify.com, 
payload: [object Object]}
15:26:10 │ remix      │ [shopify-app/DEBUG] Loading session from storage | {sessionId: 
offline_xxxxxxxxxxxxxxx.myshopify.com}
15:26:10 │ remix      │ [shopify-app/DEBUG] Request is valid, loaded session from session token | {shop: 
xxxxxxxxxxxxxxx.myshopify.com, isOnline: false}
15:26:10 │ remix      │ {
15:26:10 │ remix      │   auth: {
15:26:10 │ remix      │     billing: {
15:26:10 │ remix      │       require: [AsyncFunction: requireBilling],
15:26:10 │ remix      │       check: [AsyncFunction: checkBilling],
15:26:10 │ remix      │       request: [AsyncFunction: requestBilling],
15:26:10 │ remix      │       cancel: [AsyncFunction: cancelBilling]
15:26:10 │ remix      │     },
15:26:10 │ remix      │     session: Session {
15:26:10 │ remix      │       id: 'offline_xxxxxxxxxxxxxxx.myshopify.com',
15:26:10 │ remix      │       shop: 'xxxxxxxxxxxxxxx.myshopify.com',
15:26:10 │ remix      │       state: '',
15:26:10 │ remix      │       isOnline: false,
15:26:10 │ remix      │       scope: 'write_products',
15:26:10 │ remix      │       accessToken: 'shpua_dbd1b32febf974f02b163fb168c6c46d'
15:26:10 │ remix      │     },
15:26:10 │ remix      │     cors: [Function: ensureCORSHeaders],
15:26:10 │ remix      │     sessionToken: {
15:26:10 │ remix      │       iss: 'https://xxxxxxxxxxxxxxx.myshopify.com/admin',
15:26:10 │ remix      │       dest: 'https://xxxxxxxxxxxxxxx.myshopify.com',
15:26:10 │ remix      │       aud: 'ce0ad431bec42f5a068458d592ca96b6',
15:26:10 │ remix      │       sub: '73808904288',
15:26:10 │ remix      │       exp: 1709940430,
15:26:10 │ remix      │       nbf: 1709940370,
15:26:10 │ remix      │       iat: 1709940370,
15:26:10 │ remix      │       jti: '8e5715a9-eab6-419d-92ed-de7bba0978bd',
15:26:10 │ remix      │       sid: '9b1c4e86-23b1-4aaa-a001-0214c37cd7f1',
15:26:10 │ remix      │       sig: '9f98c8b8287b79c58db6d1f0c34ba32bb8fd075249ab9bba7b00d8ac51c625ff'
15:26:10 │ remix      │     },
15:26:10 │ remix      │     redirect: [Function: redirect]
15:26:10 │ remix      │   }
15:26:10 │ remix      │ }
15:26:10 │ remix      │ [shopify-app/DEBUG] Missing or invalid shop, redirecting to login path | {shop: null}
15:26:10 │ remix      │ [shopify-app/DEBUG] Missing or invalid shop, redirecting to login path | {shop: null}
```

**Comment by patrickDouglas** [comment]
I am also getting the same issue. I diffed the `request` objects from a working-as-expected route AND a non-working one.  In the request object coming into the non-working nested route's, I noticed...
```
'sec-fetch-dest': 'iframe',
'sec-fetch-mode': 'navigate',
```
compared to a working nested route
```
'sec-fetch-dest': 'empty',
'sec-fetch-mode': 'cors',
```
or a working route coming from the ui-menu link
```
'sec-fetch-dest': 'empty',
'sec-fetch-mode': 'same-origin',
```

**Comment by paulomarg** [comment]
Hey folks, thanks for raising this. The only case in the package where we look at the `sec-fetch-dest` header is when we start the OAuth auth code flow, which never happens for apps using the new authentication strategy. I'm not sure if that header will have any impact here.

If this is related to Vite's HMR, it could be that it is adding some code to trigger refreshes before App Bridge adds its own overrides - we'd throw responses in some of those cases, which would trigger the `Handling response` page. It doesn't usually get rendered because App Bridge would catch those errors, but maybe something is preventing that from happening in the Vite setup.

Also, one more thing to keep in mind: does this only happen after a few minutes, if you don't manually do a full refresh? It could be that the session token is expiring and triggering a failure.

**Comment by nboliver-ventureweb** [comment]
Hi @paulomarg Some more context here: I had a good streak where the issue was not happening at all yesterday, but I also did not stop the dev process once. This morning I stopped it, and now after running `npm run dev` again, the issue is back. There have been no code changes. 
Also, it does not happen after a few minutes, it's right away. Here is the sequence:
- run `npm run dev` 
- navigate from app index to other top-level route. no issues. 
- navigate from there to nested route. login screen shows. 
- refresh page and try to navigate. nothing happens, no login screen, no navigation
- enter target URL into browser directly. target page loads fine.

Here are the headers from a request that showed the login screen, if that helps at all. 
<img width="636" alt="image" src="https://github.com/Shopify/shopify-app-template-remix/assets/132302189/7bd90c1f-8920-41c9-92ba-6e22b842c304">

**Comment by Kashuab** [comment]
Ran into this same issue when migrating to Remix Vite. Full page navigations seem to work just fine (i.e. navigating from the sidebar), but when client-side navigation takes place (link rendered via React within the embedded frame) the login form seems to show up every time.

**Comment by Kashuab** [comment]
This is interesting. My `routes/app.tsx` had some old code:

```tsx
import polarisStyles from '@shopify/polaris/build/esm/styles.css';
export const links = () => [{ rel: 'stylesheet', href: polarisStyles }];
```

Removing these and replacing with the new template's import solved the problem:

```ts
import '@shopify/polaris/build/esm/styles.css';
```

**Comment by nboliver-ventureweb** [comment]
@Kashuab interesting - I don't have any old imports and the app was created recently, after the template switched to Vite. But it does seem like perhaps there is something possibly related to Vite that's causing this? There's a few other open issues that also report the login screen showing up, like https://github.com/Shopify/shopify-app-template-remix/issues/617 
cc @paulomarg

**Comment by huykon** [comment]
still have same issue : https://community.shopify.com/c/shopify-cli-and-tools/how-to-redirect-user-on-client-side-with-remix-template-shopify/m-p/2472627

**Comment by benvogler** [comment]
I was having this issue when using `redirect` from `@remix-run/react` in a loader. Using `useNavigate` in the client code  fixed this for me.

**Comment by nboliver-ventureweb** [comment]
@benvogler Have you tried using the `redirect` returned from `authenticate.admin`?
https://github.com/Shopify/shopify-app-template-remix?tab=readme-ov-file#navigatingredirecting-breaks-an-embedded-app

**Comment by benvogler** [comment]
> [@benvogler](https://github.com/benvogler) Have you tried using the `redirect` returned from `authenticate.admin`? https://github.com/Shopify/shopify-app-template-remix?tab=readme-ov-file#navigatingredirecting-breaks-an-embedded-app

Yep that fixed it, thank you!
