### ISSUE TITLE
Lack of userId Support in Shopify Session Class

### ISSUE THREAD

**Issue by hamzasgd** [Shopify/shopify-app-template-remix#602]
Issue with userId not being retrieved or updated in Session schema via Prisma Adapter

**Comment by hamzasgd** [comment]
@henrytao-me, could you also review the Prisma session where there is a BigInt userId that is neither updateable nor accessible through the session adapter?

**Comment by lizkenyon** [comment]
Hi there 👋 
The userID is accessible on the session under `session.onlineAccessInfo.associated_user.id`. Please let me know if that resolves the issue you are having.

<img width="1695" alt="user_id" src="https://github.com/Shopify/shopify-app-template-remix/assets/23265671/6e2afeb5-39a0-4502-914d-5f5efe497e57">

**Comment by hamzasgd** [comment]
Hi @lizkenyon, thank you for your reply, but I am referring to this userId.
![userId](https://github.com/Shopify/shopify-app-template-remix/assets/12862136/b5885829-1047-40ec-acfe-ba313c984e79)

The "associated_user" feature is not what I need. It is only available for online sessions, but I am using offline sessions. I want to associate my own user so that every time I use "admin.authenticate," the userId will be included in the session without needing an extra database query.

**Comment by lizkenyon** [comment]
Hi there 👋 

That UserID you are referencing in the schema is the `session.onlineAccessInfo.associated_user.id`. That is the User ID of the online access token.
You can store your own data in the database, but it will be then up to you to determine how to save and access it.

**Comment by hamzasgd** [comment]
@lizkenyon I was trying to find a way to return the userId as a session parameter so that I don't have to make an additional call to the session to retrieve it.

**Comment by lizkenyon** [comment]
You can fork the shopify-app-prisma-session-storage adapter if those are modifications you wish to make! Unfortunately the use of the userID field that you are looking for is different than intended, so you would need to make modifications.

**Comment by hamzasgd** [comment]
Okay thanks
