### ISSUE TITLE
"Bring your own server"

### ISSUE THREAD

**Issue by david-256** [Shopify/shopify-app-template-remix#614]
# What

According to the  [Remix docs](https://remix.run/docs/en/main/start/quickstart#bring-your-own-server), it is possible in Remix to use my own HTTP server.

When I use the provided example [1] in my Shopify Remix app template, I receive the error `Invalid appUrl provided. Please provide a valid URL`.

I assume this happens because `shopify app dev` is not called to create the Cloudflare tunnel and set the app URL (and other required other environment variables).

It would be good to have a server.js file for this template, that works correctly in the development environment.

# My use case

I want to create cronjobs as soon as the app is started. When the code to create the cronjobs is located in `entry.server.tsx`, then the cronjobs are only created once the app is opened in the Shopify admin. 

If there is a better place for code that creates the cronjobs, please tell me about it. 

[1]
```js
import { createRequestHandler } from "@remix-run/express";
import express from "express";

const viteDevServer =
  process.env.NODE_ENV === "production"
    ? null
    : await import("vite").then((vite) =>
        vite.createServer({
          server: { middlewareMode: true },
        })
      );

const app = express();
app.use(
  viteDevServer
    ? viteDevServer.middlewares
    : express.static("build/client")
);

const build = viteDevServer
  ? () =>
      viteDevServer.ssrLoadModule(
        "virtual:remix/server-build"
      )
  : await import("./build/server/index.js");

app.all("*", createRequestHandler({ build }));

app.listen(3000, () => {
  console.log("App listening on http://localhost:3000");
});

```

**Comment by ankur6971** [comment]
I have successfully installed the remix app onto an AWS EFS + Fargate cluster. Though there were a couple of adjustments here and there, the application is working without errors.

**Comment by lizkenyon** [comment]
Hi there 👋 
@david-256 

We recently added a [page](https://github.com/Shopify/shopify-app-template-remix/wiki/Use-a-custom-server) in our wiki explaining a potential set up for using a custom server!

Please give it a try, and let us know if you run into any more issues.

**Comment by lizkenyon** [comment]
Hey @david-256 

Did you set up the [HMR to use localhost](https://github.com/Shopify/shopify-app-template-remix/wiki/Use-a-custom-server#update-the-viteconfigjs), you do this by updating the setting in the `viteconfig.js`

This is a currently workaround because we were having issues running the Vite HMR server behind a proxy while Vite is in middleware mode. We will update the guide if we find a better solution, but for the time being using localhost instead of the tunnel will work on Chrome.

**Comment by dizzyjaguar** [comment]
@lizkenyon I followed the linked wiki page, and I'm getting the server to work but HMR _is not_ working. Any guesses?
I have
```
const hmrConfig = {
  protocol: "ws",
  host: "localhost",
  port: 64999,
  clientPort: 64999,
};

export default defineConfig({
  server: {
    port: Number(process.env.PORT || 3000),
    hmr: hmrConfig,
........rest of config
```
