### ISSUE TITLE
Store Remix based App Bridge apps, on Shopify, to improve the client demo experience

### ISSUE THREAD

**Issue by charlesr1971** [Shopify/shopify-app-template-remix#626]
When a _Remix_ based app, is embedded into the _Shopify Admin_, using _App Bridge_, in development, in order to keep the app displayed, it is neccessary to keep the _Ngrok/Cloudflare_ tunnel, open. 

If I want to show a client, the progress of an app, I either have to keep the tunnel open, or deploy the app to a remote host. The latter is impractical, during the development phase. 
Deploying an app to a remote server, for every little change that a client might require, is frustrating. 
On the other hand, the _App Bridge_ tunnel is quite fragile & often disconnects. This isn’t ideal when trying to project a level of professionalism to a client, who wishes to view changes made to an app. 

**So what is the answer to this problem?**

How about, keeping the app code files/assets & DB, on the Shopify server, during the development phase.  This would allow the app to display correctly, 24/7. 
I am not sure whether an app goes through a _build_, after an HMR hot reload? But, maybe this is the answer, to keep the codebase footprint, to a minimum, whilst it is stored on the Shopify server, during the development phase. 

Having a reliable way to demo an app, in development, is extremely important, for generating trust between a Dev community and its technical ecosystem. 
Please can someone address this issue, because for some of us, this is a deal breaker, when trying to decide, which e-commerce platform, is deserving of our attention. 🙂

**Comment by lizkenyon** [comment]
Hi there 👋 

We are always looking to review and improve our development experiences. I will share your feedback with the team.

In the meantime I might suggest looking into some of the hosting services that make it quite easy to deploy to a cloud service. Heroku and Vercel are popular choices in the app developer community. These can be configured to deploy when pushing to a main branch.

**Comment by charlesr1971** [comment]
@lizkenyon Thanks for the response. 

Yes. I am using **fly.io** for my production hosting requirements, however, during the prototyping stage, _App Bridge_ & _HMR_, is vital. 

It really would be great to have some kind of persistence, in development, so that I can review & fix code, in front of my client. 

Running:

`fly deploy `

Everytime, I need to make small changes, just isn’t practical. 

Thank you, for your understanding 🙂
