### ISSUE TITLE
Add docs and how to use with Drizzle instead of Prisma

### ISSUE THREAD

**Issue by blanklob** [Shopify/shopify-app-template-remix#635]
# Issue summary

Before opening this issue, I have:

- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

We need an example Docker file and section in Readme on how to switch from Prisma to Drizzle.

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

## Steps to reproduce the problem

1.
1.
1.

## Debug logs

```
// Paste any relevant logs here
```

**Comment by itsanishjain** [comment]
> Hi! There should be no special code needed to replace session storages, since they're built to plug in and out of the app without affecting the code itself.
> 
> I believe it would be enough to:
> 
> 1. Replace the `SessionStorage` class you pass in [shopify.server](https://github.com/Shopify/shopify-app-template-remix/blob/main/app/shopify.server.ts#L19), following the [Drizzle package docs
>    ](https://github.com/Shopify/shopify-app-js/tree/main/packages/shopify-app-session-storage-drizzle#readme)
> 2. Change your [`shopify.web.toml`](https://github.com/Shopify/shopify-app-template-remix/blob/main/shopify.web.toml#L6) file to not run prisma commands when running with the CLI
> 3. Change [your `setup` script](https://github.com/Shopify/shopify-app-template-remix/blob/main/package.json#L14) to run any migrations you need
> 
> Please let me know if you have any issues doing that! Maybe we can look into adding some docs about replacing session storages in general if the process doesn't feel straightforward.

Hey now I am getting error with billing

I get this error when I run

```
export const loader = async ({ request }: LoaderFunctionArgs) => {
  const { session, billing, sessionToken } = await authenticate.admin(request);

  try {
    const bill = await billing.check({
      plans: [MONTHLY_PLAN],
      isTest: true,
    });
    return json({ message: "success", bill });
  } catch (error) {
    console.log(error);
    return null;
  }
};
```


```
Response {
15:43:29 │ remix            │   status: 401,
15:43:29 │ remix            │   statusText: 'Unauthorized',
15:43:29 │ remix            │   headers: Headers {
15:43:29 │ remix            │     'x-shopify-api-request-failure-reauthorize-url':
                           'https://superb-brussels-jr-claimed.trycloudflare.com/auth?shop=quickstart-42d2cafa.myshopify.com'
15:43:29 │ remix            │   },
15:43:29 │ remix            │   body: null,
15:43:29 │ remix            │   bodyUsed: false,
15:43:29 │ remix            │   ok: false,
15:43:29 │ remix            │   redirected: false,
15:43:29 │ remix            │   type: 'default',
15:43:29 │ remix            │   url: ''
15:43:29 │ remix            │ }
```
