### ISSUE TITLE
A way to customize the CSP header

### ISSUE THREAD

**Issue by Drodevbar** [Shopify/shopify-app-template-remix#648]
# Issue summary

Shopify has some default logic in place that configures the CSP header under the hood (as far as I know it's done by `addDocumentResponseHeaders` of shopify object created via `shopifyApp` function of `@shopify/shopify-app-remix/server`). When the app is configured as an embedded one, it sets the `frame-ancestors` directive of the CSP header. This is great, but the thing is that when I would like to make my policy stricter and adjust the CSP header slightly, the default one gets overridden. I could try to recreate the overridden logic, but that would be nice to be able to reuse it (especially since it contains some shop name sanitization logic in place which is not exposed to the API consumer). 

Side note: I've tried using `createContentSecurityPolicy` of `@shopify/hydrogen`, but I don't think it is the way since not every app may be interested in using hydrogen. I also found it problematic to edit a directive by default specified by `createContentSecurityPolicy` function - an error was being thrown in my case when I wanted to make a specific directive stricter.

## Expected behavior

`shopifyApp` object enables CSP header configuration but lets you preserve the default `frame-ancestors` directive.

## Actual behavior

What actually happens?

I don't see a way to modify the CSP header value without overriding the default one.

## Debug logs

Before opening this issue, I have:

- [x] Upgraded to the latest version of the `@shopify` packages
  - Affected `@shopify/shopify-*` package and version:
  - Node version:
  - Operating system:
- [x] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

**Comment by paulomarg** [comment]
Hey, thanks for raising this, I think that's a fair ask. Just to be sure I fully understand the issue: we call that function to set the headers in `entry.server`, so you can [change that `responseHeaders` instance](https://github.com/Shopify/shopify-app-template-remix/blob/main/app/entry.server.tsx#L19) however you want before returning.

Would something like this not work for you?

```ts
export default async function handleRequest(
  request: Request,
  responseStatusCode: number,
  responseHeaders: Headers,
  remixContext: EntryContext
) {
  addDocumentResponseHeaders(request, responseHeaders);
  const header = responseHeaders.get('Content-Security-Policy');

  responseHeaders.set('Content-Security-Policy', `${header} my-directive; my-other-directive;`);
  ...
```
