### ISSUE TITLE
Question: What is this page for?

### ISSUE THREAD

**Issue by tvthatsme** [Shopify/shopify-app-template-remix#650]
Not a bug, but a question. Maybe the bug can be lack of documentation 😃 

What is this route for? `app/routes/_index/route.tsx` Is this for the App Listing page or something else? Looking through the Shopify docs and this history from this repo, I can't figure out what it should be used for. Thanks!

**Comment by tvthatsme** [comment]
Okay, thanks! So it that the same things as an app listing page? That is described [here](https://shopify.dev/docs/apps/store/requirements#example-app-listing) in the docs.

**Comment by lizkenyon** [comment]
No. You will create the App Listing page in your [Partner Dashboard.](https://www.shopify.com/partners) Once you select your App Distribution to be public (Apps > Your App > Choose Distribution)  you will be given the option to create your app listing.
