### ISSUE TITLE
App can't be installed in production env to a new store after upgrading it to Shopify API version 2024-04

### ISSUE THREAD

**Issue by sameerabit** [Shopify/shopify-app-template-remix#683]
# Issue summary

Before opening this issue, I have:

- [ ] Upgraded to the latest version of the `@shopify/shopify-app-remix` packages
  - Affected `@shopify/shopify-*` package and version:
  - Node version: v21.6.2
  - Operating system: node:20-alpine
- [ ] Try to install the app in a store
- [ ] app-bridge.js:1 uncaught error: app bridge next: missing required configuration fields: apikey at app-bridge.js:1:41042

## Expected behavior

App can be installed in a store without an issue.

## Actual behavior

App returns to an error page after clicking install button.

## Debug logs

```
(app-bridge.js:1 uncaught error: app bridge next: missing required configuration fields: apikey at app-bridge.js:1:41042)
```

**Comment by sameerabit** [comment]
> Hi there 👋
> 
> Could you provide a few more details regarding your issue?
> 
> * Is this the first time deploying your application? Or is it currently deployed to a production environment and is currently installed on stores, but installing it on new stores is throwing this error?
> * What are the versions and shopify packages that you are using?
> * Have you confirmed that the environment variable `SHOPIFY_API_KEY ` is set in your production environment?

Hi, This app is in production. Yes, We have clients who are using this. We can't install it to new clients because of this problem. 

Here are the versions that we are using,

    "@shopify/app": "^3.57.0",
    "@shopify/cli": "^3.57.0",
    "@shopify/polaris": "^12.15.0",
    "@shopify/polaris-icons": "^8.2.0",
    "@shopify/shopify-api": "^9.7.2",
    "@shopify/shopify-app-remix": "^2.8.1",
    "@shopify/shopify-app-session-storage-prisma": "^4.0.4",

Yes, It is a working app in prod.

**Comment by sameerabit** [comment]
The issue arose because of a try-catch block we used in app.tsx loader. The problem has been resolved after its removal. Thanks for the support.

**Comment by iffikhan30** [comment]
Hello,
You can add your index file like this
<script src="https://cdn.shopify.com/shopifycloud/app-bridge.js?apiKey=<--API_KEY-->"></script>
