### ISSUE TITLE
Error: 500: "INTERNAL_SERVER_ERROR - This Serverless Function has crashed" during deployment to Vercel host

### ISSUE THREAD

**Issue by LeviN094** [Shopify/shopify-app-template-remix#689]
Have a nice day.

# NOTE

1. I have changed the Adapter to: import "@shopify/shopify-app-remix/adapters/vercel";
2. Changed the database from SQLite to PostgreSQL.
3. Environment variables on Vercel:
- SHOPIFY_API_KEY
- SHOPIFY_WISHLIST_ICON_ID
- SHOPIFY_API_SECRET
- POSTGRES_URL
- POSTGRES_PRISMA_URL
- POSTGRES_URL_NO_SSL
- POSTGRES_URL_NON_POOLING
- POSTGRES_USER
- POSTGRES_HOST
- POSTGRES_PASSWORD
- POSTGRES_DATABASE

## Debug logs
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/@shopify/polaris/locales/en.json' imported from /var/task/node_modules/@shopify/shopify-app-remix/dist/esm/react/components/AppProvider/AppProvider.mjs
at new NodeError (node:internal/errors:405:5)
at finalizeResolution (node:internal/modules/esm/resolve:332:11)
at moduleResolve (node:internal/modules/esm/resolve:1029:10)
at moduleResolveWithNodePath (node:internal/modules/esm/resolve:876:12)
at defaultResolve (node:internal/modules/esm/resolve:1242:79)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:404:12)
at ModuleLoader.resolve (node:internal/modules/esm/loader:373:25)
at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:250:38)
at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
at link (node:internal/modules/esm/module_job:75:36) {
url: 'file:///var/task/node_modules/@shopify/polaris/locales/en.json',
code: 'ERR_MODULE_NOT_FOUND'
}
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
INIT_REPORT Init Duration: 386.22 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/@shopify/polaris/locales/en.json' imported from /var/task/node_modules/@shopify/shopify-app-remix/dist/esm/react/components/AppProvider/AppProvider.mjs
at new NodeError (node:internal/errors:405:5)
at finalizeResolution (node:internal/modules/esm/resolve:332:11)
at moduleResolve (node:internal/modules/esm/resolve:1029:10)
at moduleResolveWithNodePath (node:internal/modules/esm/resolve:876:12)
at defaultResolve (node:internal/modules/esm/resolve:1242:79)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:404:12)
at ModuleLoader.resolve (node:internal/modules/esm/loader:373:25)
at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:250:38)
at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
at link (node:internal/modules/esm/module_job:75:36) {
url: 'file:///var/task/node_modules/@shopify/polaris/locales/en.json',
code: 'ERR_MODULE_NOT_FOUND'
}
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
INIT_REPORT Init Duration: 476.74 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
Unknown application error occurred

**Comment by cleverlight** [comment]
### Process to replicate issue

* `shopify app init` or `shopify app init --package-manager=pnpm` 
* Change `shopify.server.ts` as instructed in `README.md`
```diff
// shopify.server.ts
- import "@shopify/shopify-app-remix/adapters/node";
+ import "@shopify/shopify-app-remix/adapters/vercel";
```
* Upload repo to Vercel
* Look at failed deployment's logs

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/nodejs/simplest-replication/node_modules/@shopify/polaris/locales/en.json' imported from /var/task/nodejs/simplest-replication/node_modules/.pnpm/@shopify+shopify-app-remix@2.8.2_@remix-run+node@2.9.1_@remix-run+react@2.9.1_@shopify+polari_ry6l4fmsukwl5u35magougpts4/node_modules/@shopify/shopify-app-remix/dist/esm/react/components/AppProvider/AppProvider.mjs
at new NodeError (node:internal/errors:405:5)
at finalizeResolution (node:internal/modules/esm/resolve:332:11)
at moduleResolve (node:internal/modules/esm/resolve:1029:10)
at moduleResolveWithNodePath (node:internal/modules/esm/resolve:876:12)
at defaultResolve (node:internal/modules/esm/resolve:1242:79)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:404:12)
at ModuleLoader.resolve (node:internal/modules/esm/loader:373:25)
at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:250:38)
at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
at link (node:internal/modules/esm/module_job:75:36) {
url: 'file:///var/task/nodejs/simplest-replication/node_modules/@shopify/polaris/locales/en.json',
code: 'ERR_MODULE_NOT_FOUND'
}
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
INIT_REPORT Init Duration: 370.84 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
Unknown application error occurred
```

**Comment by lizkenyon** [comment]
Hi there 👋 

Could @cleverlight and @LeviN094 both confirm what versions of the the shopify packages you are using?

**Comment by LeviN094** [comment]
Yes, I was using the latest package at the time I deployed the project. Please check the packages in my package.json file.

"devDependencies": {
    "@remix-run/eslint-config": "^2.7.1",
    "@shopify/api-codegen-preset": "^0.0.7",
    "@shopify/app-bridge-types": "^0.0.11",
    "@types/eslint": "^8.40.0",
    "@types/node": "^20.6.3",
    "@types/react": "^18.2.31",
    "@types/react-dom": "^18.2.14",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.1.0",
    "prettier": "^3.2.4",
    "typescript": "^5.2.2",
    "vite": "^5.1.3"
  },

**Comment by LeviN094** [comment]
@lnehlsen Thanks for the information. Hopefully, we can resolve this issue soon.

**Comment by bijanv** [comment]
Also running into this issue, looking forward to a resolution soon 🙏

**Comment by alesiooooooo** [comment]
> got same issue, any workaround for it?

the same problem, I tried all combinations, but shopify/polaris package has  'json modules requires assert type json'

**Comment by lizkenyon** [comment]
Hey folks 👋 

After some investigation we believe we have determined what version of the packages seem to be causing this error. 

For your application to work we recommend pinning the packages to the following versions.
```
    "@shopify/shopify-api": "9.7.2",
    "@shopify/shopify-app-remix": "2.8.0",
    "@shopify/shopify-app-session-storage-prisma": "4.0.4",
```

In `shopify-app-remix` `v2.8.1` we started using ESM with an import assertion for the `@shopify/polaris/locales/en.json` .  It appears that the Vercel build does not handle this correctly, and then is not including this file in the build when it should. (You can test this by running `vercel build` locally, and looking in the `.vercel/output/functions/app.func/.vc-config.json`)

We are going to reach out to Vercel to get more information from them about this. But in the mean time we would recommend using the above package versions. 

It does appear Vercel does some caching in their build process, ensure your are rebuilding without the build cache when deploying these changes.

**Comment by LeviN094** [comment]
Thanks for your hard work @lizkenyon. My project is running after updating the version in package.json. Hopefully the issue will be fixed in the latest versions.

Best regards

**Comment by lizkenyon** [comment]
Hi folks 👋 

It looks like Vercel has [fixed this on their side](https://github.com/vercel/vercel/pull/11580) in the latest version. 
Please give this a try to see if it resolved the issue. 🙂

**Comment by cleverlight** [comment]
Hi @lizkenyon 

Alas not working for me.  I did a fresh build this morning using Shopfy CLI (@shopify/cli/3.60.1 linux-x64 node-v18.17.1).  I changed `shopify.server.ts` as described in the `README.md`:

```diff
// shopify.server.ts
- import "@shopify/shopify-app-remix/adapters/node";
+ import "@shopify/shopify-app-remix/adapters/vercel";
```

I deployed that to Vercel as `latest15-5` project.  Once deployed, I got the same error I've been seeing in the logs:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/nodejs/latest15-5/node_modules/@shopify/polaris/locales/en.json' imported from /var/task/nodejs/latest15-5/node_modules/.pnpm/@shopify+shopify-app-remix@2.8.2_@remix-run+node@2.9.2_@remix-run+react@2.9.2_@shopify+polari_sqgc7of7lid5n2hqfm2oigaasq/node_modules/@shopify/shopify-app-remix/dist/esm/react/components/AppProvider/AppProvider.mjs
at finalizeResolution (node:internal/modules/esm/resolve:269:11)
at moduleResolve (node:internal/modules/esm/resolve:937:10)
at moduleResolveWithNodePath (node:internal/modules/esm/resolve:1161:14)
at defaultResolve (node:internal/modules/esm/resolve:1204:79)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
at link (node:internal/modules/esm/module_job:86:36) {
code: 'ERR_MODULE_NOT_FOUND',
url: 'file:///var/task/nodejs/latest15-5/node_modules/@shopify/polaris/locales/en.json'
}
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
INIT_REPORT Init Duration: 524.84 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
```

Please accept my apologies if I've missed something when giving this a try.  Could you verify that you've followed the same process and got a different result please?

**Comment by lizkenyon** [comment]
Hi there 👋 

I was able to successfully get this to deploy using `"@shopify/shopify-app-remix": "2.8.1",` on Vercel. 🎉 

You need to ensure you are using the latest version of the Vercel CLI. Vercel CLI 34.1.14 is the version where they fixed this issue. To ensure this, I specified the specific Vercel CLI version the in environment variables for my project. 
VERCEL_CLI_VERSION = vercel@34.1.14

You can then verify in your deployment logs that the correct version is being used.

<img width="1052" alt="image" src="https://github.com/Shopify/shopify-app-template-remix/assets/23265671/82c8ba78-070b-49b1-b998-6b96900d931d">

You can test this locally by 

`npm i -g vercel@latest `
`vercel --version` (check for 34.1.14)
`vercel build`

Check that you see `node_modules/@shopify/polaris/locales/en.json` in `.vercel/output/functions/app.func/.vc-config.json`

**Comment by nickfthedev** [comment]
> Hi there 👋
> 
> I was able to successfully get this to deploy using `"@shopify/shopify-app-remix": "2.8.1",` on Vercel. 🎉
> 
> You need to ensure you are using the latest version of the Vercel CLI. Vercel CLI 34.1.14 is the version where they fixed this issue. To ensure this, I specified the specific Vercel CLI version the in environment variables for my project. VERCEL_CLI_VERSION = vercel@34.1.14
> 
> You can then verify in your deployment logs that the correct version is being used.
> 
> <img alt="image" width="1052" src="https://private-user-images.githubusercontent.com/23265671/330856440-82c8ba78-070b-49b1-b998-6b96900d931d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODk4MzIsIm5iZiI6MTcxNTc4OTUzMiwicGF0aCI6Ii8yMzI2NTY3MS8zMzA4NTY0NDAtODJjOGJhNzgtMDcwYi00OWIxLWI5OTgtNmI5NjkwMGQ5MzFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDE2MTIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZDg4ZDI3ZWFiMWEzZDA4YzQ3ZTc3YzZhMTM3ZjBhYmRkMGZiZGU5ZGUxMjNjMmI3YjQxNjI3ZTkyYjUyNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zpflIFKDWG4uFBkke2eZbzH4aiC--N4clZZWlHyg5Fs">
> You can test this locally by
> 
> `npm i -g vercel@latest ` `vercel --version` (check for 34.1.14) `vercel build`
> 
> Check that you see `node_modules/@shopify/polaris/locales/en.json` in `.vercel/output/functions/app.func/.vc-config.json`

This works! I didn't set the VERCEL_CLI_VERSION = vercel@34.1.14 as an enviroment variable. Thank you!

**Comment by lizkenyon** [comment]
Glad it worked! 

As it states in the deployment logs, using the env variable to set the  Vercel CLI version would stop you from getting updates in the future, so you shouldn't keep this set forever. 

I would suggest heading over to the Vercel docs for further details on updating the Vercel CLI, and updating your deployment processes.

**Comment by cleverlight** [comment]
Thank you for all your help on this so far @lizkenyon, but **please don't close this ticket**.  I don't believe it's fixed.  The current version installed by the current CLI is 2.8.2 (`"@shopify/shopify-app-remix": "^2.8.2"`), which does not work.

Thank you for coming up with a short-term hack, where we can revert to earlier version of `shopify-app-remix`, but future users following the README.md will be faced with the same problem.  Either the `shopify-cli` needs updating so that it does not install 2.8.2, or better, we need to fix forward:

* Nowhere in the README.md does it suggest that the `vercel` package needs to be installed.
* The `vercel` package is not included in the package.json generated by `shopify app init`
* There's no mention in the README.md that the Vercel CLI needs to be used to deploy to vercel.  Many people will have set up their GitHub repo in the Vercel.com UI and deploy using a `git push`.

While I'm delighted that there's signs of a solution here, especially for those who are already running in production, I feel like it's really valuable to fix the root of the problem, or at least something close to that (shopify-cli, or the README.md instrutions).

I think the first step is to update the `Process to replicate issue` on this ticket.  Please could you clarify exactly what you did to make it work?

## Original process to replicate issue
+ shopify app init or shopify app init --package-manager=pnpm
+ Change shopify.server.ts as instructed in README.md
```diff
// shopify.server.ts
- import "@shopify/shopify-app-remix/adapters/node";
+ import "@shopify/shopify-app-remix/adapters/vercel";
```
+ Upload repo to Vercel
+ Look at failed deployment's logs

## Additional steps??
+ modify `package.json` to `"@shopify/shopify-app-remix": "2.8.1"`
+ re-run `pnpm install`
+ set `VERCEL_CLI_VERSION = vercel@34.1.14` environment variable in .env
+ to test locally:
    + `npm i -g vercel@latest`
    + `vercel --version` (check for 34.1.14)
    + `vercel build`
+ push live
