### ISSUE TITLE
Internal server error: Unexpected identifier 'assert'

### ISSUE THREAD

**Issue by mufftee** [Shopify/shopify-app-template-remix#695]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the `@shopify` packages
  - Affected `@shopify/shopify-*` package and version:
  - Node version: 22.0.0
  - Operating system: MacOS
- [ ] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

Hey, somehow the template / boilerplate isnt working. After the `shopify app init` and starting the `shopify app dev` following error occours:

i did already updated to Shopify CLI: `3.59.1`

```
15:54:14 │ remix      │ 3:54:14 PM [vite] Internal server error: Unexpected identifier 'assert'
15:54:14 │ remix      │       at compileSourceTextModule (node:internal/modules/esm/utils:337:16)
15:54:14 │ remix      │       at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:166:18)
15:54:14 │ remix      │       at callTranslator (node:internal/modules/esm/loader:416:14)
15:54:14 │ remix      │       at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:422:30)
```

**Comment by mufftee** [comment]
`"@shopify/shopify-app-remix": "2.8.1",` and `"@shopify/shopify-app-remix": "2.8.2",` is causing this problem for me, for a friend of mine the version `"@shopify/shopify-app-remix": "^2.8.2",` works perfectly fine. My Workaround right now is to set `"@shopify/shopify-app-remix"` to `2.8.0`.

**Comment by paulomarg** [comment]
Hi, thanks for raising this. I was able to reproduce this by creating a new app using node 22, it seems like it's failing in that version only. Could you please try a different node version to see if you're still getting an error?

In the meantime, I'll start tracking this issue and we'll look into fixing it properly.

**Comment by aldenflatt-article** [comment]
I am also running into this issue using node 22.
I tried some of the above suggestions, but the only thing that seemed to work was downgrading to an older version of node I tested with node 20, since that's what's readily available in homebrew and it worked fine after that.

**Comment by lizkenyon** [comment]
Hi folks 👋 

At this time we would please ask you to use a node version < 22. W
e are working on getting the `shopify-app-remix` package working with the Node 22, and we'll update you when we do.

**Comment by lizkenyon** [comment]
Hi there 👋 

With the recent [release of the libraries](https://www.npmjs.com/package/@shopify/shopify-app-remix), we now support Node 22. 

Please update your package versions to the latest to start using it.

**Comment by jmanzo** [comment]
Hi guys, I fixed the issue just downgrading my node version to LTS (v~20) again. It seems like v22 is not a stable version yet. I recommend you use [nvm](https://github.com/nvm-sh/nvm/blob/master/README.md) for handling your node versions.
