### ISSUE TITLE
I get a permission error when I try to install it in my test store

### ISSUE THREAD

**Issue by BeycanDeveloper** [Shopify/shopify-app-template-remix#705]
I'm trying to install the repository below but I'm getting errors. I want to develop a custom payment gateway for Shopify.

https://github.com/Shopify/example-app--payments-app-template--remix

![image](https://github.com/Shopify/shopify-app-template-remix/assets/50718965/419cf6ce-3f6e-4d90-87a9-0deec7335469)

**Comment by lizkenyon** [comment]
Hi there 👋 

Please see [this post](https://community.shopify.com/c/extensions/version-couldn-t-be-created-app-access-validation-errors/m-p/2454131) from our developer forums.
