### ISSUE TITLE
[ERROR] Failed to resolve entry for package "crypto"

### ISSUE THREAD

**Issue by usamadar** [Shopify/shopify-app-template-remix#714]
I am simply doing `shopify app init`, then `npm insall` and `npm run dev`, the app runs i see this error in the console

`✘ [ERROR] Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]
00:20:53 │ remix      │ 
00:20:53 │ remix      │     node_modules/vite/node_modules/esbuild/lib/main.js:1374:21:
00:20:53 │ remix      │       1374 │         let result = await callback({
00:20:53 │ remix      │            ╵                      ^
00:20:53 │ remix      │ 
00:20:53 │ remix      │     at packageEntryFailure (file:///Users/u.dar/shopify-apps/test1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48264:17)
00:20:53 │ remix      │     at resolvePackageEntry (file:///Users/u.dar/shopify-apps/test1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48261:5)
00:20:53 │ remix      │     at tryNodeResolve (file:///Users/u.dar/shopify-apps/test1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48031:20)
00:20:53 │ remix      │     at Context.resolveId (file:///Users/u.dar/shopify-apps/test1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:47781:28)
00:20:53 │ remix      │     at Object.resolveId (file:///Users/u.dar/shopify-apps/test1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51063:64)
00:20:53 │ remix      │     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
00:20:53 │ remix      │     at async file:///Users/u.dar/shopify-apps/test1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:68310:21
00:20:53 │ remix      │     at async file:///Users/u.dar/shopify-apps/test1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48604:34
00:20:53 │ remix      │     at async requestCallbacks.on-resolve (/Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:1374:22)
00:20:53 │ remix      │     at async handleRequest (/Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:732:11)
00:20:53 │ remix      │ 
00:20:53 │ remix      │   This error came from the "onResolve" callback registered here:
00:20:53 │ remix      │ 
00:20:53 │ remix      │     node_modules/vite/node_modules/esbuild/lib/main.js:1293:20:
00:20:53 │ remix      │       1293 │       let promise = setup({
00:20:53 │ remix      │            ╵                     ^
00:20:53 │ remix      │ 
00:20:53 │ remix      │     at setup (file:///Users/u.dar/shopify-apps/test1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48584:19)
00:20:53 │ remix      │     at handlePlugins (/Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:1293:21)
00:20:53 │ remix      │     at buildOrContextImpl (/Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:979:5)
00:20:53 │ remix      │     at Object.buildOrContext (/Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:788:5)
00:20:53 │ remix      │     at /Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:2224:68
00:20:53 │ remix      │     at new Promise (<anonymous>)
00:20:53 │ remix      │     at Object.context (/Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:2224:27)
00:20:53 │ remix      │     at Object.context (/Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:2048:58)
00:20:53 │ remix      │     at prepareEsbuildOptimizerRun (file:///Users/u.dar/shopify-apps/test1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:52792:35)
00:20:53 │ remix      │ 
00:20:53 │ remix      │   The plugin "vite:dep-pre-bundle" was triggered by this import
00:20:53 │ remix      │ 
00:20:53 │ remix      │     node_modules/@shopify/shopify-app-remix/dist/esm/server/adapters/node/index.mjs:1:19:
00:20:53 │ remix      │       1 │ import crypto from 'crypto';
00:20:53 │ remix      │         ╵                    ~~~~~~~~
00:20:53 │ remix      │ 
00:20:53 │ remix      │ ✘ [ERROR] Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]
00:20:53 │ remix      │ 
00:20:53 │ remix      │     node_modules/vite/node_modules/esbuild/lib/main.js:1374:21:
00:20:53 │ remix      │       1374 │         let result = await callback({
00:20:53 │ remix      │            ╵                      ^
00:20:53 │ remix      │ 
00:20:53 │ remix      │     at packageEntryFailure (file:///Users/u.dar/shopify-apps/test1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48264:17)
00:20:53 │ remix      │     at resolvePackageEntry (file:///Users/u.dar/shopify-apps/test1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48261:5)
00:20:53 │ remix      │     at tryNodeResolve (file:///Users/u.dar/shopify-apps/test1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48031:20)
00:20:53 │ remix      │     at Context.resolveId (file:///Users/u.dar/shopify-apps/test1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:47781:28)
00:20:53 │ remix      │     at Object.resolveId (file:///Users/u.dar/shopify-apps/test1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51063:64)
00:20:53 │ remix      │     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
00:20:53 │ remix      │     at async file:///Users/u.dar/shopify-apps/test1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:68310:21
00:20:53 │ remix      │     at async file:///Users/u.dar/shopify-apps/test1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48604:34
00:20:53 │ remix      │     at async requestCallbacks.on-resolve (/Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:1374:22)
00:20:53 │ remix      │     at async handleRequest (/Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:732:11)
00:20:53 │ remix      │ 
00:20:53 │ remix      │   This error came from the "onResolve" callback registered here:
00:20:53 │ remix      │ 
00:20:53 │ remix      │     node_modules/vite/node_modules/esbuild/lib/main.js:1293:20:
00:20:53 │ remix      │       1293 │       let promise = setup({
00:20:53 │ remix      │            ╵                     ^
00:20:53 │ remix      │ 
00:20:53 │ remix      │     at setup (file:///Users/u.dar/shopify-apps/test1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:48584:19)
00:20:53 │ remix      │     at handlePlugins (/Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:1293:21)
00:20:53 │ remix      │     at buildOrContextImpl (/Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:979:5)
00:20:53 │ remix      │     at Object.buildOrContext (/Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:788:5)
00:20:53 │ remix      │     at /Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:2224:68
00:20:53 │ remix      │     at new Promise (<anonymous>)
00:20:53 │ remix      │     at Object.context (/Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:2224:27)
00:20:53 │ remix      │     at Object.context (/Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:2048:58)
00:20:53 │ remix      │     at prepareEsbuildOptimizerRun (file:///Users/u.dar/shopify-apps/test1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:52792:35)
00:20:53 │ remix      │ 
00:20:53 │ remix      │   The plugin "vite:dep-pre-bundle" was triggered by this import
00:20:53 │ remix      │ 
00:20:53 │ remix      │     node_modules/cookie-signature/index.js:5:21:
00:20:53 │ remix      │       5 │ var crypto = require('crypto');
00:20:53 │ remix      │         ╵                      ~~~~~~~~
00:20:53 │ remix      │ 
00:20:54 │ remix      │ 00:20:54 [vite] error while updating dependencies:
00:20:54 │ remix      │ Error: Build failed with 2 errors:
00:20:54 │ remix      │ node_modules/vite/node_modules/esbuild/lib/main.js:1374:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its 
package.json.
00:20:54 │ remix      │ node_modules/vite/node_modules/esbuild/lib/main.js:1374:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its 
package.json.
00:20:54 │ remix      │     at failureErrorWithLog (/Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:1651:15)
00:20:54 │ remix      │     at /Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:1059:25
00:20:54 │ remix      │     at /Users/u.dar/shopify-apps/test1/node_modules/vite/node_modules/esbuild/lib/main.js:1527:9
00:20:54 │ remix      │     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
`

**Comment by felixmpaulus** [comment]
Same problem. Running

`Now using node v20.14.0 (npm v10.7.0)`

with npm as the package manager.

**Comment by saamde** [comment]
I'm having a similar issue when building with the Shopify CLI and npm, I can no longer build my app "shopify app build" fails with this error:
`╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  Build failed with 1 error:                                                  │
│  node_modules/@shopify/shopify-app-remix/dist/esm/server/adapters/node/inde  │
│  x.mjs:1:19: ERROR: Could not resolve "crypto"                               │
│                                                                              │
│  To investigate the issue, examine this stack trace:                         │
│    at node_modules/                                                          │
│    (shopify/shopify-app-remix/dist/esm/server/adapters/node/index.mjs:1)     │
│    at failureErrorWithLog                                                    │
│    (../../../../../home/derek/.nvm/versions/node/v20.16.0/lib/node_modules/  │
│    @shopify/cli/node_modules/esbuild/lib/main.js:1650)                       │
│    at (../../../../../home/derek/.nvm/versions/node/v20.16.0/lib/node_modul  │
│    es/@shopify/cli/node_modules/esbuild/lib/main.js:1058)                    │
│    at (../../../../../home/derek/.nvm/versions/node/v20.16.0/lib/node_modul  │
│    es/@shopify/cli/node_modules/esbuild/lib/main.js:1003)                    │
│    at buildResponseToResult                                                  │
│    (../../../../../home/derek/.nvm/versions/node/v20.16.0/lib/node_modules/  │
│    @shopify/cli/node_modules/esbuild/lib/main.js:1056)                       │
│    at (../../../../../home/derek/.nvm/versions/node/v20.16.0/lib/node_modul  │
│    es/@shopify/cli/node_modules/esbuild/lib/main.js:1085)                    │
│    at <computed> (../../../../../home/derek/.nvm/versions/node/v20.16.0/lib  │
│    /node_modules/@shopify/cli/node_modules/esbuild/lib/main.js:703)          │
│    at handleIncomingPacket                                                   │
│    (../../../../../home/derek/.nvm/versions/node/v20.16.0/lib/node_modules/  │
│    @shopify/cli/node_modules/esbuild/lib/main.js:763)                        │
│    at readFromStdout (../../../../../home/derek/.nvm/versions/node/v20.16.0  │
│    /lib/node_modules/@shopify/cli/node_modules/esbuild/lib/main.js:679)      │
│    at emit (node:events:519)                                                 │
│    at emit (node:domain:488)                                                 │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯`

Node Version v20.16.0 I did try deleting my node_modules folder and installing them again without sucess.

**Comment by saamde** [comment]
My issue was resolved when I realized I had inadvertently included an import from another part of my function in an extension. The error message and stack trace isn't all that useful in pointing the developer towards the issue.
