### ISSUE TITLE
shopifyApp afterAuth hook not running in Vercel

### ISSUE THREAD

**Issue by alexshwe1** [Shopify/shopify-app-template-remix#719]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the `@shopify` packages
  - Affected `@shopify/shopify-*` package and version:
  - Node version:
  - Operating system:
- [x] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

## Expected behavior

afterAuth hook should run to completion in Vercel environments.

## Actual behavior

afterAuth hooks aren't run in Vercel environments.

## Steps to reproduce the problem

1. Add `console.log("DEBUG: Inside afterAuth")` to afterAuth hook
2. Deploy the default shopify remix app in Vercel using Shopify's provided Vercel configuration
3. Install the deployed vercel app in a shopify development store
4. Compare local DEBUG logs to Vercel logs

**Comment by matteodepalo** [comment]
Hi @alexshwe1 thank you for reporting this, we'll take a look.

**Comment by nullndr** [comment]
The `afterAuth()` hook is runned on two specific cases as explained [here](https://github.com/Shopify/shopify-app-template-remix?tab=readme-ov-file#my-webhook-subscriptions-arent-being-updated):

1 - The `Session` row for the shop does not exist
2 - The `Session` row for the shop exists, but is expired

When you get an `app/uninstalled` webhook you should delete the associated session in your db, in order for the `afterAuth()` hook to be triggered again.

**Comment by lizkenyon** [comment]
I am going to close this issue as not reproducible.
