### ISSUE TITLE
Docker image can be greatly reduced in size

### ISSUE THREAD

**Issue by joshuaballoch** [Shopify/shopify-app-template-remix#720]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the `@shopify` packages
  - Affected `@shopify/shopify-*` package and version:
  - Node version:
  - Operating system:
- [ ] [Not really applicable in this case] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

I found that the docker image size created in an app built from this template was very large (around 1.7-1.8 GB). I see that there were previous efforts to reduce the image size, such as #418.

After some investigation locally, I found that the issue was a combination of NPM’s cache not being cleared, as well as Docker’s image layer cache.

I'd like to propose a change that reduces the docker image size from ~1.8 GB to ~500 MB. I don't have permission to open a pull request on this repo, so I'm filing this as an issue with info on the solution I found.

## Proposed Change

The key change in the Dockerfile is to modify the `RUN npm install --omit-dev` line to include a clearing of the NPM cache:

```
RUN npm install --omit=dev && npm cache clean --force
```

This will clear the NPM cache, which reduces the overall image size. This needs to be run on the same `RUN` as the `npm install` or else the docker image layer cache will still include the cached data.

I also would propose that the Dockerfile could copy only the package.json and package-lock.json files before the npm install, to allow docker builds to run faster when the only changes made are to application code.

Here are two images I built locally, from this repo, before and after the fix, to demonstrate the savings:

```
$ docker image ls
REPOSITORY                   TAG          IMAGE ID       CREATED          SIZE
shopify-app-template-remix   after-fix    b1a72b194a84   8 seconds ago    522MB
shopify-app-template-remix   before-fix   d1e581de7c98   8 minutes ago    1.81GB
```

Here is the updated Dockerfile I propose:

```
FROM node:18-alpine

EXPOSE 3000

WORKDIR /app

ENV NODE_ENV=production

COPY package.json package-lock.json* ./

RUN npm install --omit=dev && npm cache clean --force
# Remove CLI packages since we don't need them in production by default.
# Remove this line if you want to run CLI commands in your container.
RUN npm remove @shopify/app @shopify/cli

COPY . .

RUN npm run build

# You'll probably want to remove this in production, it's here to make it easier to test things!
RUN rm -f prisma/dev.sqlite

CMD ["npm", "run", "docker-start"]
```

**Comment by joshuaballoch** [comment]
I also have one question to ask (I'm not familiar enough with npm and yarn to know the answer) - I created an app using this template, where I specified the yarn to be the package manager. The Dockerfile still just uses `npm` - should this be something that changes to yarn, when that package manager is used?

**Comment by lizkenyon** [comment]
Hi there 👋 

Thank you very much for the detailed investigation on this issue!

You can definitely create a PR for this!

You will need to fork the repo first, and the [create a PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) into our main repo.

Regarding your question about the use of NPM, swapping the docker file to use the package manager that is used locally is something we probably should do, to keep environments consistent. This would probably be done at the CLI level, where when initializing the app with the Shopify CLI it would add the appropriate Docker file. So for right now, if you would like to create a PR, you can just leave it with NPM.
