### ISSUE TITLE
Cookies in Shopify Remix App

### ISSUE THREAD

**Issue by aditibpatil** [Shopify/shopify-app-template-remix#726]
I want to store specific data of my app users in cookies in a Shopify Remix app. Can anyone please help me understand how to store and access this data across pages within Shopify embedded apps?

**Comment by lizkenyon** [comment]
Hi there 👋 

[Browsers have restricted the use](https://developer.mozilla.org/en-US/blog/goodbye-third-party-cookies/) of third party cookies. 
These would cover cookies set by an embedded app. So we currently cannot recommend their use.

You may want to review the documentation about [Online Access Tokens](https://shopify.dev/docs/apps/build/authentication-authorization/access-token-types/online-access-tokens) to see if they would be helpful for you for determining the user of your app.
