### ISSUE TITLE
[Question] Authenticate another system after install the app 

### ISSUE THREAD

**Issue by knguyen30111** [Shopify/shopify-app-template-remix#751]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the `@shopify` packages
  - Affected `@shopify/shopify-*` package and version:
    -  "@shopify/app-bridge-react": "^4.1.2",
    -  "@shopify/polaris": "^12.0.0",
    -  "@shopify/shopify-api": "^11.0.0",
    -  "@shopify/shopify-app-remix": "^3.0.0",
    -  "@shopify/shopify-app-session-storage-prisma": "^5.0.0",
  - Node version: 20.14.0
  - Operating system: MacOS Sonoma 14.5
- [ ] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration
- [ ] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [ ] Looked for similar issues in this repository
- [ ] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

## Question
I want to develop the connect account function through my existing system (specifically, login by email and password). While authenticating the user, I also want to include a session token or access token so that my back end can call the Shopify endpoint to get the needed resources.

Is there a way for me to do that by opening a new browser tab and doing the above? Then, after the authenticated user is redirected back to the admin shop page

Thank you so much

## Expected behavior

Can authenticate with another system and send session token as query params

## Actual behavior

What actually happens?

**Comment by nick-potts** [comment]
What exactly are you trying to achieve? You want to link someone's external account with their shopify account?

If that's the case, I would just have them sign in (inside an embedded frame), and your backend can return a jwt token. This token can be stored in your remix database for later use. 

That way when a user has "linked" to your backend, you don't send your shopify auth to your backend. You just authenticate using typical jwt.

**Comment by nick-potts** [comment]
You can do that with a form and target `_blank`, but do bear in mind if the user has to do this as the way to sign into your app, you won't be able to apply for Built for Shopify as it goes against their guidelines.
