### ISSUE TITLE
Bump @shopify/polaris from ^12.0.0 to ^13.4.0

### ISSUE THREAD

**Issue by Siefke1** [Shopify/shopify-app-template-remix#758]
# Update Polaris Version

With the currently used `^12.0.0` Version of `@shopify/polaris` there seems to be a problem when using the `IndexTable` component: It uses `useLayoutEffect` internally which cannot be encoded into the server renderer's output format and hence produces logs like the one described in this issue:

https://github.com/Shopify/polaris/issues/11862

I get the same logs for a Remix App rebased with the latest version of this template.

According to [this](https://github.com/Shopify/polaris/issues/11862#issuecomment-2106794818) response on the issue in the Polaris Github the behaviour was fixed in Polaris `v13.4.0`. But using this version requires Node `^20.10` which requires updating the Node Version for the workflow files as well as the Docker-Image i suspect.

Is this something you are looking to update in your template anytime soon?

**Comment by paulomarg** [comment]
You're right, the only things you'll need to update are the node version and Dockerfile source, so there's no real need for a wiki page. Since it's so small, I added a gotcha to the README for this, thank you!
