### ISSUE TITLE
How can I do SSE and auth session at the same time without a 302 redirect?

### ISSUE THREAD

**Issue by tajbowness** [Shopify/shopify-app-template-remix#759]
I'm trying to make a progress bar with SSE. But I need to get the session id and then call the DB to get the clients progress to pass back.

But when trying to get the session id `const { session } = await authenticate.admin(request)`

This error occurs

`EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.`

Because the `authenticate` line is returning a 302, wanting to redirect the client to login. This breaks the SSE.

This is the catched response from `authenticate`

```
Response {
    [Symbol(realm)]: { settingsObject: {} },
    [Symbol(state)]: {
    aborted: false,
    rangeRequested: false,
    timingAllowPassed: false,
    requestIncludesCredentials: false,
    type: 'default',
    status: 302,
    timingInfo: null,
    cacheState: '',
    statusText: '',
    headersList: HeadersList {
        cookies: null,
        [Symbol(headers map)]: [Map],
        [Symbol(headers map sorted)]: null
    },
    urlList: []
    },
    [Symbol(headers)]: HeadersList {
    cookies: null,
    [Symbol(headers map)]: Map(1) { 'location' => [Object] },
    [Symbol(headers map sorted)]: null
    }
}

```
This is the SSE code
```
import { eventStream } from "remix-utils/sse/server";
import { authenticate } from "../shopify.server";


export async function loader({ request }) {

  const { session } = await authenticate.admin(request);

  let controller = new AbortController();

  request.signal.addEventListener("abort", () => controller.abort());

  let start = Date.now();

  return eventStream(controller.signal, function setup(send) {
    let timer = setInterval(async () => {
      let date = new Date();
      // MAKE DB REQUEST WITH SESSION ID. FETCHS INFO. PASSES IT BACK TO CLIENT
      if (date.getTime() - start > 10000) return controller.abort()

      send({ event: "time", data: "HOLA"});
    }, 1000);

    return function clear() {
      clearInterval(timer);
    };
  });
}

```

What am I doing wrong? Any insight would be much appreciated!

**Comment by tajbowness** [comment]
I've realised that assuming authenticating was possible, it'd be constantly authenticating the user, is there perhaps a way to pass the session id to the SSE loader instead? Apologies, I know this is unrelated now, so feel free to close this issue.

**Comment by lizkenyon** [comment]
Glad you figured it out!

**Comment by lizkenyon** [comment]
If you are able to add context why it is necessary for you to use SSE, (the current limitation of the template) then we can triage investigating adding documentation for how to do this.

Some things to keep in mind.
`authenticate.admin(request)` is for authenticating requests that are initiated from the Shopify Admin. If your request is not being initiated from the admin, then it makes sense that you would get a 302

We do have `const { session } = await unauthenticated.admin(shop);`, for times when you we not need to authenticate your request (because you are doing so already) that you may want to look into to see if it fits your usecase.

**Comment by tajbowness** [comment]
@lizkenyon Thanks for the reply!

Certainly, I can provide context. I'd like to create a progress bar, its for a part of the app that takes longer than 100 seconds for the server to respond to the client, so I need to sustain the connection from the client with the server. There are easier ways to do this. But I wanted to test myself and try and figure out web sockets and SSE, so I've gone for the SSE approach. Instead of just prompting them with "Hey, its all done now" after its finished.

So far from my understanding this is how it works (you likely already know, but I'll provide further context of my actual understanding).

![Capture](https://github.com/Shopify/shopify-app-template-remix/assets/120999614/7c31391e-a6fc-40cc-b9c2-4d75e3d5082b)

Currently it's the left one. I'd like to have the right one but I don't think that's possible. In order to get the clients actual progress, which is stored in the database, I need to get their session id to access the DB. Once it has it, it'll pass the digit value back to the client for it to be rendered on to a progress bar.

> Some things to keep in mind.
authenticate.admin(request) is for authenticating requests that are initiated from the Shopify Admin. If your request is not being initiated from the admin, then it makes sense that you would get a 302

I've already come to that conclusion, but that makes more sense now.

I'll have a look into `const { session } = await unauthenticated.admin(shop);`. 

Are you able to provide context to what you mean by "(the current limitation of the template)"?

Please let me know if you need me to provide additional context :)
