### ISSUE TITLE
No admin object when authenticate.webhook(request) 

### ISSUE THREAD

**Issue by FynnMenkIT** [Shopify/shopify-app-template-remix#763]
# Issue summary

Before opening this issue, I have:

- [X] Upgraded to the latest version of the `@shopify` packages
  - Affected `@shopify/shopify-*` package and version: 
    "@remix-run/dev": "^2.7.1",
    "@remix-run/node": "^2.7.1",
    "@remix-run/react": "^2.7.1",
    "@remix-run/serve": "^2.7.1",
    "@shopify/app": "3.57.0",
    "@shopify/cli": "3.57.0",
    "@shopify/polaris": "^12.0.0",
    "@shopify/shopify-api": "^9.2.0",
    "@shopify/shopify-app-remix": "^2.5.0",
    "@shopify/shopify-app-session-storage-prisma": "^4.0.1",
  - Node version: v16.20.2
  - Operating system: Mac OS 14.4.1 (23E224)
- [X] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration
- [X] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [X] Looked for similar issues in this repository
- [X] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

If I trigger my webhook 
`  webhooks: {
    DISCOUNTS_UPDATE: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/test-endpoint",
    },
  },`
I get a empty admin object, only the topic, shop and payload comes back from authenticate.webhook

I called it via CLI, via test-send in backend and also via actually triggering it in the backend

## Expected behavior

after I call

```
export const action = async ({ request }) => {
  const { admin } = await authenticate.webhook(request);
  console.log('webhook_fired', admin);

...
```

My console log should be defined.
But this simple code wont work:
```
if (admin) {
    const data = await admin.graphql.query<any>({ data: `{shop {name}}` });

    console.log(data.body.data.shop.name);
    const response = await admin.graphql(
            `#graphql
        query webhooks {
            webhookSubscriptions(first: 100) {
                edges {
                    node {
                        id
                        topic
                        endpoint {
                            __typename
                            ... on WebhookHttpEndpoint {
                                callbackUrl
                            }
                            ... on WebhookEventBridgeEndpoint {
                                arn
                            }
                            ... on WebhookPubSubEndpoint {
                                pubSubProject
                                pubSubTopic
                            }
                        }
                    }
                }
            }
        }`
    );
  }
  

    const responseJson = await response.json();
    console.log(responseJson);
```
## Actual behavior

When I call it with or without the v3_webhookAdminContext flag, I get an empty admin object

```
export const action = async ({ request }) => {
  const { admin } = await authenticate.webhook(request);
  console.log('webhook_fired', admin);

...
```
or without the v3_webhookAdminContext

```
export const action = async ({ request }) => {
  const { admin } = await authenticate.webhook(request);
  console.log('webhook_fired', admin);

...
```

## Steps to reproduce the problem

1. register a new webhook
1. try to authenticate the webhook
1. console.log the admin object after the authenticate

## Debug logs

```
22:01:15 │ remix      │ [shopify-api/DEBUG] webhook request is valid
22:01:15 │ remix      │ webhook_fired DISCOUNTS_UPDATE shop.myshopify.com undefined undefined {
22:01:15 │ remix      │   admin_graphql_api_id: 'gid://shopify/DiscountAutomaticNode/1',
22:01:15 │ remix      │   title: 'Automatic free shipping updated',
22:01:15 │ remix      │   status: 'ACTIVE',
22:01:15 │ remix      │   created_at: '2016-08-29T08:00:00-04:00',
22:01:15 │ remix      │   updated_at: '2016-08-29T08:00:00-04:00'
22:01:15 │ remix      │ }

```

**Comment by FynnMenkIT** [comment]
Hey and thanks for the quick answer 

how do I verify that there is a session token for the shop ?
For me it was pretty self explained that i have working connection if the app starts without errors and i got my preview url and a working graphiQL url 

For example I also can access the shopInfo where I get the right shopifyDomain in graphiQL via:
```
query shopInfo {
  shop {
    name
    url
    myshopifyDomain
    plan {
      displayName
      partnerDevelopment
      shopifyPlus
    }
  }
}
```

**Comment by FynnMenkIT** [comment]
Thanks @mohamedhaddi  for your mention but this problem is not related. We dont deploy to fly.io. I try to run it locally with prisma and sqlite.

When I start my remix app then there is also this log, which shows me that my configuration is working correct:
```
13:49:49 │                 remix │ Environment variables loaded from .env
13:49:49 │                 remix │ Prisma schema loaded from prisma/schema.prisma
13:49:49 │                 remix │ Datasource "db": SQLite database "dev.sqlite" at "file:dev.sqlite"
13:49:49 │                 remix │
13:49:49 │                 remix │ 1 migration found in prisma/migrations
13:49:49 │                 remix │
13:49:49 │                 remix │
13:49:49 │                 remix │ No pending migrations to apply.
```

btw this is the migration for the session table:

```
CREATE TABLE "Session" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "shop" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "isOnline" BOOLEAN NOT NULL DEFAULT false,
    "scope" TEXT,
    "expires" DATETIME,
    "accessToken" TEXT NOT NULL,
    "userId" BIGINT
);
```

In addition and to be clear about it, I have a problem with webhook authentication. The authentication via loader in the app is working:
```
export const loader = async ({ request }) => {
  await authenticate.admin(request);
```
so only on my registered webhooks I have the problem that I dont get a admin object back with the request I trigger via CLI or via a webhook "send test".

**Comment by FynnMenkIT** [comment]
I would be glad to hear other answers about my problem. 

Maybe its my local app. I will try to host it on a live instance..

**Comment by mohamedhaddi** [comment]
@FynnMenkIT as @lizkenyon suggested, could you verify if you have a session token for your shop in the database? Try to log it with something like `console.log(await db.session.findMany({ where: { shop } }))`.

Also, do you initially get an admin object with the webhook upon first install of the app, but only stop getting it afterwards on later attempts?

**Comment by FynnMenkIT** [comment]
No i never got an admin object. 
Also another coworker has the same problem with our instance.

I have two problems now I guess:
1. I get an hmac validatione Error on anyhow I fire the webhook. (via Store, via Test trigger, via CLI)
example of my CLI trigger:
2. If I put the console.log before the authenticate.webhook, because obviously I cant put it after the authenticate method. The console.log outprint gives an error: ReferenceError: Cannot access 'shop' before initialization


My next attemps now are :
* use the toml for webhook subscription https://shopify.dev/docs/api/webhooks/2024-01?reference=toml
* use the v3 instead the v3 adminRequest flag

I am grateful for any new information regarding my problems
