### ISSUE TITLE
Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.

### ISSUE THREAD

**Issue by codex5** [Shopify/shopify-app-template-remix#773]
# Issue summary

My specs:

- Node version: v20.15.0
- Operating system: MacOS Sonoma
- Firefox with no extension

My package.json packages
```
"dependencies": {
    "@prisma/client": "^5.11.0",
    "@remix-run/dev": "^2.10.0",
    "@remix-run/node": "^2.10.0",
    "@remix-run/react": "^2.10.0",
    "@remix-run/serve": "^2.10.0",
    "@shopify/app-bridge-react": "^4.1.2",
    "@shopify/polaris": "^12.0.0",
    "@shopify/shopify-api": "^11.1.0",
    "@shopify/shopify-app-remix": "^3.0.2",
    "@shopify/shopify-app-session-storage-prisma": "^5.0.2",
    "isbot": "^5.1.0",
    "prisma": "^5.11.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "vite-tsconfig-paths": "^4.3.1"
  },
  "devDependencies": {
    "@remix-run/eslint-config": "^2.10.0",
    "@shopify/api-codegen-preset": "^1.0.1",
    "@types/eslint": "^8.50.0",
    "@types/node": "^20.6.4",
    "@types/react": "^18.2.32",
    "@types/react-dom": "^18.2.15",
    "eslint": "^8.44.0",
    "eslint-config-prettier": "^9.1.0",
    "prettier": "^3.2.4",
    "typescript": "^5.2.2",
    "vite": "^5.1.3"
  },
```

## Expected behavior

The app should work properly without any errors thrown on the console inspector.

## Actual behavior
![image](https://github.com/Shopify/shopify-app-template-remix/assets/33718109/f63a1137-9d66-45ab-80ce-638953936e95)

The app can not work properly, the UI can be loaded, but the remix routes are not working.
Also there are hydration error messages from the console.

## Steps to reproduce the problem

1. Create a new app by running `yarn create @shopify/app`
2. Run `npm run dev` to start the app proxy
3. Open the app on your development store
4. Open the console tab from the browser inspector
5. You gonna see the error messages

## Debug logs

```
Warning: Expected server HTML to contain a matching <head> in <html>.
head
html
App
RenderedRoute@https://marshall-stage-bangladesh-therapy.trycloudflare.com/node_modules/.vite/deps/chunk-FPLWQC6Y.js?v=cedce92b:400:7
RenderErrorBoundary@https://marshall-stage-bangladesh-therapy.trycloudflare.com/node_modules/.vite/deps/chunk-FPLWQC6Y.js?v=cedce92b:357:5
DataRoutes@https://marshall-stage-bangladesh-therapy.trycloudflare.com/node_modules/.vite/deps/chunk-FPLWQC6Y.js?v=cedce92b:1386:7
Router@https://marshall-stage-bangladesh-therapy.trycloudflare.com/node_modules/.vite/deps/chunk-FPLWQC6Y.js?v=cedce92b:744:7
RouterProvider@https://marshall-stage-bangladesh-therapy.trycloudflare.com/node_modules/.vite/deps/chunk-FPLWQC6Y.js?v=cedce92b:1203:7
RemixErrorBoundary@https://marshall-stage-bangladesh-therapy.trycloudflare.com/node_modules/.vite/deps/chunk-FPLWQC6Y.js?v=cedce92b:2736:5
RemixBrowser@https://marshall-stage-bangladesh-therapy.trycloudflare.com/node_modules/.vite/deps/chunk-FPLWQC6Y.js?v=cedce92b:4300:46
```

```
Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    React 12
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    js scheduler.development.js:571
    js scheduler.development.js:633
    __require chunk-VRMXEQCD.js:15
    js index.js:6
    __require chunk-VRMXEQCD.js:15
    React 2
    __require chunk-VRMXEQCD.js:15
    js React
    __require chunk-VRMXEQCD.js:15
    <anonymous> chunk-FPLWQC6Y.js:43
```

```
Error: Hydration failed because the initial UI does not match what was rendered on the server.
    React 9
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    js scheduler.development.js:571
    js scheduler.development.js:633
    __require chunk-VRMXEQCD.js:15
    js index.js:6
    __require chunk-VRMXEQCD.js:15
    React 2
    __require chunk-VRMXEQCD.js:15
    js React
    __require chunk-VRMXEQCD.js:15
    <anonymous> chunk-FPLWQC6Y.js:43
```

**Comment by paulomarg** [comment]
Hi, thanks for raising this. I just created an app and I'm not seeing this error on a freshly installed Firefox.

Can you confirm whether
- you made any changes to the app after creating it?
- the issue still happens if you try again?

Unfortunately, if we can't reproduce the error there's not a lot we can do here. I'd also recommend checking whether there is something wrong with the document request for the page that's failing.

**Comment by ccarlosm** [comment]
In a new fresh installation this is the package.json I get and no problems of that kind:

```
"dependencies": {
    "@prisma/client": "^5.11.0",
    "@remix-run/dev": "^2.7.1",
    "@remix-run/node": "^2.7.1",
    "@remix-run/react": "^2.7.1",
    "@remix-run/serve": "^2.7.1",
    "@shopify/app-bridge-react": "^4.1.2",
    "@shopify/polaris": "^12.0.0",
    "@shopify/shopify-api": "^11.1.0",
    "@shopify/shopify-app-remix": "^3.0.2",
    "@shopify/shopify-app-session-storage-prisma": "^5.0.2",
    "isbot": "^5.1.0",
    "prisma": "^5.11.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "vite-tsconfig-paths": "^4.3.1"
  },
  "devDependencies": {
    "@remix-run/eslint-config": "^2.7.1",
    "@shopify/api-codegen-preset": "^1.0.1",
    "@types/eslint": "^8.40.0",
    "@types/node": "^20.6.3",
    "@types/react": "^18.2.31",
    "@types/react-dom": "^18.2.14",
    "eslint": "^8.42.0",
    "eslint-config-prettier": "^9.1.0",
    "prettier": "^3.2.4",
    "typescript": "^5.2.2",
    "vite": "^5.1.3"
  },
```

node version: v20.11.1

**Comment by codex5** [comment]
hi @paulomarg 
can we somehow get the SSR-ed content and then compare to the one from client side?

**Comment by paulomarg** [comment]
Hi, unfortunately there is no official way to get a diff for now, but React is planning on addressing that in v19: https://react.dev/blog/2024/04/25/react-19#diffs-for-hydration-errors

The error message they mention here might be helpful - these are typical causes for this:
- A server/client branch if (typeof window !== 'undefined').
- Variable input such as Date.now() or Math.random() which changes each time it’s called.
- Date formatting in a user’s locale which doesn’t match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

But if this is happening on a fresh app (which it doesn't for anyone else as far as I know), the only thing I can think of is browser extensions, and there's not a lot we can do about that from this template.

The easiest way might be to turn them all off and then turn them back on one at a time to figure out which one it is.

**Comment by codex5** [comment]
@paulomarg thank you for the update.
Do you think these errors cause the issue?
<img width="1549" alt="image" src="https://github.com/user-attachments/assets/f48ebaa9-343f-4439-aa0b-518662b09730">

**Comment by codex5** [comment]
I just tried again and saw that it works on the dev mode (npm run dev)
but doesn't work with npm run start
it throws an error message: TypeError: Failed to resolve module specifier ".prisma/client/index-browser". Relative references must start with either "/", "./", or "../".

**Comment by huykon** [comment]
I'm having the same issue when create new shopify remix app
