### ISSUE TITLE
Paths ~ not being recognized

### ISSUE THREAD

**Issue by arimtiaz** [Shopify/shopify-app-template-remix#774]
It is showing this error, and I posted on the shopify community and seems like a lot of other people are facing this problem recently.

![image](https://github.com/Shopify/shopify-app-template-remix/assets/83642378/a6fa4524-5f33-4459-9ea8-977bf108f2d2)

**Comment by paulomarg** [comment]
Hey, I think this issue might have been solved by https://github.com/Shopify/shopify-app-template-remix/pull/769 which is no longer using the `~` shorthand.

Can you please confirm whether this still happens for new apps?
