### ISSUE TITLE
Handle unauthenticated request

### ISSUE THREAD

**Issue by asacarter** [Shopify/shopify-app-template-remix#775]
The template does not have any configuration settings for the login route.

It automatically redirects to `auth/login`. I would like to specify my own route to an unauthenticated page or have it just return unauthenticated so I can handle my own logic if a user is not authenticated.

`const { admin } = await authenticate.admin(request);`

**Comment by paulomarg** [comment]
Hey, thanks for raising this! Just to help me understand the problem better, could you please clarify:

1. are you trying to create an unauthenticated endpoint?
1. or are you trying to handle the "error" scenario of `authenticate.admin` differently?

If it's number 2, and you simply want to override the `auth/login` endpoint, it's in the template in `app/routes/auth.login/route.tsx`.

One option would be to skip the `await login(request)` calls in that file, which are what trigger the automatic redirection in the template. That page will by default show a login form if there is no shop parameter, or trigger a login if there is one.

Hope this helps!

**Comment by paulomarg** [comment]
I see, I think that's a great point - so you basically want to be able to call the authentication but handle the failure cases yourself.

I like the idea, but it's worth pointing out that there are quite a few edge cases in that authentication that we need to be mindful of, so we'd need to do some thinking on it.

In any case, I'll bring it to the team and get back to you!
