### ISSUE TITLE
git tracks .env files after running shopify config use

### ISSUE THREAD

**Issue by danyn** [Shopify/shopify-app-template-remix#778]
# Issue summary

Before opening this issue, I have:

- [ ] Upgraded to the latest version of the `@shopify` packages
  - Affected `@shopify/shopify-*` package and version:
  - Node version:
  - Operating system:
- [ ] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration
- [ ] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [ ] Looked for similar issues in this repository
- [ ] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

## Expected behavior
What do you think should happen?
.env files should never be tracked!

## Actual behavior

What actually happens?
.env files could be tracked after funning shopify config use
## Steps to reproduce the problem

1. run shopify config use 
2. check your version control

## Debug logs

```
// Paste any relevant logs here
```

**Comment by paulomarg** [comment]
Thanks for raising this, we should indeed not be tracking the `.env` file if that is happening! We'll look into it!

**Comment by lizkenyon** [comment]
Hi there 👋 

I wasn't able to reproduce on my side. Could you confirm the steps for reproduction for me?

This is what I did
`shopify app init`

`shopify app dev`

Create a .env file in the root folder

Before `shopify app config use` my git status showed this
![Image](https://github.com/user-attachments/assets/a21a2007-4b35-440d-a4d3-67195321a4d8)

`shopify app config use`

After my .env file is not being tracked in git.

![Image](https://github.com/user-attachments/assets/b43a5ba6-da9d-4b72-b34d-dccef7e6af5d)
