### ISSUE TITLE
Question: How do I access a shop ID (bigint) in the loader?

### ISSUE THREAD

**Issue by asacarter** [Shopify/shopify-app-template-remix#784]
The response from authenticate does not contain the int value of a store.

Is this now a legacy value and should I use the myshopify domain as the ID instead? And is this because JavaScript can't do BigInts?

Assuming I can get it with a graph query but thats an additional request.

**Comment by ccarlosm** [comment]
It contains admin, and probably you can get the shop id with ``` admin.rest.shop.id ```
