### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by FireAnt121** [Shopify/shopify-app-template-remix#794]
# I was getting process is not defined, on dev mode

Before opening this issue, I have:

- [x] Upgraded to the latest version of the `@shopify` packages
  - Affected `@shopify/shopify-*` package and version:
  - Node version:
  - Operating system:
- [x] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration
- [ ] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [ ] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

This might be only me, but i was getting process is not defined from remix-run/node. Maybe i messed with something, which got me into this situation. My main query is towards, since we are using vite, are not vite env imported using import.meta.env. If it was working, how was this solved before?

## Expected behavior
Run smoothly, without console giving me error

## Actual behavior
Console, gives error of process is not defined

## Debug logs
![image](https://github.com/user-attachments/assets/6b2c01f3-8d73-4eae-a9e0-505604f2f7eb)
adding this solved it

**Comment by Arkham** [comment]
hey @FireAnt121, thanks for reporting this issue. could you provide some replication steps? such as node version, which package manager you use, OS, etc?
