### ISSUE TITLE
Requests to the REST api return 401 / 302 after authentication

### ISSUE THREAD

**Issue by KeKs0r** [Shopify/shopify-app-template-remix#797]
# Issue summary
I have a loader in my app._index that is authenticating the admin API and then trying to query the shop from the REST api. I am always  able to successfully authenticate, but often the subsequent request to the rest API then fails with a 302 status code. The issue mainly occurs after "reinstalling" the app and it most of the time only applies to the first load.  I was not yet able to perfectly reliably reproduce it, but it happens often enough. This alone makes me think it might be a race condition.

Before opening this issue, I have:

- [ ] Upgraded to the latest version of the `@shopify` packages
  - Affected `@shopify/shopify-*` package and version:
 ```
 "@shopify/shopify-api": "^10.0.0",
"@shopify/shopify-app-remix": "^2.8.2",
"@shopify/shopify-app-session-storage-kv": "^4.0.0",
```
-> I cant upgrade to the latest 3.X, due to issues with vite and wrangler together
  - Node version: This runs in cloudflare pages
  - Operating system: osx, but I am observing it deployed on cloudflare
- [x] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration
- [ ] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

## Expected behavior
After successfully authenticating against the admin api and validating the token, I would expect that I can reliably request data from the Shopify API. Those requests are answered with a 302 and a redirect to `/auth/session-token`

## Actual behavior
The logs indicate that the session token is valid, but using the session to request from the API results into the 302. I am observing that on that first request I am authenticating multiple times:
- loader in app.tsx
- loader in app._index.tsx
- afterAuth hook from the app.

## Debug logs
Full Logs are here: https://gist.github.com/KeKs0r/73281aa6625433c903d4aea029b66078

```
 "[shopify-app/DEBUG] Validating session token"
"[shopify-app/DEBUG] Session token is valid | {payload: {\"iss\":\"https://convea-demo.myshopify.com/admin\",\"dest\":\"https://convea-demo.myshopify.com\",\"aud\":\"414d71062e73c13562f60cadc290dc7b\",\"sub\":\"92021948629\",\"exp\":1722239864,\"nbf\":1722239804,\"iat\":1722239804,\"jti\":\"cbc3a9a6-fe76-4ddd-8e6f-0386b5f53c1a\",\"sid\":\"6602e822-f3ac-4911-98a3-439bc092ca1f\",\"sig\":\"a034ed6fb6a132e2a101123c9896f31551b630320358a40e2c7ba6d22f819fd4\"}}"
 "[shopify-app/DEBUG] Loading session from storage | {sessionId: offline_convea-demo.myshopify.com}"
 "[shopify-app/DEBUG] Got an HTTP response error from the API: Received an error response (401 Unauthorized) from Shopify:\n\"[API] Invalid API key or access token (unrecognized login or wrong password)\"\nIf you report this error, please include this id: ba3ab041-a63b-447a-b6e2-b84565ecce97-1722239806 | {code: 401, statusText: Unauthorized, body: {\"errors\":\"[API] Invalid API key or access token (unrecognized login or wrong password)\"}}"
```

**Comment by KeKs0r** [comment]
I thought this was the case, and even ensured to delete all sessions for the shop on uninstall: 
```
		case 'APP_UNINSTALLED':
			const sessions = await shopify.sessionStorage.findSessionsByShop(shop);
			await Promise.all(sessions.map(async (session) => shopify.sessionStorage.deleteSession(session.id).catch(console.error)));
			throw new Response('OK', { status: 200 });
```

**Comment by lizkenyon** [comment]
As @ccarlosm mentioned if you are using the Shopify CLI to manage your tunnels your URL will change. This means that you are starting and stoping your app server and your webhook subscription isn't updated it may mean you don't receive those `APP_UNISTALLED` webhooks. 

I am going to close this issue. If you are still seeing issues and you think it may be unrelated to the shop information not getting cleared from the database, please reopen.
