### ISSUE TITLE
Duplicated webhooks when migrating to declarative webhooks

### ISSUE THREAD

**Issue by nullndr** [Shopify/shopify-app-template-remix#805]
I am trying to migrate the webhooks registration process inside my app to the [new declarative webhooks method](https://shopify.dev/docs/apps/build/webhooks/subscribe/get-started?framework=remix&deliveryMethod=eventBridge).

With my suprise, webhooks are being triggered twice, it does not look like the new method register the topic on [Graphql](https://shopify.dev/docs/api/admin-graphql/2024-10/mutations/eventBridgeWebhookSubscriptionCreate), so there is it and the already existing webhook subscription registration on Graphql that trigger the same webhook.

**Comment by matteodepalo** [comment]
Hi @nullndr I found where a warning for this is documented https://shopify-dev.shopify-dev-eqeh.anita-mehrotra.us.spin.dev/docs/apps/build/webhooks/subscribe#app-specific-vs-shop-specific-subscriptions

Basically, if you want to have overlap and not miss webhooks, you should allow for some duplicates in your code and delete the existing webhook subscriptions after having deployed the config changes.
