### ISSUE TITLE
Sync two shopify stores with this shopify-app-template-remix

### ISSUE THREAD

**Issue by FynnMenkIT** [Shopify/shopify-app-template-remix#819]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the `@shopify` packages
  - Affected `@shopify/shopify-*` package and version: `@shopify/remix-app@x.x.x`
  - Node version: `v16.13.0`
  - Operating system: `macOS Monterey 12.4`
- [x] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

## Expected behavior

I have a Remix app installed in two different Shopify stores. I've registered webhooks to capture the creation of new discount codes in one store, and I want these discount codes to be automatically sent and applied to the other store.

My current approach involves using the Shopify access token. To do this, I understand I need to install another app in the target store to retrieve the `x-shopify-access-token` as described [here](https://support.syncmadeasy.com/configuration-articles/how-to-retrieve-the-shopify-access-token/).

However, I suspect there may be a better or more efficient way to achieve this synchronization without the need for an additional app installation.

## Actual behavior

Right now, my approach requires installing an extra app in each store to retrieve the access token, which seems cumbersome. I’m looking for guidance or alternative methods that would allow for seamless discount code synchronization between the two stores.

## Steps to reproduce the problem

1. Install a Remix app in two different Shopify stores.
2. Register webhooks to capture discount code creation.
3. Attempt to send the captured discount code to the other store using the Shopify access token.

## Debug logs

```javascript
// Not applicable as this is more of a feature implementation request rather than a bug report.
```

## Current Code
import { authenticate } from '../shopify.server';
import db from "../db.server";

const URL_STORE_1 = "sheko-staging.myshopify.com";
const URL_STORE_2 = "elbdev-checkout.myshopify.com";
const ACCESS_TOKEN_STORE_1 = "ACCESS-CODE";
const ACCESS_TOKEN_STORE_2 = "ACCESS";

const GRAPHQL_HEADERS = (shop) => ({
  "Content-Type": "application/json",
  "X-Shopify-Access-Token": shop === URL_STORE_1 ? ACCESS_TOKEN_STORE_1 : ACCESS_TOKEN_STORE_2,
});

const sendGraphQL = async (query, shop) => {
  const url = shop === URL_STORE_1 ? `https://${URL_STORE_1}/admin/api/2024-07/graphql.json` : `https://${URL_STORE_2}/admin/api/2024-07/graphql.json`;
  const response = await fetch(url, {
    method: "POST",
    headers: GRAPHQL_HEADERS(shop),
    body: JSON.stringify({ query }),
  });
  return response.json();
};

export const action = async ({ request }) => {
  console.log('test-endpoint_fired', request);

  const { topic, shop, session, admin, payload } = await authenticate.webhook(request);
  console.log(await db.session.findMany({ where: { shop } }));
  console.log('test-endpoint_admin', admin);
  console.log('test-endpoint_rest', { topic, shop, session, admin, payload });

  if (!admin) {
    throw new Response();
  }

  if (admin) {
    const discountData = await admin.graphql(
      `#graphql
      query getDiscount($id: ID!) {
        discountNode(id: $id) {
          id
          code
          usageLimit
          startsAt
          endsAt
          appliesOncePerCustomer
          appliesToProductVariants {
            id
            title
          }
          appliesToCollections {
            id
            title
          }
          appliesToCustomerSegments {
            id
            name
          }
          minimumRequirement {
            ... on DiscountMinimumQuantity {
              greaterThanOrEqualToQuantity
            }
            ... on DiscountMinimumSubtotal {
              greaterThanOrEqualToSubtotal {
                amount
                currencyCode
              }
            }
          }
          customerGets {
            items {
              ... on DiscountItemsProduct {
                products {
                  id
                  title
                }
              }
              ... on DiscountItemsCollection {
                collections {
                  id
                  title
                }
              }
            }
            value {
              ... on DiscountPercentage {
                percentage
              }
              ... on DiscountFixedAmount {
                amount {
                  amount
                  currencyCode
                }
              }
            }
          }
        }
      }
    `,
      { id: payload.admin_graphql_api_id }
    );

    console.log(discountData);
    console.log('topic', topic);
    let query;
    switch (topic) {
      case "DISCOUNTS_ADD":
        //todo
        console.log('DISCOUNTS_ADD', request, discountData, admin, session, shop, payload);
        break;
      case "DISCOUNTS_DELETE":
        //todo
        console.log('DISCOUNTS_DELETE', request, discountData, admin, session, shop, payload);
        break;
      case "DISCOUNTS_UPDATE":
        query = `
        mutation {
          discountUpdate(id: "${discountData.discountNode.id}", discountCode: {
            code: "${discountData.discountNode.code}",
            usageLimit: ${discountData.discountNode.usageLimit},
            startsAt: "${discountData.discountNode.startsAt}",
            endsAt: "${discountData.discountNode.endsAt}",
            appliesOncePerCustomer: ${discountData.discountNode.appliesOncePerCustomer},
            appliesToProductVariants: ${JSON.stringify(discountData.discountNode.appliesToProductVariants)},
            appliesToCollections: ${JSON.stringify(discountData.discountNode.appliesToCollections)},
            appliesToCustomerSegments: ${JSON.stringify(discountData.discountNode.appliesToCustomerSegments)},
            minimumRequirement: ${JSON.stringify(discountData.discountNode.minimumRequirement)},
            customerGets: ${JSON.stringify(discountData.discountNode.customerGets)}
          }) {
            discountCode {
              id
              code
              usageLimit
              startsAt
              endsAt
            }
            userErrors {
              field
              message
            }
          }
        }
      `;
        break;
      default:
        throw new Response("Unhandled webhook topic", { status: 404 });
    }

    // Execute the mutation
    const updatedDiscount = await admin.graphql(query);
    console.log('Updated Discount:', updatedDiscount);

    if (query) {
      await Promise.all([
        sendGraphQL(query, URL_STORE_1),
        sendGraphQL(query, URL_STORE_2),
      ]);
    }
  }

  throw new Response();
};

**Comment by paulomarg** [comment]
If I understood the problem correctly, you're essentially using webhooks to sync up the discounts, right? So, one option you would have is to get the `admin` object from the webhook authentication, and then create an unauthenticated client to the other store.

This is a bit simplified, but this is what I have in mind:

```ts
import { unauthenticated } from '../shopify.server';

const { topic, shop, session, admin } = await authenticate.webhook(request);
const otherShop = shop === SHOP1 ? SHOP2 : SHOP1;
const { admin: otherAdmin } = await unauthenticated.admin(otherShop);

// Create discount in other store
await otherAdmin.graphql(
  `#graphql ...`,
);
```

I think this isn't really a bug in the package / template, so there won't be much else we can do here, but I hope that helps!
