### ISSUE TITLE
Vite server server keeps refreshing.

### ISSUE THREAD

**Issue by tajbowness** [Shopify/shopify-app-template-remix#837]
Hello,

This issue has only started occuring today. Everything was working perfectly fine yesterday. Also on my other project that I haven't touched in a week, is also getting the same issue.

Basically, the vite server keeps refreshing.

![Image](https://github.com/user-attachments/assets/85da8803-8ab9-4353-8067-1acdbbf2de31)

![Image](https://github.com/user-attachments/assets/5a1faa83-c7ae-4783-9725-277a5981d296)

Browser console error logs

![Image](https://github.com/user-attachments/assets/90dc6fd8-686d-49f2-af76-35b4eb754f65)

Browser console info logs

In `vite.config.js`,

```
if (host === "localhost") {
  hmrConfig = {
    protocol: "ws",
    host: "localhost",
    port: 64999,
    clientPort: 64999,
  };
} else {
  hmrConfig = {
    protocol: "wss",
    host: host,
    port: parseInt(process.env.FRONTEND_PORT) || 8002,
    clientPort: 443,
  };
}

```
For now I've had to change the clientPort to something other than `443`, which stops the issue, but you lose HMR.

Unsure if this issue should be posted to the this repo, so please move it if necessary. I believe it's a Shopify issue as creating a test remix app like this `npx create-remix@latest` , the issue doesn't occur. And someone on Shopify forums reported the same problem today.

https://community.shopify.com/c/shopify-apps/continuous-re-auth-by-shopify-admin-api/m-p/2726541#M82476

I'm on Chrome. But it's also occuring on Edge.

**Comment by anhdd-kuro** [comment]
Same here

**Comment by vincaslt** [comment]
Also getting the same issue, started getting it on an existing application, so decided to test on a fresh install - also keeps refreshing.

**Comment by Detek001** [comment]
same here

**Comment by NavasMuhammed** [comment]
same here

**Comment by Dezital** [comment]
I am also facing this same issue after last night

**Comment by dani-sanomads** [comment]
We are having exactly same issue

**Comment by yosef-grant** [comment]
we're having the same issue. tried updating to the latest version of the CLI (3.66.0)  but no change.

![Image](https://github.com/user-attachments/assets/90723aad-7d5c-4a04-9f82-b73d709077d6)

**Comment by CurtisPine** [comment]
Also experiencing this issue. Cannot run any app at the moment.

**Comment by myrkoharmatiy** [comment]
+1

**Comment by themistoklis-bogiatzoglou** [comment]
Workaround until they'll fix this: 

1. Install ngrok in your system.
2. Create a free account in ngrok. And go to Domains and create a Domain and copy it.
3. Run ngrok,exe
4. Then change the port number in command from 80 to 8080 . Run the command in local to create a tunnel. eg. ngrok http --domain=xxx-xxxxxxxxx-xxxxxx.ngrok-free.app 80805. 
5. In your shopify project run `npm run dev -- --tunnel-url="xxx-xxxxxxxxx-xxxxxx.ngrok-free.app:8080"`

**Comment by tnishikata** [comment]
same here

**Comment by paulomarg** [comment]
It seems that cloudflare tunnels are working again, so I'm going to close this issue.

**Comment by philipp-eisen** [comment]
I don't think it's fixed. I still get the same behavior as above and can fix it by providing my own tunnel.
