### ISSUE TITLE
Hosting Embedded Shopify App Admin Portal outside of Shopify for internal use

### ISSUE THREAD

**Issue by ghussain08** [Shopify/shopify-app-template-remix#841]
I have a Shopify app with an admin portal that is embedded within the store dashboard. Now, I want to make the same admin portal available for our team to use independently. The idea is that our team members should be able to log in as any store to assist with any issues.

When our team tries to log in in our app admin portal by directly visiting the hosted URL, Remix redirects them to the logged-in store's admin portal, where they do not have access. This redirection prevents them from accessing the app’s admin portal in the intended way.

Is it possible to achieve what I'm trying to do? If yes, how can I set up the admin portal so our team can access it independently without being redirected to the store's admin portal?

**Comment by lizkenyon** [comment]
Hi there 👋 

At this time with the Remix template we do not have any guidance on running the app this way. And our recommendation would be to use collaborator access via the Partner dashboard. 

I will flag with the team that this is functionality that you are interested in.
