### ISSUE TITLE
Webhooks is not triggering.

### ISSUE THREAD

**Issue by masumluf** [Shopify/shopify-app-template-remix#858]
Yesterday I have created an app using Shopify CLI command. I am trying to print some log whenever anybody uninstall my app. Here is my code below 

**shopify.app.tomal** file
  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

**webhooks.app.uninstalled.jsx** in the routes folder file
```
import { authenticate } from "../shopify.server";
import db from "../db.server";

export const action = async ({ request }) => {
  console.log("--- uninstall hook triggered ---");
  const { shop, session, topic } = await authenticate.webhook(request);

  console.log(`Received ${topic} webhook for ${shop}`);

  console.log(shop, session, topic, "shop, session, topic");

  if (session) {
    db.session.deleteMany({ where: { shop } });
  }

  return new Response();
};
```
Since I am new in shopify app development. I am unable to figure out why this portion of code is not executing while anybody uninstall my app ?Is there anything I have missed ? My

**Comment by imrostom** [comment]
Please checked registerd webhook list via api call. please check this example https://shopify.dev/docs/api/admin-rest/2024-01/resources/webhook#get-webhooks
