### ISSUE TITLE
What is the usage of /routes/_index/route.tsx in template

### ISSUE THREAD

**Issue by watislaf** [Shopify/shopify-app-template-remix#865]
What is the purpose of file /routes/_index/route.tsx as it seems impossible to reach it. When i logged in i'm just getting redirected  from / to /app . when i am not logged in this page is not displayed. When app is uninstalled this page simply tells 404 not found. So what is the purpose and how to reach this route ? 

There is an open similar [question](https://community.shopify.com/c/shopify-apps/is-the-app-index-folder-included-in-the-shopify-remix-template/td-p/2410138).

**Comment by lizkenyon** [comment]
Hi there 👋 

This page has a couple of purposes. 
It was intended to be an example of a "marketing" or landing page. This would be an example of how your application could host public pages outside of the authenticated merchant admin.

It was also to handle to edge case of 
1) An app is not embedded
2) A merchant bookmarks a page in the app
3) A merchant looses their cookie.
4) The app has no way to identify the user

In local development you can access this page by going directly to your tunnel URL in the browser.
