### ISSUE TITLE
clone template error

### ISSUE THREAD

**Issue by xgqfrms** [Shopify/shopify-app-template-remix#869]
```sh
$ shopify app init --package-manager=yarn


Cloning into '/private/var/folders/by/24_sdryj5sv4qvxcyjfnn64c0000gn/T/7407c468964a49b0dd4901e34c56db09/download'...      
fatal: unable to access 'https://github.com/Shopify/shopify-app-template-remix/': Failure when receiving data from the peer  

```

![Image](https://github.com/user-attachments/assets/e832c96c-e136-4f8b-bc0d-bb42338757be)

**Comment by lizkenyon** [comment]
Hi there 👋 

I don't believe this is an issue with the template. It may be an issue with your firewall preventing the cloning. I would recommending researching the error message.
