### ISSUE TITLE
Why doesn't the token work?

### ISSUE THREAD

**Issue by Sinevik** [Shopify/shopify-app-template-remix#894]
I created the remix app and dev store according to the documentation.

 

I save the accesToken that I get when installing the application

![Image](https://github.com/user-attachments/assets/360279bc-61b1-41aa-a1d5-a7323420c1d3)

Now I want to use this token to get store products. According to the documentation, I make a request:

![Image](https://github.com/user-attachments/assets/d002cf49-32f3-4e9f-af2f-f5de9ae981c4)

I add the token according to the documentation

![Image](https://github.com/user-attachments/assets/5c85f3fb-63b4-4e39-905f-747953509add)

Can you please tell me why I'm getting an error? 

 

401 Unauthorized

""errors": "[API] Invalid API key or access token (unrecognized login or wrong password)"

**Comment by Sinevik** [comment]
Created a new dev store and installed there. The problem disappeared. For some reason, when you uninstall the app and dev store and then install it again, the token is not updated via remix. It's a terrible bug

**Comment by lizkenyon** [comment]
Hi there 👋 

Yes, if you stop your app server before you uninstall then your app can't receive the `APP_UNINSTALLED` webhook event. So your old token won't have been deleted from the DB. 
If you are using Shopify managed installed then you access token won't be updated until you try to make a request to the API. 

Glad you were able to figure it out and get your access token.
