### ISSUE TITLE
Plans for React Router 7?

### ISSUE THREAD

**Issue by mkromann** [Shopify/shopify-app-template-remix#903]
Hi,

Since it seems like the remix team has made the switch to React Router 7 now. What are the plans for this repo? Will it be updated, or will you publish a new one?

/Magnus

**Comment by lehoangnnx** [comment]
This is also an issue that I am interested in, hope to receive information from the development team.

**Comment by mkromann** [comment]
Ah great! Then @paulomarg would be the one to know most likely :)

**Comment by bakikucukcakiroglu** [comment]
Any updates?
